### ISSUE TITLE
Switch images to Python 3.8

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1023]
Both in .taskcluster.yml and in the dockefiles under infra/.

**Comment by dotslash21** [comment]
Hi! I'd like to work on this issue.

**Comment by marco-c** [comment]
Sure, feel free!

**Comment by marco-c** [comment]
The Docker images were switched with https://github.com/mozilla/bugbug/commit/1142f8a1bea791d78fa8d15c66f7d0aed549a4de.

**Comment by InfTkm** [comment]
> The Docker images were switched with [1142f8a](https://github.com/mozilla/bugbug/commit/1142f8a1bea791d78fa8d15c66f7d0aed549a4de).

Is this issue closed now?

**Comment by marco-c** [comment]
No, we still need to update .taskcluster.yml.

**Comment by InfTkm** [comment]
> No, we still need to update .taskcluster.yml.

Hi, I would like to work on this issue as my first contribution. Thank you!

**Comment by InfTkm** [comment]
I have read the Taskcluster log of the previous PR in this issue, and the reason it failed the tests was the incompatibility between python:3.8 and Scipy library back then. It is no longer an issue now. I have successfully installed Scipy on my local container running python:3.8.
However, Tensorflow is incompatible with Python 3.8 right now, [issue](https://github.com/tensorflow/tensorflow/issues/33374). Therefore, each time the Taskcluster uses python:3.8 as an image and run pip install in the instance, there will be errors. (failed on my local container as well)
I guess we'll wait for Tensorflow's update then.

**Comment by marco-c** [comment]
Thanks for testing it! So we have to wait a bit more in order to update.

**Comment by mdb571** [comment]
Hello I would like to work on this issue.

**Comment by marco-c** [comment]
@mdb571 read the discussion above :)

**Comment by marco-c** [comment]
This should now be feasible, since a new version of Tensorflow which supports Python 3.8 has been released.
