### ISSUE TITLE
Extend the whiteboard feature to consider all possible whiteboard words

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#104]
https://github.com/mozilla/bugbug/blob/1784a10346d9dedcb2e18e076f3d482e39be93a1/bugbug/bug_features.py#L83

**Comment by marco-c** [comment]
Right now it's only looking for `whiteboard` or `[ux]`. It should instead get all possible whiteboard words.

**Comment by ayush1999** [comment]
@marco-c It's currently looking for `memshrink` or `[ux]` right?. (You mentioned `whiteboard`) above.

**Comment by marco-c** [comment]
Yes, see the comment above :smile:

**Comment by ayush1999** [comment]
I found a list of commonly used whiteboard words here: https://wiki.mozilla.org/ReleaseEngineering/Bugzilla/Whiteboard . Should I add these?

**Comment by marco-c** [comment]
No, unfortunately they are bound to change and there's no complete reference.
We should just use all whiteboard items we find in the whiteboard. The model will automatically discard the ones which are not meaningful.

**Comment by ayush1999** [comment]
Oh, I see. Please correct me if I'm wrong: I'll have to implement an regex that finds all text between `[` and `]` in the whiteboard, extracts only the tags from each (`[memshrink:XXX]` becomes only `memshrink`), and appends it to the returned list. Right?

**Comment by marco-c** [comment]
Correct!
