### ISSUE TITLE
Add `author experience` as feature

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#105]

**Comment by ayush1999** [comment]
@marco-c From where should this data be extracted? (Any specific field that should be used?)

**Comment by marco-c** [comment]
The data should be extracted from commits, using a template when calling hg.log.

**Comment by marco-c** [comment]
I think the first step would be to try to add the `template` parameter to the `hg.log` call and adjust the rest of the code.

E.g. template='{author}|{node}\n'
will give you something like:
```
Masayuki Nakano <masayuki@d-toybox.com>|c650507f7feee04516c2c869a2f0662c2a6dc0c0
Kartikaya Gupta <kgupta@mozilla.com>|47b5e6d95d9eaa421b6aaaccd8f263f32bbc8121
Brian Grinstead <bgrinstead@mozilla.com>|5ea2f61028a5e989f1dbf46e9fe961a7b1c419ca
```

**Comment by ayush1999** [comment]
I just dug a bit into the hglib code, looks like using `hg.log()` returns commit in `'{rev}\\0{node}\\0{tags}\\0{branch}\\0{author}\\0{desc}\\0{date}\\0'` format. Can't we use this directly? `commit.author` and `commit.node` attributes can be used to extract the corresponding values.

**Comment by marco-c** [comment]
We can use it for the author, we can't use it for the reviewer.

**Comment by ayush1999** [comment]
@marco-c I'm trying to do something like:
```
>>> import hglib
>>> hg = hglib.open("mozilla-central")
```

`hg` in this case doesn't have a kwarg called template, according to the docs. What am I doing wrong? (Is there some problem in installing the extension?)

**Comment by marco-c** [comment]
Ahhh, that's a pity. I thought there was a `template` parameter for log.

OK, so it looks like you'll have to write a custom log function, you can take inspiration from https://www.mercurial-scm.org/repo/python-hglib/file/tip/hglib/client.py#l1095.

**Comment by marco-c** [comment]
(you don't need to support all the options, just template)

**Comment by ayush1999** [comment]
The default template is defined in `templates.changeset`, equal to `'{rev}\\0{node}\\0{tags}\\0{branch}\\0{author}\\0{desc}\\0{date}\\0'`, so if I try to change that, I get an empty list in the result, so maybe the template `{author}|{node}\n` isn't right?
```
>>> import hglib
>>> from hglib import templates
>>> templates.changeset = '{author}|{node}\n'
>>> hg = hglib.open('mozilla-central')
>>> hg.log(limit=5000)
[ ]
```

**Comment by marco-c** [comment]
> maybe the template {author}|{node}\n isn't right?

You can test it from the command line, `hg log --template '{author}|{node}\n'`.

**Comment by ayush1999** [comment]
Hm, that's weird. I'm not sure why it behaves differently in both cases.

**Comment by calixteman** [comment]
For example:
```python
import hglib
from hglib.util import cmdbuilder

c = hglib.open('/home/calixte/dev/mozilla/mozilla-central.hg')
args = cmdbuilder(b'log', template='{author}\\0{node}\\0', r="tip:-2")
x = c.rawcommand(args)
c.close()
print(x)
```

is working for me.

**Comment by ayush1999** [comment]
@marco-c Now that the first step is complete (template for log function), how should the experience of the author be determined? (Probably depends on the number of commits made?)

**Comment by marco-c** [comment]
I've split the issue in two, this one is about the author, #152 is about the reviewer.

**Comment by ayush1999** [comment]
> Yes, it should be the number of commits by that author in total and in the previous three months.

Sure, so we can have a global variable such as `num_commits = {}` that maps author names to the number of commits made by them, and then writes it out to the json file?

**Comment by marco-c** [comment]
We'll add the information directly in commits.json (each commit will have `author_experience` and `author_experience_past_3_months`).

**Comment by marco-c** [comment]
Total author experience has been added with #154.

Now we need to add author experience in previos 3 months.

**Comment by ayush1999** [comment]
@marco-c We need the number of commits in previous 3 months from the day the commit was made or from `datetime.now()`?

**Comment by marco-c** [comment]
From the day the commit was made

**Comment by marco-c** [comment]
Total experience added with a002e0ce53080699a78cada08a95fd2355953c42, previous 90 days experience added with 936509ba3aa695b5e43fa6d086a2c58a295f85ef.
