### ISSUE TITLE
Support multiclass classifiers in bug_classifier script

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1070]
The bug_classifier script at scripts/bug_classifier.py currently assumes the model is a binary model. We need to make it work for multiclass models too (e.g. defectenhancementtask).

In particular, https://github.com/mozilla/bugbug/blob/65bf1b4604ca55a67490d27adc99c6441bad38c8/scripts/bug_classifier.py#L75-L78 needs to be changed.

To test your changes, simply run `python3 -m scripts.bug_classifier defectenhancementtask`

**Comment by ashutosh-b-b** [comment]
Hi , I am new here. I would like to work on this. Can anyone guide me through?

**Comment by marco-c** [comment]
I've expanded the description in the first comment.

**Comment by ashutosh-b-b** [comment]
Hi @marco-c , When I was installing the requirements in requirements.txt I get an error for rs_parsepatch. I am currently on Mac OS.X . Does parsepatch support OSX?

**Comment by marco-c** [comment]
No: https://github.com/mozilla/pyo3-parsepatch/issues/4.
You don't need it though to fix this issue.

**Comment by gilltan97** [comment]
Hi @marco-c, I am interested in this bug. Can you guide me to get started on the fix?

**Comment by trulyness** [comment]
Can I work on this?

**Comment by marco-c** [comment]
No need to ask, you can work on any issue that has no open PR linked to it!
The description of what needs to be done is in the first comment. The first step is to set-up the repository as described in README, then try to run `python3 -m scripts.bug_classifier defectenhancementtask`. It will output "Positive" or "Negative" according to the prediction made by the model, it should instead output the predicted class name.

**Comment by HackyRoot** [comment]
Hello @marco-c , 
I followed the instruction to setup the project and after running `python3 -m scripts.bug_classifier defectenhancementtask` command, it not displaying any output. Any suggestion?

![IMG_20191109_173833](https://user-images.githubusercontent.com/18494493/68528381-ef2c2400-0317-11ea-94cc-783e84bc6efb.png)

**Comment by marco-c** [comment]
It shouldn't happen, but please file a separate issue about this problem.
