### ISSUE TITLE
Add a few more features to the spambug model

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1082]
There are a few features that might make sense, we should try to add them one by one and see if they improve results:
- [ ] keywords;
- [ ] number_of_bug_dependencies;
- [ ] blocked_bugs_number;
- [ ] product;
- [ ] component;
- [x] is_mozillian;
- ...

**Comment by marco-c** [comment]
> is_mozillian

Actually for this one it might be better to just overwrite the decision (#1084).

**Comment by marco-c** [comment]
@ayush-1506 do you want to look into this too?

**Comment by ayush-1506** [comment]
Ok!

**Comment by ayush-1506** [comment]
Sure!

**Comment by ayush-1506** [comment]
Results:

Before any additions:
```
Accuracy: f0.995783670252694 (+/- 0.0007449414872651147)
Precision: f0.9833024639219158 (+/- 0.004560331424210395)
Recall: f0.9944979418565302 (+/- 0.0017856201890962399)
```

After adding `keywords()`:
```

**Comment by marco-c** [comment]
Thanks for the investigation, so it looks like the increase is minimal for all. I guess the metrics are already too high :)

I'd add keywords, product and component anyway. They would probably be useful if we had more examples of spam bugs.
