### ISSUE TITLE
No output from bug_classifier

### ISSUE THREAD

**Issue by HackyRoot** [mozilla/bugbug#1093]
I followed the instruction to setup the project and after running `python3 -m scripts.bug_classifier defectenhancementtask` command, it not displaying any output. Any suggestion?

![IMG_20191109_173833](https://user-images.githubusercontent.com/18494493/68528633-66af8280-031b-11ea-980d-a30156f4b937.png)

**Comment by marco-c** [comment]
Add some logging to the scripts you're trying to run and see where exactly it stops.

**Comment by arjun-krishna** [comment]
You might have to run bug_retriever script to populate data/bugs.json ?

**Comment by HackyRoot** [comment]
@arjun-krishna sorry I didn't see any steps regarding the same in setup instruction or issue description (I was working on another issue when I got this error). Can you please help me with this?

**Comment by marco-c** [comment]
@HackyRoot you can download the bugs DB simply by running this code:
```Python
from bugbug import db, bugzilla
db.download(bugzilla.BUGS_DB)
```
