### ISSUE TITLE
Add number of backouts as a feature

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#110]

**Comment by marco-c** [comment]
No, all changesets have a parent, even those which were never backed out.

For example, take a look at https://hg.mozilla.org/mozilla-central/rev/758c71218a1f. It has one parent, and it has not been backed out.

https://hg.mozilla.org/mozilla-central/rev/7065c7171760 has one parent too, and it has been backed out by https://hg.mozilla.org/mozilla-central/rev/2b73321e629d.

There are a few possible ways to implement this:
1) Figuring out if we can get the backout information directly using hg.log and a template (https://github.com/mozilla/version-control-tools/blob/d5db0980ab004b3aada29afdcf798a8a95520240/hgext/mozext/__init__.py#L137, https://github.com/mozilla/version-control-tools/blob/d5db0980ab004b3aada29afdcf798a8a95520240/hgtemplates/json/map);
2) Generate a map of backouts by walking the list of commits and parsing the commit message (e.g. https://hg.mozilla.org/mozilla-central/rev/2b73321e629d says "Backed out changeset 7065c7171760 ...", so you can put 7065c7171760 -> 2b73321e629d in the map); then use the map when generating the commit information.

1 would be best, but I'm not sure yet if it's feasible. CC @cgsheeh.

**Comment by marco-c** [comment]
We will be able to do 1 when https://bugzilla.mozilla.org/show_bug.cgi?id=1523961 is fixed.

**Comment by rhcu** [comment]
Thanks! Will have a look on it later then. :)

**Comment by marco-c** [comment]
I've added you to the CC list of the bug on Bugzilla, so you get notified when it is fixed.

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1523961 has been fixed, so this is now feasible.
