### ISSUE TITLE
Split commit changes-related features into real code changes and test code changes

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#111]
Right now we have single `added`, `deleted` and `types` values: https://github.com/mozilla/bugbug/blob/1784a10346d9dedcb2e18e076f3d482e39be93a1/bugbug/repository.py#L48.

We should have a `added` and `test_added`, `deleted` and `test_deleted`, and so on.

**Comment by LakshyAAAgrawal** [comment]
Hey,
Could someone please provide a little more info regarding this?

**Comment by marco-c** [comment]
At the moment, the `lines_added` feature is considering both real changes and test-only changes, we have to split the feature in two, `lines_added` and `test_lines_added`.
`lines_added` will be the number of lines added by the commit in Firefox code.
`test_lines_added` will be the number of lines added by the commit in testing code.

**Comment by LakshyAAAgrawal** [comment]
Hey,
Really sorry to have got it wrong.
Should I instead check for the filename in the variable _path_ if it contains 'test' or not using regex, and if it does, then consider them to be test code changes?
