### ISSUE TITLE
Make utils.download_check_etag automatically detect the file name from the URL

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1112]
And then we should update the usages of the function, e.g. https://github.com/mozilla/bugbug/blob/aaad3298d88153e06841fb13c2ffb4ba1eb64a72/scripts/test_scheduling_history_retriever.py#L99
would become just `download_check_etag(PUSH_DATA_URL)`.

**Comment by vishal3410** [comment]
@marco-c can i take up this issue ?

**Comment by marco-c** [comment]
Sure, no need to ask. Did you read "Guidance for first contributors" or CONTRIBUTING.md?

**Comment by vishal3410** [comment]
Yes :)

**Comment by abhaykatheria** [comment]
@marco-c  path = url.split('/')[-1] will this work ..?

**Comment by marco-c** [comment]
> Yes :)

So, if you did read them, it is clearly specified not to ask if you can be assigned to issues. Why did you ask anyway? (I'm not angry, I just need to know what I can do to make it more clear for new contributors).
