### ISSUE TITLE
Add number of previous commits touching the same files as a feature

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#112]

**Comment by poojan124** [comment]
I want to work on this issue. Can you please give me some references.

**Comment by marco-c** [comment]
This is very similar to #113, removing `good first issue` as it's not so easy.

**Comment by marco-c** [comment]
You're still welcome to work on this if you want, but it would require quite a bit of investigation and work.

**Comment by marco-c** [comment]
With a962e0694bef08090bd6c4810e5c4c770154f99c, this is now easier to do (see https://github.com/mozilla/bugbug/issues/113#issuecomment-470744304).

**Comment by poojan124** [comment]
* I still not quite sure what number we are putting here.  Should we put count for each file or as group of files?
* If one commit touching multiple files what would be scenario? How to add count for each file (sum all those up)?

**Comment by marco-c** [comment]
> 
> I still not quite sure what number we are putting here. Should we put count for each file or as group of files?

We can try for each file and for each directory.

> If one commit touching multiple files what would be scenario? How to add count for each file (sum all those up)?

Each file has a different count. If a commit is touching multiple files, you increase the count by 1 for each file.

**Comment by marco-c** [comment]
@sbeesm do you want to take this? It should be pretty similar to the one about components.

**Comment by sbeesm** [comment]
Sure, I'd like to work on this.

Do we also need to add files for previous 90 days, just like we did for components?

**Comment by marco-c** [comment]
> Do we also need to add files for previous 90 days, just like we did for components?

Yes!
