### ISSUE TITLE
Add components touched and number of components touched as features

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#115]

**Comment by sbeesm** [comment]
By modules, you mean the sub-directories touched, right? Like files in how many directories got changed?

**Comment by marco-c** [comment]
I meant modules, which are described at XXX.
But actually, let's use components instead, as they're easier to retrieve, see https://mozilla-version-control-tools.readthedocs.io/en/latest/hgmo/mozbuildinfo.html.

Unfortunately, they are not as easy to retrieve as I was expecting, so I'll remove the `good first issue` label from this.

**Comment by marco-c** [comment]
The info can be retrieved by using mach, e.g. `./mach file-info bugzilla-component toolkit/components/telemetry/`.

**Comment by marco-c** [comment]
Yes, we can use the `subprocess` library to execute mach.
The `file-info` command also has a `--format` option to return a json instead of plain text, which might be better.
Moreover, you can pass a list of files, you don't need to pass one at a time.

**Comment by marco-c** [comment]
Actually, even better, by running `./mach file-info bugzilla-component **/* --format json` you should get info on all files in the repository. So you'd just need to run mach once.

**Comment by marco-c** [comment]
N.B.: In theory, we should run mach after checking out to the required commit, as files can be removed/renamed, or components can change, but as an approximation we can start by running `mach` in the repository at the "current state" (which is the latest commit).

**Comment by sbeesm** [comment]
But we need the components touched by a specific commit in our data right?

Wouldn't `./mach file-info bugzilla-component **/* --format json` give the info for all files in the repository irrespective of the fact that they were changed by a commit or not?

**Comment by marco-c** [comment]
You can run that script, put the result in a map, then for each commit you get the list of modified files and you go into that map to get the components.

**Comment by marco-c** [comment]
(BTW `**/*` only gives first-level files, we'll need another way to get all files)

**Comment by sbeesm** [comment]
The script doesn't seem to work, it returns an empty dict:
```
(py27) F:\COMPILED\Mercurial\mozilla-central>python ./mach file-info bugzilla-component **/* --format json
{}
```

**Comment by marco-c** [comment]
Try running "./mach" without python. If it doesn't work still, try running "./mach bootstrap" first.
