### ISSUE TITLE
 The Firefox Bookmarks Menu slide up problem when enter full screen mode, sometimes freezes and cant save bookmark

### ISSUE THREAD

**Issue by matstiv** [mozilla/bugbug#1157]
They sent me here, I have a problem. Please help, how did nobody notice this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1601706

**Comment by marco-c** [comment]
Bugzilla is the right place to report the bug. This project is just powering the bot which assigns the right component to filed bugs on Bugzilla.
