### ISSUE TITLE
Add number of touched files as a feature

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#116]

**Comment by sbeesm** [comment]
Could the number of files touched be the length of `types` attribute list in commits data?

`"types": ["JavaScript", ".ini", ".build"]`

**Comment by marco-c** [comment]
No, the types are only the types. If you have ten JavaScript files the length of types will be 1, but we want 10.

**Comment by sbeesm** [comment]
As of now, we are just downloading commits data and not parsing it like in `repository.py`, right?

So do we somehow need to parse the bug id related commit data from bugzilla? Something like extracting info from attachments diff?

**Comment by marco-c** [comment]
We can simply change `repository.py` to add the required info.

**Comment by ayush1999** [comment]
@marco-c This means that the bug data will now contain a new field called `desc` right? (Obtained from commits.json for each bug element)

**Comment by ayush1999** [comment]
Will the `number of touched files` feature be extracted from the comments in the bug `bug['comments']`? Or would this data need to be extracted from commits.json file?

**Comment by marco-c** [comment]
We can't extract it from the comments, as they don't contain this information.

It would need to be extracted in `repository.py`, and stored in `commits.json`.

**Comment by ayush1999** [comment]
Oh, I see. So the number of touched files will be sum of added and deleted, if I'm not wrong?
