### ISSUE TITLE
Training of the SpamBug model failed on Taskcluster

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1200]
See https://community-tc.services.mozilla.com/tasks/WqBnMthmQJ22x-RmDZo-pQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FWqBnMthmQJ22x-RmDZo-pQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log.

```
X: (100920, 351731), y: (100920,)
Cross Validation scores:
Accuracy: f0.9970713836755015 (+/- 0.0010172701157966423)
Precision: f0.9936170412244343 (+/- 0.002257050740925755)
Recall: f0.9953493975862067 (+/- 0.001831166668421503)
X_train: (48166, 351731), y_train: (48166,)
X_test: (10092, 351731), y_test: (10092,)
Model trained
Setting feature_perturbation = "tree_path_dependent" because no background data was given.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

Probably we just need to disable feature importance.

**Comment by ayush-1506** [comment]
@marco-c Does this mean it is running out of memory? Training the model locally works just fine for me.

**Comment by marco-c** [comment]
Yep!
Do you have up-to-date dependencies (pip3 install -r requirements.txt)? Maybe a new version of a dependency is using more memory than before?
How much RAM do you have? We can also just increase the RAM available for the job.

**Comment by ayush-1506** [comment]
Ah, I just realized it crashes for me too. I wasn't patient enough to wait for the entire training period, hence after seeing the initial metrics I figured the rest might also be working fine for me.

I'm on 16 gigs of RAM and this is failing for me. @marco-c I think the only option here is increasing the ram be have for this job?

**Comment by marco-c** [comment]
@ayush-1506 or we can disable feature importance, that should fix it too.
