### ISSUE TITLE
Tracking model is missing bugs which were filed with the tracking flags right away

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1212]
As we are only checking the history, we miss bugs which were filed right from the start with the tracking flags set (they are probably fewer, but still...).

https://github.com/mozilla/bugbug/blob/99cd7d4088859f8af4eb5d9ccecf956517fde2c8/bugbug/models/tracking.py#L93-L117

The same might apply to other models, we need to check.

**Comment by kushagra414** [comment]
@marco-c `True` and `False` are flags that were filed from the start?

**Comment by marco-c** [comment]
Not sure what you mean.

**Comment by kushagra414** [comment]
Can you give an example of the kind of bug you are talking about?

**Comment by marco-c** [comment]
Finding the examples is part of fixing this. You'll need to find bugs where a cf_tracking_firefox* flag was there from the beginning, rather than just looking at the history.

**Comment by kushagra414** [comment]
Could you verify.If this example is correct?
https://gist.github.com/kushagra414/3080414168d23e61a07bca69d28cbe8c#file-track_bug-json-L12

**Comment by kushagra414** [comment]
Please Review.

**Comment by marco-c** [comment]
> Could you verify.If this example is correct?
> https://gist.github.com/kushagra414/3080414168d23e61a07bca69d28cbe8c#file-track_bug-json-L12

It isn't correct, this is an example of what we are already handling (bug filed with no tracking flags, tracking flags added later).

**Comment by kushagra414** [comment]
In Previous PR,I did not run pre- commit hence the lint task failed.
That's why I created this new PR.
Please review.

**Comment by marco-c** [comment]
There is no need to create a new PR for every change you make, you can simply update an already existing PR.

**Comment by kushagra414** [comment]
I updated the existing PR. Please Review
