### ISSUE TITLE
Check if there are other models relying on the history and not the initial state

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1218]
We could increase the number of labels for some models.

Similar to #1212.

**Comment by kushagra414** [comment]
I think these models need to be changed.
https://github.com/mozilla/bugbug/blob/e9a35eb01f6977f46e31f4f8d072b65c977a5fbf/bugbug/models/devdocneeded.py#L84-L112
https://github.com/mozilla/bugbug/blob/e9a35eb01f6977f46e31f4f8d072b65c977a5fbf/bugbug/models/regression.py#L16-L36
https://github.com/mozilla/bugbug/blob/e9a35eb01f6977f46e31f4f8d072b65c977a5fbf/bugbug/models/qaneeded.py#L76-L92

**Comment by kushagra414** [comment]
@marco-c could you please confirm?

**Comment by kushagra414** [comment]
Please Review #1247

**Comment by marco-c** [comment]
About qaneeded and devdocneeded, yes.
About regression, no.

Did you check the other models too?

**Comment by kushagra414** [comment]
> About qaneeded and devdocneeded, yes.
> About regression, no.
> 
> Did you check the other models too?

Yes I checked all other models.
Regression does not need to be changed, I realised it later.
