### ISSUE TITLE
Try increasing the test selection history retrieved for training

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1222]
https://github.com/mozilla/bugbug/blob/abf47d3b1c69e782450a57918d5950b2bec22cb4/scripts/test_scheduling_history_retriever.py#L37

**Comment by kushagra414** [comment]
How many months should be considered for training?

**Comment by marco-c** [comment]
We need to test, if I had known the exact number I would have used it already :P

**Comment by marco-c** [comment]
The first increase for the label-level model was done in 0af1db468b718dc22cbc457a52de2927b1c8a90f.
For the group-level model in a2db51106e6e56aab59b905c43a952009fcc8dd6 and 6088fcc7542324093a25fe9433a944a7ffb01ff9.

I'm planning to increase both to 7 months for now.

**Comment by marco-c** [comment]
I've increased the group-level history to 6 months in 5fd23da48c046d4ce26fd44fae219b662744727c.

Soon I'll increase it to 7 and then close this issue.
