### ISSUE TITLE
Add SpamBug model to relman-auto-nag

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1223]
First of all, we need to fix #1200, otherwise the model fails during training.

Then, in relman-auto-nag, we need something like https://github.com/mozilla/relman-auto-nag/blob/master/auto_nag/scripts/stepstoreproduce.py and https://github.com/mozilla/relman-auto-nag/blob/57fae814cb1d5c56cbb4e808784b3a21031aff28/auto_nag/scripts/configs/tools.json#L580-L603.
Assuming you will name the script "spam.py", you can run it this way: python -m auto_nag.scripts.spam --dryrun. You might need some minimal configuration for it to run, let me know (here or on IRC) if you run into issues and I'll help you.

**Comment by ayush-1506** [comment]
@marco-c I'm trying to run `python -m auto_nag.scripts.stepstoreproduce --dryrun` and I get an error: `FileNotFoundError: [Errno 2] No such file or directory: './auto_nag/scripts/configs/config.json'`

**Comment by marco-c** [comment]
Create that file and put something like this in it:
```
{
    "ldap_username": "",
    "ldap_password": "",
    "bz_api_key": "YOUR_BUGZILLA_TOKEN",
    "phab_api_key": "",
    "repo_dir": ""
}
```

I don't remember if you already have a Bugzilla token. If you don't, you can get one by registering on https://bugzilla.mozilla.org/ and going to https://bugzilla.mozilla.org/userprefs.cgi?tab=apikey.

**Comment by ayush-1506** [comment]
This can be closed now.

**Comment by marco-c** [comment]
It was fixed by https://github.com/mozilla/relman-auto-nag/pull/881.
