### ISSUE TITLE
Commit classifier should accept push rev or id in addition to phabricator diff

### ISSUE THREAD

**Issue by ahal** [mozilla/bugbug#1236]
The current entry point requires a phabricator ID:
https://github.com/mozilla/bugbug/blob/master/scripts/commit_classifier.py#L545

But when running from the taskgraph, we'll be passing in a revision instead. We should accept both.

**Comment by marco-c** [comment]
This was fixed by https://github.com/mozilla/bugbug/commit/936f2ccb3c6440875009c7f8f31825c7a772fe1d.
