### ISSUE TITLE
Set label as 0 in the QANeeded model when one of the qa flags are removed

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1249]

**Comment by dotslash21** [comment]
Hey @marco-c, after exploring `bugbug/models/qaneeded.py` I came across this method `get_labels()` which I think needs the required modification. So, If I add a check for one of the QA flags in the `removed` field of a change and set the label accordingly then that should do it.

Can you please confirm that am I on the right track, and also If I'm missing something? That would really help me, thanks.

**Comment by joshz123** [comment]
Is this issue still open? I am new to open source but if it is available would like to work on it

**Comment by marco-c** [comment]
Sorry @dotslash21 and @joshz123, but there already is a PR to fix this, so it is assigned for now (unless @abhaykatheria abandons their PR).
