### ISSUE TITLE
Use exponential backoff when retrying with tenacity

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1257]
After switching to tenacity (#1234), we should start using exponential backoff instead of normal retries.

**Comment by aditya-hari** [comment]
Where will this change have to be made?

**Comment by menarulalam** [comment]
Can I work on this? I would like to contribute to the open source community.

**Comment by marco-c** [comment]
This requires #1234 to be done first.

**Comment by Luis-gd** [comment]
I am new in open source contributions and I want to work on this issue, where I can start?

**Comment by marco-c** [comment]
@Luis-gd the first step is reading the documentation of the tenacity library to figure out how to use exponential backoff, then find all usages of tenacity in bugbug and apply the necessary changes.

**Comment by Luis-gd** [comment]
All right, I am working on this.

**Comment by marco-c** [comment]
Note that there are already two PRs open to fix this, the first opened PR has the priority.
