### ISSUE TITLE
Clean the test data for cleanup functions

### ISSUE THREAD

**Issue by ayush1999** [mozilla/bugbug#126]
The test data for cleanup functions (https://github.com/mozilla/bugbug/tree/master/tests/fixtures/bug_features) has a lot of redundant fields. Essentially, we'd need only the field that is being tested. For example, it'd be easier if each test element in `has_str.json` had only the `has_str` key. (And so on for other test files).

**Comment by pramud** [comment]
@marco-c, @ayush1999  I would like to work on this issue could you help me with initial steps

**Comment by ayush1999** [comment]
Hey @pramud The test data in the `test/fixtures/bug_features` directory is really messy. We'd like to remove all redundant keys from each test element in all test files and keep on the element being tested. So each line ion `has_str.json` will be a dict containing only `has_str` key, for example.

**Comment by HSR05** [comment]
i would like to work on this issue.
Can you guide me @ayush1999

**Comment by ayush1999** [comment]
The process is pretty much summed up in my earlier comment (https://github.com/mozilla/bugbug/issues/126#issuecomment-459639958). Please tell me if you need help understanding any aspect of it.

**Comment by HSR05** [comment]
@ayush1999  Can you please explain a little more about what "each line in has_str.json will be a dict containing has_str only.
I get that we are removing the redundant fields in the dict but it's my first time with this data so can you help me walkthrough this data. 
I'd appreciate  the help.
Thankyou.

**Comment by ayush1999** [comment]
@HSR05 Each line is the test file is a dict, suppose `{'a': val1, 'b':val2, 'c':val3}` and so on. If the test file is for the `a` field, we can remove the other fields (`b` and `c`), so that the line becomes `{'a':val1}` only, since the other fields aren't of any use to us.

**Comment by HSR05** [comment]
Got it. I'll work on it. Thanks for the guidance 👍 @ayush1999

**Comment by HSR05** [comment]
@ayush1999 

> each test element in `has_str.json` had only the `has_str` key.

Can you please clarify once again because the has_str.json file does not have any has_str key. 
Same goes for the other files like has_urls.json. I cannot find any key has_urls.
If there is anything wrong with my udnerstanding can you please clarify the issue once again?
Thankyou.

**Comment by ayush1999** [comment]
`has_str` is just a bug extractor. It doesn't search for the `has_str` key. For the key, see : https://github.com/mozilla/bugbug/blob/master/bugbug/bug_features.py#L27 (and similar for other bug extractors)

**Comment by parthpm** [comment]
Can I work on this issue?

**Comment by HSR05** [comment]
@parthpm I am already working on it, if i find any difficulty i'll update this thread and you can help along. Cheers 👍

**Comment by marco-c** [comment]
Please note, as explained in the contributing section of the readme (https://github.com/mozilla/bugbug#contributing), that any issue is unassigned until there is a PR open to fix it. You don't need to ask to work on an issue, you can work on any issue that is unassigned.

@HSR05 is working on this, but there is still no PR, so the issue is to be considered unassigned. However, since there are many issues available, you can probably find (but you don't have to, given the rules above) some other issue to work on so that you don't both work on the same thing.
