### ISSUE TITLE
Return 404 when a model which doesn't exist is requested

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1265]
The HTTP service APIs (http_service/bugbug_http/app.py) should return 404 when the requested model is not supported (that is, not in the list at https://github.com/mozilla/bugbug/blob/e2a54a04ab69efd91c74a67805271009afb714a5/http_service/bugbug_http/models.py#L23).

**Comment by Sanjuhub** [comment]
Hey, I want to work on this issue. Can you please elaborate this issue please and where do I need to do changes?

**Comment by marco-c** [comment]
I've updated the first comment to explain the issue in more detail.

**Comment by kaushiksk** [comment]
@marco-c I've raised a PR for this. Kindly review.
