### ISSUE TITLE
Make the commit classifier script apply the Phabricator patch as its first step

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1268]
Most failures happen when applying patches, so that should be the first step (right after cloning). This way, we don't waste time doing other things if the patch fails to apply.

**Comment by kaushiksk** [comment]
@marco-c Kindly review my PR

**Comment by marco-c** [comment]
Reopening as #1388 is being backed-out (#1419).

**Comment by imskr** [comment]
I would like to fix this issue @marco-c Assign me!

**Comment by marco-c** [comment]
Hello @imskr, feel free to work on it, but please read the contributing rules: issues are not assigned until there is a PR linked to it.

**Comment by bhushan-borole** [comment]
Hello @marco-c .
I have sent a PR for this issue.
I am facing a problem for the TaskGroup checks, "bugbug link" task has failed while rest of them has passed.
Can you tell me how to resolve this problem?

Logs : https://community-tc.services.mozilla.com/tasks/MsFDby5-QRSxkFM04ed4Tg/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FMsFDby5-QRSxkFM04ed4Tg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by marco-c** [comment]
Let's discuss in the PR itself about issues with it.

**Comment by Emeka-Onwuepe** [comment]
Is this linked pull request made on Oct 2022 still active or can I give it a try?
