### ISSUE TITLE
Add a setup step to the http service to setup the environment for classifying commits

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1299]
This is partly similar to the what we are doing in the code-review backend.
We need to do:
- Clone mozilla-central;
- Download the test scheduling DB (https://github.com/mozilla/bugbug/blob/cb51deac6235477e7f2dbc13352a2627d129451c/scripts/commit_classifier.py#L179-L183);
- Update the commits DB (https://github.com/mozilla/bugbug/blob/cb51deac6235477e7f2dbc13352a2627d129451c/scripts/commit_classifier.py#L219-L229).

We should update the commits DB periodically, but I think doing it daily (whenever Heroku restarts) is a good enough approximation.

Blocks #632.

**Comment by marco-c** [comment]
Note: this should happen in the worker dynos.

**Comment by La0** [comment]
I'm starting to work on that issue.
