### ISSUE TITLE
Add the scaffolding needed to add an API call to select tests

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1300]
This issue is just about adding an API call (with a hardcoded result) to the http service, preparing the ground for the actual API.

It should be similar to the bug classification API call (`model_prediction`), but its input will be a repository and a commit hash.

As part of this issue, we should:
- add the API definition (in http_service/app.py);
- the implementation of queuing the classification from the web dyno to the worker dyno using rq (again, in http_service/app.py, like we do for bugs).
- a `select_tests` function in http_service/models.py which for now returns a hardcoded result.

Note: the implementation should be simpler than the one for bugs, as we don't need (actually, we don't want to!) cache results.

Blocks #632.

**Comment by ahal** [comment]
@La0 would it help if I took a look at this issue while you worked on #1299 ? Or do you think you would have this finished in a couple days anyway?

**Comment by La0** [comment]
I'm on PTO tommorow, will start looking into these issues on Wednesday.
I *should* have something by the end of the week, if that's too slow, feel free to re-assign the issues.

**Comment by ahal** [comment]
Ok I don't have permission to re-assign, but I'm going to take a look at getting a head start here. If I'm not done by the time you're ready to work on it.. I can upload what I have and you can take over again if you like.

**Comment by La0** [comment]
@ahal I've assigned the issue to you, as I see some commits from your fork linked to this issue.
