### ISSUE TITLE
Download test scheduling models in the HTTP service

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1330]
We should:
- Add the test scheduling models to https://github.com/mozilla/bugbug/blob/cfd82a8ad3635ab0214818c461b5220dccf76aa8/http_service/bugbug_http/models.py#L23-L29;
- Make sure the Docker build task https://github.com/mozilla/bugbug/blob/cfd82a8ad3635ab0214818c461b5220dccf76aa8/infra/data-pipeline.yml#L1124 depends on the tasks to train the test selection models;
- Remove the dependency on `test-label-scheduling-history-generator` for the HTTP service Heroku push (https://github.com/mozilla/bugbug/pull/1320#discussion_r385636594).

Blocks #632.

**Comment by imskr** [comment]
Can i work on this issue ? @marco-c

**Comment by marco-c** [comment]
@imskr better to start with an issue with the good-first-bug label: https://github.com/mozilla/bugbug/issues?q=is%3Aissue+is%3Aopen+label%3Agood-first-bug.
You can still work on this if you want of course, but it might not be as easy as those.
