### ISSUE TITLE
Print progress bar while downloading bugs

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#134]
Similar to what we're doing for commits data: 28b83c12c29185c52afb58d94a533a9448969a8a.

**Comment by EternalLearner42** [comment]
Sounds interesting. I am a bit of a newbie, if you could give me some advice on how to do this, I'd be happy to try 👍

**Comment by marco-c** [comment]
You have an example in the first comment :)
You can just do something similar in the function to download bugs in bugbug/bugzilla.py.

**Comment by akashgosai** [comment]
@marco-c are these changes enough?

**Comment by marco-c** [comment]
@akashgosai sorry, the issue is reserved for new contributors (people who haven't done any commit to the project yet).

**Comment by akashgosai** [comment]
Okay.
