### ISSUE TITLE
'dict' object has no attribute 'data' while accessing error message from UnauthorizedError().dump({})

### ISSUE THREAD

**Issue by kaushiksk** [mozilla/bugbug#1357]
The following line throws a 'dict' object has no attribute 'data'
https://github.com/mozilla/bugbug/blob/1fb819b1317f15ac883c337d4313c955db9b4eeb/http_service/bugbug_http/app.py#L261

This is because the UnauthorizedError schema defines a field named  "message" and not "data"
https://github.com/mozilla/bugbug/blob/1fb819b1317f15ac883c337d4313c955db9b4eeb/http_service/bugbug_http/app.py#L84-L85

Found this while working on #1343

**Comment by marco-c** [comment]
Thanks for the report! @ahal is fixing this in #1319.

**Comment by kaushiksk** [comment]
Awesome! This means that  I can work on #1343 only once this fix is issued right?
Please let me know in this thread once it's fixed. I'll  raise the PR for the test case accordingly.

**Comment by marco-c** [comment]
Feel free to submit a PR to fix just the `.data` issue, and @ahal will rebase his PR on top of yours.

**Comment by kaushiksk** [comment]
@marco-c  I've raised a PR for this. Kindly review.
