### ISSUE TITLE
Stop parsing bug ID manually and use a hg.log template

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#137]
We can use the {bugs} template (https://github.com/mozilla/version-control-tools/blob/d5db0980ab004b3aada29afdcf798a8a95520240/hgext/mozext/__init__.py#L137) at https://github.com/mozilla/bugbug/blob/5da534ecc95b375de2e5b4e8262253115725bce1/bugbug/repository.py#L86 and stop parsing the bug ID manually at https://github.com/mozilla/bugbug/blob/5da534ecc95b375de2e5b4e8262253115725bce1/bugbug/repository.py#L35.

**Comment by akashgosai** [comment]
I am a newbie here, can you suggest a bit about how are we supposed to parse manually?

**Comment by marco-c** [comment]
We *are* parsing manually, and we should stop doing it. The first step would be to clone mozilla-central and then read docs about hg log (the template parameter) and try to use it from the cmd line.

**Comment by akashgosai** [comment]
do I have to clone mozilla-gecko-dev ?

**Comment by marco-c** [comment]
You'll have to clone mozilla-central, which is a Mercurial repository, see https://github.com/mozilla/bugbug#running-the-repository-mining-script.

**Comment by ayir** [comment]
@marco-c I managed to get the bug ids from the cmd line using "hg log --template '{bug}\n'" command but I am stuck as how to put the template argument in the hglog python command?

**Comment by marco-c** [comment]
@ayir @ayush1999 is working on that in #148, once that is landed you'll be able to use the function he wrote.

**Comment by ayir** [comment]
Ohh alright thanks !
