### ISSUE TITLE
Figure out why memory usage while workers are idle is high

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1421]
```
2020-03-20T18:38:28.037743+00:00 heroku[worker.1]: Process running mem=1514M(110.4%)
2020-03-20T18:38:28.037860+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2020-03-20T18:38:31.544075+00:00 heroku[worker.2]: Process running mem=1240M(103.8%)
2020-03-20T18:38:31.544172+00:00 heroku[worker.2]: Error R14 (Memory quota exceeded)
```

**Comment by La0** [comment]
I'll dive into this on Monday

**Comment by La0** [comment]
The simple fact that [there is a dedicated official article](https://devcenter.heroku.com/articles/node-memory-use) on debugging memory leaks on Heroku is intriguing. The article is aimed at NodeJs developers (and specific tooling) so not really useful here.

**Comment by La0** [comment]
After team meeting:

1. try to get an [ssh connection on the host](https://devcenter.heroku.com/articles/exec)
2. check number of threads
3. use [pympler](https://github.com/pympler/pympler)  locally to see where the memory is going in worker mode bh,n

**Comment by La0** [comment]
Found by @calixteman : https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior

**Comment by marco-c** [comment]
> Found by @calixteman : https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior

This is also interesting, but the strange thing is that it's not a problem of peak memory usage, but it seems as if there is something lingering around using memory even when we are not doing anything.

**Comment by marco-c** [comment]
I've tried to set MALLOC_ARENA_MAX, let's see what happens.
Another easy thing we could try is using a different allocator, such as jemalloc.

**Comment by marco-c** [comment]
Unfortunately setting MALLOC_ARENA_MAX didn't help.

**Comment by marco-c** [comment]
jemalloc helped a lot: memory usage (on a Performance-M) on idle went from ~1,3 GB to ~100 MB.

I'm trying switching to Standard-2X again to see if we have the same improvement there or if we have to tune jmalloc a bit (in particular, the number of arenas [narenas] is 4 times the number of CPUs, and on Standard-2X we have more CPUs than on Performance-M).

**Comment by marco-c** [comment]
![memusage](https://user-images.githubusercontent.com/1616846/78790305-a0f67c00-79ae-11ea-834e-c76480489a97.png)

So yes, there is some tuning needed to get us to the same mem usage of Performance-M, but I think we can call this issue fixed: the memory usage was high because of malloc.
