### ISSUE TITLE
Add Mi metric

### ISSUE THREAD

**Issue by Luni-4** [mozilla/bugbug#1448]
https://github.com/mozilla/rust-code-analysis/commit/3e84e7172e8a482bb7275428a41a3d65e11cbb14

**Comment by rajpratyush** [comment]
@Luni-4 So we have to implement the mi metric just like we dig in that repo of rust code analysis. can you guide me more on this ?? I would like to work on this issue

**Comment by marco-c** [comment]
@rajpratyush this would be similar to 5119534.
