### ISSUE TITLE
Add Blank metric

### ISSUE THREAD

**Issue by Luni-4** [mozilla/bugbug#1482]
See https://github.com/mozilla/rust-code-analysis/commit/86ac7c967cf70be99ef8d5a138da45b1c4266dca

**Comment by rajpratyush** [comment]
@Luni-4 So we have to implement the blank metric just like we dig in that repo of rust code analysis. can you guide me morre on this ?? I owuld like to work on this issue

**Comment by marco-c** [comment]
@rajpratyush this would be similar to 51195344ff2c889ba58db4621f9c13e3091ab140.

**Comment by rajpratyush** [comment]
so can i work on both this one and #1448

**Comment by marco-c** [comment]
@rajpratyush I told you, you can work on anything you want. Issues are not assigned until there is a PR linked to them :)

**Comment by Luni-4** [comment]
Hi @rajpratyush! Thanks for your help! :)

Yes, you can implement the two issues you have chosen in this way:
- One pull request for the `Blank` metric
- One pull request for the `Mi` metric

To get the data associated to those metrics, use the reference commit posted above by @marco-c

**Comment by Patil2099** [comment]
@marco-c  @Luni-4  @rajpratyush  If this is still available I would love to work on this.

**Comment by 1Gokul** [comment]
Hey, I had started a PR on this issue but a KeyError on a line is makingthe [bugbug tests](https://community-tc.services.mozilla.com/tasks/d2w90CyRRQug4835ZEPdKQ) fail.

Copy-pasting my message on the PR:

> 
> 
> The bugbug test logs [here](https://community-tc.services.mozilla.com/tasks/P6uOPVR_TK6cmNc7k_s9bg/runs/0/logs/public/logs/live.log) always show a KeyError when using the `metrics` dictonary.
> 
> [`obj["blank_total"] += metrics["blank"]["sum"]` on line 508](https://github.com/1Gokul/bugbug/blob/e10c6a654d91ef5cc02c9cef05e4f6e792193e8c/bugbug/repository.py#L508) seems to be causing the error.
> 
> Any ideas on how to fix?

**Comment by marco-c** [comment]
@1Gokul for issues about the PR, please comment in the PR itself.

**Comment by joshua-chopra** [comment]
Hi, am I able to work on this issue or has it already been assigned to @1Gokul?

**Comment by 1Gokul** [comment]
> 
> 
> Hi, am I able to work on this issue or has it already been assigned to @1Gokul?

It's actually assigned to @Patil2099 because he made the first pull request. [My PR will be checked only if his is abandoned.](https://github.com/mozilla/bugbug/pull/2203#issuecomment-787523883)
