### ISSUE TITLE
Bugbot fails to learn not to move from Firefox::General to Core::Internationalization

### ISSUE THREAD

**Issue by zbraniecki** [mozilla/bugbug#1484]
Examples of bugs: 1609558, 1609561, 1626842, 1609557, 1579477, 1609559, 1609556, 1609562, 1597692, 1597849

I'm not sure how to notify the bot to stop doing that, and I don't like having to follow its trail and revert each one manually.

**Comment by marco-c** [comment]
These bugs seem all about migration to Fluent, I'm assuming bugbug learned that because there were many other Fluent migration bugs that were filed under Core::Internationalization.

Why isn't it the right component? Do we have a better component for those bugs than "Firefox::General"?

**Comment by zbraniecki** [comment]
Another https://bugzilla.mozilla.org/show_bug.cgi?id=1635550

**Comment by zbraniecki** [comment]
Another https://bugzilla.mozilla.org/show_bug.cgi?id=1635548

**Comment by zbraniecki** [comment]
Can I ask to please exclude `Fluent` from this behavior? The failure rate for the bugs around this are 100% and it adds to my mental overhead to chase the bugbug and revert each and every time.

**Comment by marco-c** [comment]
Yes, I'll disable moving from General to Internationalization, sorry for the delay.

**Comment by marco-c** [comment]
Fixed in https://github.com/mozilla/relman-auto-nag/pull/963.
