### ISSUE TITLE
Don't ignore commits with no bugs attached to them for test selection

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1493]
E.g. we failed on https://treeherder.mozilla.org/#/jobs?repo=try&revision=3af569898d2613443b749afb023e74c823acc861, where the three commits are:
```
no bug - Run cppcoreguidelines-pro-type-member-init on dom
no bug - Run cppcoreguidelines-pro-type-member-init on js
no bug - static analysis doc: Fix a trivial rst typo in the doc
```

**Comment by ahal** [comment]
It's fairly common to not file a bug until after you've made a WIP patch and pushed to try.
