### ISSUE TITLE
Instead of applying patch in git, fetch it from the local Mercurial repository

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1506]
Using git-cinnabar, we can replace https://github.com/mozilla/bugbug/blob/e60a51b6b744ae1c1bbd65cbc28fc7f796f851e0/scripts/commit_classifier.py#L358-L380 and just fetch the commit from the local Mercurial repository where we already applied the patch.

Then, we can stop installing `patch` in our Docker image: https://github.com/mozilla/bugbug/blob/e60a51b6b744ae1c1bbd65cbc28fc7f796f851e0/infra/dockerfile.commit_retrieval#L10.

**Comment by Dcoder99** [comment]
Hi @marco-c, I'd like to try and fix this issue! I hope that's okay :)

**Comment by marco-c** [comment]
Sure, feel free! Any issue is open for contribution by anyone. As a first step, read https://github.com/mozilla/bugbug/issues/1092.

**Comment by Dcoder99** [comment]
May I know where the Mercurial repo for bugbug is?

**Comment by marco-c** [comment]
https://hg.mozilla.org/mozilla-central/

**Comment by Dcoder99** [comment]
So what worked on my terminal is this:
$git cinnabar fetch hg::https://hg.mozilla.org/mozilla-central/ 50244579252a229131ae04a1d2c60682611e5702

I replaced lines 358-380 with:
![bugbug1](https://user-images.githubusercontent.com/28946131/81383012-f4362880-912c-11ea-8530-ad0ecfe5198a.png)

But I am not sure how to test this file, without having to run trainer.py as mentioned in the README.

**Comment by marco-c** [comment]
You will need to fetch the commit that was just applied to the local mercurial repository, not a specific commit which already exists in https://hg.mozilla.org/mozilla-central/.

**Comment by Dcoder99** [comment]
I think I've not understood what a "local mercurial repo" means. 
If I clone the link https://hg.mozilla.org/mozilla-central/ ,is it referred to as a local .hg repo? 
How or Where do I find the 'commit that was just applied to the local mercurial repository'?
I'm really sorry if its a silly question, I'm a complete beginner :P

**Comment by marco-c** [comment]
If you look at the code of the commit classifier script mentioned in the first comment, it is cloning a Mercurial repository, then cloning a git repository using git cinnabar. Then it applies a set of patches to the locally cloned Mercurial repository and tries to apply the same set of patches to the locally cloned git repository.
Instead of trying to apply the set of patches to the locally cloned git repository, we want to fetch the patches from the locally cloned Mercurial repository, since we just applied them there.

**Comment by KhadijaKamran** [comment]
Hi @marco-c ! I am an Outreachy applicant and I want to work on this issue. Can you confirm if the set of patches are applied to Mercurial from line 352-356?

**Comment by KhadijaKamran** [comment]
Hey @marco-c! Would the following command help:
git cinnabar hg2git <changeset>
