### ISSUE TITLE
Add 'reviewer experience' as feature

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#152]

**Comment by ayush1999** [comment]
@marco-c Can I work on this? If yes, could you tell me where are the reviewer details found?

**Comment by marco-c** [comment]
Sure! This will be similar to the `author experience`.

The reviewer info can be found in the commit message, but you can simply use the `reviewers` template parameter.

**Comment by ayush1999** [comment]
The template does not seem to have a `reviewers` option, as I read here : http://hgbook.red-bean.com/read/customizing-the-output-of-mercurial.html (and I also keep getting empty results when I add `reviewers` to the template). The `desc` for each commit contains `r=some_name`, so this is the reviewer detail, if I'm not wrong?

**Comment by marco-c** [comment]
You will need to enable the mozext mercurial extension in order to have that (same for backedoutby, which should be empty for you now).

After running `./mach vcs-setup` in the directory where you cloned mozilla-central, add:
hgmo = PATH/TO/VERSION-CONTROL-TOOLS/hgext/hgmo
mozext = PATH/TO/VERSION-CONTROL-TOOLS/hgext/mozext
to the extensions section of your hgrc file.
