### ISSUE TITLE
repository.py is not working

### ISSUE THREAD

**Issue by Varezki** [mozilla/bugbug#155]
I keep getting this error each time I run 'python repository.py <path>'. I'm using python3.6.8

`Traceback (most recent call last):
  File "repository.py", line 144, in <module>
    download_commits(args.repository_dir)
  File "repository.py", line 116, in download_commits
    with concurrent.futures.ProcessPoolExecutor(initializer=_init, initargs=(repo_dir,)) as executor:
TypeError: __init__() got an unexpected keyword argument 'initializer'
`

**Comment by ayush1999** [comment]
@Varezki This was updated in Python 3.7, I'd recommend you to use that.

**Comment by Varezki** [comment]
@ayush1999 I installed Python3.7 and it worked, but now run.py is giving this error
`urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
`
I think this has something to do with the dropbox url in the repository.py file but I'm not sure
Any suggestions?

**Comment by ayush1999** [comment]
The link is correct; you can visit the link to verify this. How are you running the run.py script? Also, you need to have an internet connection the first time you run the script (for downloading the data).

**Comment by Varezki** [comment]
`python run.py --train`
I run this command and the internet connection is fine but I still get the error.
I tried now to download the data manually from the browser using the link, but dropbox says "There was an error downloading your file". I think the link needs to be updated.

**Comment by marco-c** [comment]
The link works for me.

**Comment by marco-c** [comment]
Please reopen in case you still can't download those files.
