### ISSUE TITLE
extend classifiers to distinguish between defect, feature, and task

### ISSUE THREAD

**Issue by emceeaich** [mozilla/bugbug#156]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1522340

**Comment by marco-c** [comment]
This can be done pretty easily, the most time consuming part that I would need help on is collecting a few examples of bugs that are `feature` and `task`.

Two ways we can do this:
1) I can create a spreadsheet where we list bugs and we can write down the labels for them;
2) We could use a WebExtension that adds a form to Bugzilla pages to collect this info.

**Comment by emceeaich** [comment]
How many bugs would you need for training? If it's not a large number we could use a sheet.

**Comment by marco-c** [comment]
I think a couple hundred would be enough. We have already a lot of `defect` labels, so we mainly need `feature` and `task`.

I've created a sheet, you can copy it and fill as much as you can, then send it to me:
https://docs.google.com/spreadsheets/d/1xWLpllN36KmF0_44XSxrBQi0cUuV_zF10S2KlR8u4vQ/edit#gid=1115488857

(I'll do the same with my own copy, so we can compare the results to fix possible wrong labels)

**Comment by emceeaich** [comment]
I'll go through this spreadsheet Monday.

**Comment by emceeaich** [comment]
I'm also going to ask some other teams to review this list so we can reduce bias.

**Comment by marco-c** [comment]
This was done.
