### ISSUE TITLE
Use whiteboard tags for finding more perf bugs

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1561]
There are some whiteboard tags that are used for performance bugs (e.g. fxperf if I'm not mistaken). We can find more examples of perf bugs by using those tags.

**Comment by PromiseFru** [comment]
@suhaibmujahid, I believe a portion of https://github.com/mozilla/bugbug/pull/3823, deals with this issue. Does it?

**Comment by suhaibmujahid** [comment]
Yes, I think so. Even the tag mentioned as an example (i.e., `fxperf`) has already been added.
