### ISSUE TITLE
Make get_feature_importances work for multiclass problems

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#162]
Right now `get_feature_importances` fail for multiclass problems (e.g. component).

**Comment by marco-c** [comment]
@yatinmaan you might be interested in this, since you fixed #67.

**Comment by yatinmaan** [comment]
I am.
I'll open an PR as soon as possible.

**Comment by marco-c** [comment]
My suggestion would be to sort the features by "sum of importance", and then show the importance for each feature and each class side by side in a table.

(a bit like the picture at the bottom of https://github.com/slundberg/shap/blob/35e20d11e58218c25c8f2c3c0662aa706716243b/notebooks/tree_explainer/XGBoost%20Multi-class%20Example.ipynb, but as a ASCII table instead of an image)

**Comment by saurabhdaalia** [comment]
@yatinmaan , hey are you working on this?
@marco-c

**Comment by marco-c** [comment]
@saurabhdaalia the contributing rules are at https://github.com/mozilla/bugbug#contributing, you can consider all issues as unassigned until there is a PR open to fix them.

**Comment by yatinmaan** [comment]
@saurabhdaalia Yes, I am still working on this.

I have modified the .ipnb mentioned above to show [the ASCII table](https://i.imgur.com/7LGiOFy.png), now I am porting that code over to bugbug.

**Comment by spectre1811** [comment]
> @saurabhdaalia Yes, I am still working on this.
> 
> I have modified the .ipnb mentioned above to show [the ASCII table](https://i.imgur.com/7LGiOFy.png), now I am porting that code over to bugbug.

@saurabhdaalia  Could you please possibly explain in more detail what has to be done here ? ... as i want to contribute to this issue and i am a mere beginner

**Comment by marco-c** [comment]
@spectre1811 just like you, @saurabhdaalia simply asked if he could work on this :P

@yatinmaan is already working on this and has a PR open, so this issue is assigned to him. You can choose another issue.

**Comment by chidauri** [comment]
@marco-c  i've worked on this. can you please tell me a model(which doesn't take much time to train) which to test upon?

**Comment by marco-c** [comment]
@chidauri you can test it on the defect_enhancement_task model. If it runs out of memory, you can simply reduce the training set manually just for the sake of testing.

**Comment by marco-c** [comment]
@chidauri I'm now working on this though, as I'm changing a bit the visualization of the feature importance.

**Comment by marco-c** [comment]
@chidauri btw, if you have something mostly ready, you can submit a PR for it. What I'm working on is a graphic visualization, but having a raw result would be nice too.

**Comment by chidauri** [comment]
> @chidauri btw, if you have something mostly ready, you can submit a PR for it. What I'm working on is a graphic visualization, but having a raw result would be nice too.

i have a table ready as you said first sort features by sum of importance and then their importance for each class.

**Comment by marco-c** [comment]
OK, feel free to submit a PR
