### ISSUE TITLE
Investigate /push/schedules timeout for 68fc2c6f83a9a9742ab039c877555f7e25a5327e

### ISSUE THREAD

**Issue by ahal** [mozilla/bugbug#1641]
https://treeherder.mozilla.org/#/jobs?repo=try&revision=68fc2c6f83a9a9742ab039c877555f7e25a5327e

cc @marco-c

**Comment by marco-c** [comment]
I tried to run it now and it took 1 minute and 30 seconds (from 18:47:53 to 18:49:21). It must have been a fluke.
The only explanation I can think of is that maybe the workers were all busy and no worker got to this particular request in time. If we still see it, we can just increase the number of workers.
