### ISSUE TITLE
Investigate SSL error when calling /push/schedules API

### ISSUE THREAD

**Issue by ahal** [mozilla/bugbug#1642]
I made a few |mach try auto| pushes that hit this error:
https://firefoxci.taskcluster-artifacts.net/E_-ReF8CStKw8Mq75GISjQ/0/public/logs/live_backing.log

It was reproducible at first, then my patches started working again, so maybe it was some heroku issue? I didn't notice anyone else hitting it on try, but no one pushed in-between my pushes, so maybe I just got unlucky.

Just filing to get it on the record in case it appears again.

**Comment by marco-c** [comment]
It seems like it hasn't happened again.
