### ISSUE TITLE
Don't collect metrics for backouts

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#166]
This is an optimization. First of all, we need to count how many backouts we have to make sure this is worth it.

**Comment by marco-c** [comment]
We could also avoid collecting metrics for backed out commits.

**Comment by sangimanishrao** [comment]
Could you elaborate on this a little more?

**Comment by marco-c** [comment]
In the repository mining script, we need to skip collecting metrics for any commit which is a backout or which has been backed out.

**Comment by marco-c** [comment]
`hg log --template '{backedoutby}\n' | wc -l` shows that we have ~34000 commits that were backed out. If we assume that each commit backed out only one commit, by doing this we could skip ~68000 commits (in practice the number will be lower, as one commit often backs out more than one commit).
