### ISSUE TITLE
Bugbug timed out in a couple of my Try pushes

### ISSUE THREAD

**Issue by armenzg** [mozilla/bugbug#1673]
https://treeherder.mozilla.org/#/jobs?repo=try&group_state=expanded&revision=1e708cfb489393295e0272f2a7270f248cb4d459
https://treeherder.mozilla.org/#/jobs?repo=try&group_state=expanded&revision=1115e256d9dc18434a757113c1fbbc42811b2026

**Comment by marco-c** [comment]
I'm seeing some "rq.worker:Killed horse pid XXX" in the logs, must be related to the timeouts.

I haven't changed anything in the HTTP service lately that could explain this, except https://github.com/mozilla/bugbug/commit/fafc100eecba876399f04cb6815ac5939c708f3f.

I've deployed a new version with some additional logging:
> Jul 08 08:12:36 bugbug app/api: Deployed web (f7a32d6b5b92), worker (f382ae6963ff) by user heroku-relman-deployer@mozilla.com
Let's see if the timeouts happen again, and if they do, I'll try to revert the rq upgrade.

**Comment by marco-c** [comment]
> Jul 08 17:24:49 bugbug app/worker.3: 2020-07-08 16:24:49,439:INFO:rq.worker:default: bugbug_http.models.schedule_tests('try', '0ccaaabc4617c4d074a50dbcd326216594cefdcc') (c2208da3e41043f6aa5d2216796e4b28) 
> Jul 08 17:24:49 bugbug app/web.1: 2020-07-08 16:24:49,433:INFO:root:Request with API TOKEN 'pulse_listener' 
> Jul 08 17:24:49 bugbug app/web.1: INFO:root:Successfully requested try/0ccaaabc4617c4d074a50dbcd326216594cefdcc 
> Jul 08 17:24:51 bugbug app/worker.3: 2020-07-08 16:24:51,053:INFO:root:Processing schedule_tests:try_0ccaaabc4617c4d074a50dbcd326216594cefdcc... 
> Jul 08 17:24:51 bugbug app/worker.3: 2020-07-08 16:24:51,053:INFO:root:Loading commits to analyze using automationrelevance... 
> Jul 08 17:24:58 bugbug app/worker.3: 2020-07-08 16:24:58,416:INFO:root:Pulling commits from the remote repository... 
> Jul 08 17:32:50 bugbug app/worker.3: 2020-07-08 16:32:49,516:INFO:rq.worker:Killed horse pid 1471 

So it seems it is taking a very long time to pull from the remote repository (from both try and autoland).

**Comment by marco-c** [comment]
We have a good workaround now, so I'm going to call this fixed.
