### ISSUE TITLE
Use information on how a bug is filed as a feature

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1783]
This could be especially useful for the Spam model.

https://bugzilla.mozilla.org/show_bug.cgi?id=1565403

**Comment by jpangas** [comment]
I would like to attempt this.

**Comment by jpangas** [comment]
After going through `bug_features.py` and some of the bugs in `bugs.json`, It can't seem to find a field that would contain information about how a bug was filed. Am I missing something or is the field under a different name?

**Comment by jpangas** [comment]
Do I have to change the bug mining script?

**Comment by suhaibmujahid** [comment]
> Do I have to change the bug mining script?

Yes, if needed. The field on Bugzilla is called `filed_via`.

**Comment by jpangas** [comment]
I have completed training the spam bug model with the `filed_via` feature included. Should I there the performance reports here or I open a PR?

**Comment by suhaibmujahid** [comment]
> I have completed training the spam bug model with the `filed_via` feature included. Should I share the performance reports here or I open a PR?

Feel free to open a PR. It will be helpful to highlight the improvements over what we already have.
