### ISSUE TITLE
Create a classifier to detect regression bugs that have no regression range

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#18]
Needed for https://github.com/mozilla/relman-auto-nag/issues/221.

To do this, we'll need to collect some labels.
We can automatically create positive labels by getting bugs that have the `regression` keyword and the `regression-wanted` keyword.
We can't automatically create negative labels because we can't be sure that the regression range is available, when we have the `regression` keyword but no `regression-wanted`.

**Comment by ayush-1506** [comment]
@marco-c I reckon we'd have to collect negative labels manually? How should I be doing this? When I visit a bug, what should I look for to add it into the negative category?

**Comment by marco-c** [comment]
We actually have a 'Has Regression Range' field, so we can collect some positive and negative examples using that (similarly to 'Has STR').
