### ISSUE TITLE
CanvasRenderingContext2D  shape closing issue

### ISSUE THREAD

**Issue by mdmusaib** [mozilla/bugbug#1801]
We are using 2D canvas element for drawing shapes,we are using closepath() to close the shape, on that time closed coordinates are getting tapped. we using latest firefox 80.0.1 in windows 10 environment.
<img width="554" alt="firefox_pic" src="https://user-images.githubusercontent.com/19144712/92494533-746fb600-f213-11ea-894c-b47472bfeaa0.png">

expected result:
In chrome it is working fine, only in firefox it edges are looking like tapped, we need sharp edges in firefox browser.

you can check in codesandbox link below

https://oh20g.csb.app/

**Comment by marco-c** [comment]
This looks like a Firefox bug, you should use Bugzilla to report it: https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=Canvas%3A%202D.

**Comment by mdmusaib** [comment]
I already raised in bugzilla in there only , they told to raise a bug here in github bugbug...
<img width="951" alt="Screenshot 2020-09-10 152243" src="https://user-images.githubusercontent.com/19144712/92714597-0c87af80-f37a-11ea-82bc-4179390d407d.png">

**Comment by marco-c** [comment]
This project here is used by the bot (Release mgmt bot) to choose the component on Bugzilla bugs.
It moved your bug from Firefox::Untriaged to Core::Canvas: 2D (so, the right component).
You don't have to file an issue here, things will be handled in your Bugzilla bug.

**Comment by mdmusaib** [comment]
I don't know where to raise this bug, how can i raise a bug in firefox can you help me..

**Comment by marco-c** [comment]
You already raised it on Bugzilla, and that is the right place to raise it.

**Comment by mdmusaib** [comment]
okay, but I'm not getting any reply there, whether they will reply my bug?

**Comment by marco-c** [comment]
What is the bug number? Can you share a link here?

**Comment by mdmusaib** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1663945
https://bugzilla.mozilla.org/show_bug.cgi?id=1659070

same bug i raised but different style
