### ISSUE TITLE
Retrieve review data

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#185]
(Unfortunately) We'd need to gather it from multiple places:
1) Bugzilla
2) MozReview
3) Phabricator

**Comment by andreibratu** [comment]
I'd like to start working on this issue. I reckon some data scraping is needed, but I am not familiar with the project's structure. Could someone point me to where should I start?

**Comment by marco-c** [comment]
I'd start with Phabricator, as it is self-contained you can write a totally separate script (similar to bugzilla.py or repository.py).

You can look at this repo to figure out how to download data from Phabricator: https://github.com/mars-f/firefox-code-review-analysis.

**Comment by marco-c** [comment]
Done with 6e4360dd2aa0227e7b04555c054eda3ea2642717, f84945f86fe9b406829381b31f1197b8d8236f5a and a few others.
