### ISSUE TITLE
Classify multiple bugs at a time in the code to find bug-fixing commits

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1866]
We are classifying one bug at a time in https://github.com/mozilla/bugbug/blob/22222328ad277b94f08ea4f4634cee87db0ad013/scripts/regressor_finder.py#L264, we could instead collect the bugs in a list and then classify them in one go.

The script can be easily tested by running `python -m scripts.regressor_finder bug_fixing`.

**Comment by marco-c** [comment]
Hello! We don't need to sort them, we can classify them in any order.
You have an example classification of multiple items (commits in this case, but you can apply the same to bugs) here: https://github.com/mozilla/bugbug/blob/4bd73121bb86afe3d9a045ad97aea9a92fc71e21/scripts/generate_landings_risk_report.py#L277.

**Comment by Abhishek5002443** [comment]
Hey this is my first time on Github and I am looking for my first contribution. Can you please tell me, what will I need to do exactly in this request?

**Comment by marco-c** [comment]
Hello @Abhishek5002443, the description of what needs to be done is above. First of all follow https://github.com/mozilla/bugbug/issues/1092. Then, once everything is set-up, follow the pointers I gave above, try to understand that code, and then try to implement what was requested above. If you get stuck, feel free to ask questions.

**Comment by LuiGiovanni** [comment]
@marco-c Hello is this issue being worked on? I was starting to set up everything and read the guidelines because I am interested in this being my first contribution, just wanted to make sure it wouldn't conflict with someone else.

**Comment by willT97** [comment]
Hi I had a go fixing this issue, making the defect model classify in one go. Should the regression model also classify bugs at the same time?

**Comment by marco-c** [comment]
> Hi I had a go fixing this issue, making the defect model classify in one go. Should the regression model also classify bugs at the same time?

If possible yes, can you file a new issue for that?

**Comment by willT97** [comment]
> If possible yes, can you file a new issue for that?

Ok will do, created the new issue #2007 .

**Comment by 5aumy4** [comment]
Hello everyone!, I have a little past experience with open source contribution. Can I work on this bug?

**Comment by marco-c** [comment]
@5aumy4 please read the introduction first; there is already a PR open to fix this issue, so you'd need to choose another issue to work on.
