### ISSUE TITLE
Create a classifier to detect bugs that have no steps to reproduce

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#19]
Needed for https://github.com/mozilla/relman-auto-nag/issues/222 and https://github.com/mozilla/relman-auto-nag/issues/400.

To do this, we'll need to collect some labels.
We can automatically create some positive labels by getting bugs that have the `stepswanted` keyword.
We can't automatically create negative labels because we can't be sure that STR are available, when we don't have the `stepswanted` keyword.

**Comment by marco-c** [comment]
Actually, we could create some negative labels too, by looking for bugs which had `stepswanted` at some point and then the keyword got removed.

Nevertheless, some manual labeling is still needed.

**Comment by marco-c** [comment]
The has_str keyword can be used to find negative examples.

**Comment by ayush-1506** [comment]
@marco-c Could you tell me a bit about how negative examples are created here (using has_str)?

**Comment by marco-c** [comment]
> The has_str keyword

has_str is actually not a keyword, but a field.

Here you have an example of a bug with has_str (shown as "Has STR") set to yes: https://bugzilla.mozilla.org/show_bug.cgi?id=1200865
Here has_str set to no: https://bugzilla.mozilla.org/show_bug.cgi?id=898532

You can check the name of the field with the rest API: https://bugzilla.mozilla.org/rest/bug/1200865.

**Comment by marco-c** [comment]
So, negative examples: Has STR=no or stepswanted keyword
Positive examples: Has STR=yes or stepswanted keyword removed in the history
