### ISSUE TITLE
Ignore revisions from .hg-annotate-ignore-revs

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#191]
They are changes like reformatting, automated removal of code, and so on. Given that they are one-offs, maybe we should ignore them when collecting metrics.

**Comment by poojan124** [comment]
If I understand correctly, for this we need to ignore the commits whose hash matches with hash listed in file `.hg-annotate-ignore-revs`.

**Comment by marco-c** [comment]
Correct. I'm not yet sure we want to do it though.

**Comment by calixteman** [comment]
These changes are mostly cosmetic so I think we can exclude them.
For information, what are the consumers for this file ?

**Comment by marco-c** [comment]
We use the commit data in the devdocneeded model for now, but we will use it in the uplift model too.
