### ISSUE TITLE
Add ability to filter changes by target release

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1969]

**Comment by bgrins** [comment]
We also want to include the target release in the results list (probably a newline below the existing date column)

**Comment by bgrins** [comment]
There's a `versions` array on the landings artifact we could use for this. We could generate the set of options in a select dropdown by traversing the entire artifact and finding all versions in them (or just stub it out with the most recent few releases).

**Comment by marco-c** [comment]
You could also get versions from https://product-details.mozilla.org/1.0/, but I'd say it's preferable to get them from the artifact directly.

**Comment by bgrins** [comment]
@jrbenny35 is taking a look at what we can do here

**Comment by jrbenny35** [comment]
Would it make sense to scan a bunch of the bugs and only populate based on how many times a version appears?

**Comment by bgrins** [comment]
I think we could do something to the effect of:

```
var allVersions = new Set();\
for (let date in landingsData) {
  for (let bug of landingsData[date]) {
    if (bug.versions.length) {
      allVersions.add(...bug.versions)
    }
  }
}
```

**Comment by bgrins** [comment]
IOW it seems OK to have a version in the dropdown even if there's only a single bug that landed in it in the artifact
