### ISSUE TITLE
surface bugzilla component mapping in the ui

### ISSUE THREAD

**Issue by bgrins** [mozilla/bugbug#1973]
Related to the Dependency Matrix request. A bit still TBD on what this means but this should use the component_connections.json data (most_common_regression_components field)

**Comment by bgrins** [comment]
https://github.com/mozilla/bugbug/commit/b06d41a582f508f1db15c517101528006d7e4948 is a start

**Comment by marco-c** [comment]
A heatmap of the component connections has been added to the graph.html page in #2120.
We definitely want to iterate on it and show it on other pages too, but we'll track further work in separate issues.
