### ISSUE TITLE
Firefox 83.0-r1 x86_64: Crash Annotation GraphicsCriticalError: |[C0][GFX1]

### ISSUE THREAD

**Issue by BLOPESLO** [mozilla/bugbug#1995]
Steps to reproduce:

S/O: Alpine edge
Firefox 83.0-r1 x86_64
geckodriver-v0.28.0
headless=true

Actual results:

I'm trying to run firefox in headless mode with selenium.
I'm getting the following error in the last version:

1607339934953 mozrunner::runner INFO Running command: "/usr/bin/firefox" "--marionette" "--headless" "--no-remote" "-foreground" "-profile" "/tmp/rust_mozprofile6wgbbq"
*** You are running in headless mode.
Crash Annotation GraphicsCriticalError: |[C0][GFX1]: no fonts - init: 1 fonts: 14 loader: 0 (t=0.318426) [GFX1]: no fonts - init: 1 fonts: 14 loader: 0
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
Crash Annotation GraphicsCriticalError: |[C0][GFX1]: no fonts - init: 1 fonts: 14 loader: 0 (t=0.371525) [GFX1]: no fonts - init: 1 fonts: 14 loader: 0
###!!! [Parent][MessageChannel] Error: (msgtype=0x3A0028,name=PContent::Msg_PreferenceUpdate) Channel error: cannot send/recv
###!!! [Parent][MessageChannel] Error: (msgtype=0x3A0028,name=PContent::Msg_PreferenceUA content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
pdate) Channel error: cannot send/recv
JavaScript error: resource://activity-stream/lib/ActivityStreamPrefs.jsm, line 27: NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIPrefBranch.removeObserver]
JavaScript error: resource:///modules/sessionstore/SessionStore.jsm, line 2303: TypeError: subject.QueryInterface is not a function
A content process crashed and MOZ_CRASHREPORTER_SHUTDOWN is set, shutting down
console.error: Region.jsm: "Error fetching region" (new TypeError("NetworkError when attempting to fetch resource.", ""))
console.error: Region.jsm: "Failed to fetch region" (new Error("NO_RESULT", "resource://gre/modules/Region.jsm", 376))
console.warn: SearchService: "_init: abandoning init due to shutting down"
JavaScript error: , line 0: uncaught exception: 2147500036
JavaScript error: , line 0: uncaught exception: 2147500036
JavaScript error: , line 0: uncaught exception: 2147500036
JavaScript error: , line 0: uncaught exception: 2147500036
JavaScript error: , line 0: uncaught exception: 2147500036
JavaScript error: , line 0: uncaught exception: 2147500036
org.openqa.selenium.WebDriverException: Process unexpectedly closed with status 0
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'dev-selenium-alpine-ba4634dd-c921-49a5-b7fb-0b25f2459876', ip: '10.116.11.217', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-862.14.4.el7.x86_64', java.version: '1.8.0_272'
org.openqa.selenium.WebDriverException: Process unexpectedly closed with status 0(..)

**Comment by marco-c** [comment]
@BLOPESLO thanks for the report, though this is not the right place to report Firefox issues :)
The actual Firefox bug tracking system is at https://bugzilla.mozilla.org/.
