### ISSUE TITLE
Add a treemap with the feature metabugs and the number of changes landing that block them

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#1996]
A grid of feature metabugs showing a high level summary for each one. We need to define what a "high level summary" is :)

**Comment by marco-c** [comment]
@rajpratyush we still don't know exactly what this "landing page" should look like, some investigation and thinking is required first.

**Comment by rajpratyush** [comment]
well if you can describe what to include in the landing page maybe i can come up with a rough layout and then we can work ahead to make it @marco-c

**Comment by marco-c** [comment]
We don't know yet what the landing page should include. Designing the landing page is part of the issue itself.

**Comment by rajpratyush** [comment]
@marco-c Then I suggest if we could have a short google meet call whenever you are free. I have worked on improving the docs pages before. we can have a deliberation on it.

**Comment by marco-c** [comment]
@rajpratyush this is not easy, I suggest getting your hands dirty with other parts of the project first, and then once you have a clear understading of it we can discuss about this

**Comment by rajpratyush** [comment]
surely @marco-c

**Comment by marco-c** [comment]
Here's what we decided to do as a first step: a treemap with the feature metabugs and the number of changes landing that block those feature metabugs.
