### ISSUE TITLE
Bookmarked website not starred when opened

### ISSUE THREAD

**Issue by RiyaJ2311** [mozilla/bugbug#2029]
**Steps to reproduce**
1. Go to the firefox website
2. check the bookmark bar 
3. Press Right-click
4. Open it in a new tab
5. Wait a few seconds on the current tab
6. Switch to a new tab

**Expected behavior**
The website must be starred

**Actual behavior**
See video: https://drive.google.com/file/d/19fu00Um8nZFB1H0bIc0Y5Q-EU2cMjDcB/view?usp=sharing

**Device information**

- Device name DESKTOP-UTB3367
- Processor Interl(R) Core(TM) i5-8250U CPU @ 1.60GHz 
- System Type - 63-bit operating system, x64-based processor

**Comment by marco-c** [comment]
Hey @RiyaJ2311, thanks for the report, but this is not the bug tracking system for Firefox.
You should open a bug on https://bugzilla.mozilla.org/.
