### ISSUE TITLE
Add documentation of a new feature as Data and User's reviews as dependent variable

### ISSUE THREAD

**Issue by RushabhVasani** [mozilla/bugbug#203]
We can predict the the overall impact of a new feature which we are thinking to add by training this kind of model.
Every time when we add a new feature we would have to make users  give reviews or stars to it and by making  review or stars as a dependent variable and the full documentations of that newly added feature as the data of the feature and by training on that data we can I think predict that  how the feature we are thinking to add is going to help others and  and is going to make impact on the world.The only thing we will have to give the model is the pre-documentation of the supposed feature.

**Comment by marco-c** [comment]
Who will give reviews and starts to the proposed features?

I feel it would be better to rely on the results of the added feature (see if a model improves after adding it), rather than trying to collect feedback from multiple users.

**Comment by RushabhVasani** [comment]
Okay !
So you are telling that we should train the model on the documentation as Data and feature's performance after adding it as a dependent variable.

But I think only from documentation of a proposed feature we can not say that this feature is going to the make the performance better or not. Because  I think there is no good enough interaction between the words of the documentation and the improvement in the performance.Because I feel the documentation of the feature will be only containing the details of the feature but the performance would depend on what algorithm we use,which language and framework we use and all that stuff.

But I think we can predict that  "yes, lastly this feature's integration in this kind of direction won lots of people's hearts and lots of people were helped by this another kind of feature ,And the update we are thinking to make is a mixture of those feature in a similar kind of directions so this feature is probably going to make a good impact so we should focus on it ".
Tell me if I am going wrong because I know you are an expert and I am just learning out these things and trying to understand the things better.
And Thanks for your response sir !:)@marco-o

**Comment by marco-c** [comment]
>  So you are telling that we should train the model on the documentation as Data and feature's performance after adding it as a dependent variable.

No, I think we shouldn't do this at all :)
We should not try to train the model on the documentation of features, we should just add features and add them to models only if they improve the models.

**Comment by RushabhVasani** [comment]
Okay than!:)
And I'm sorry for wasting your time.I'm closing this issue now.

**Comment by marco-c** [comment]
No worries, you didn't waste time, it was an interesting idea (but not so easily applicable in this case).

**Comment by RushabhVasani** [comment]
Okay ! Thanks for your compliment.
Actually I am thinking to try for mozilla's this BugBug project to contribute in GSoC this summer and I was just watching all the conversations and the code base and by watching that I got an Idea that you people are trying to make the operations of the issues and bugs be automated and from that I got this Idea.
