### ISSUE TITLE
Convert dates to PlainDate just once

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#2039]
I've seen the conversion from string to PlainDate in a performance profile. We are currently doing that multiple times, it's best to do it just once when we load the artifact.

**Comment by bgrins** [comment]
We could also expose a function from common.js that memoizes results from the call so we could then find/replace `Temporal.PlainDate.from` to `getPlainDate`. Might make it easier if it turns out we sometimes want the string dates and sometimes want the date object.

**Comment by bgrins** [comment]
Although not sure if there'll be issues with sharing the same Temporal object from different callers with the same date string. I believe they are stateless and it'd be fine, but would have to double check.
