### ISSUE TITLE
Optimize sorting

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#2040]
Sorting the bug summaries is quite slow, we should try to optimize it (implementing it manually instead of using `sort`?) or at least try to break its computation using requestIdleCallback to make page load (and reload after filter changes) look smoother.

**Comment by bgrins** [comment]
Alternatively, find a third party table library that handles sorting more efficiently

**Comment by marco-c** [comment]
Converting dates to Temporal.PlainDate just once (f23985f046fb97235319cb1fd38afe94be82a548) removed the sorting from my profile.
