### ISSUE TITLE
Show the number of fixed regressions alongside new regressions in the summary graph

### ISSUE THREAD

**Issue by bgrins** [mozilla/bugbug#2051]
Right now we see what I assume is total regression bugs filed (both fixed and not) grouped in the graph. It'd be helpful to break that down so that we can see how many new regressions carried over per release, for instance.

**Comment by bgrins** [comment]
Also @marco-c just wanted to clarify - bugs that eventually get duped (or closed as invalid / wontfx) don't get counted in this data / included in the artifact?

**Comment by marco-c** [comment]
> Also @marco-c just wanted to clarify - bugs that eventually get duped (or closed as invalid / wontfx) don't get counted in this data / included in the artifact?

They were, let me fix that.
