### ISSUE TITLE
Show changed components (and/or teams) in a heatmap in the summary view

### ISSUE THREAD

**Issue by bgrins** [mozilla/bugbug#2078]
Based on a discussion with relman, it would be helpful to visualize what's changed across components in a given time period or release.

**Comment by marco-c** [comment]
Both changes to components and, separately, what other components could be affected by those changes.

**Comment by marco-c** [comment]
In this view we could also include stability data (how many crashes are occuring in files belonging to a given component).

**Comment by marco-c** [comment]
Changes at the component-level for 86:
![immagine](https://user-images.githubusercontent.com/1616846/107684158-bc9f7280-6ca2-11eb-9425-339ac048e877.png)

**Comment by marco-c** [comment]
Changes at the team-level for 86:
![immagine](https://user-images.githubusercontent.com/1616846/107684230-d0e36f80-6ca2-11eb-8ec9-d3291bcef9ca.png)
