### ISSUE TITLE
Add a "Include unfixed bugs" option in the filters

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#2079]
Instead of adding a N/A option to the releases dropdown.

**Comment by bgrins** [comment]
I wonder if unfixed bugs should just always be treated differently. Like in a different table and either not included in, or split out separately in graphs or summary view. I elaborated a bit on this in https://github.com/mozilla/bugbug/issues/2065#issuecomment-759686697

**Comment by bgrins** [comment]
One problem with unfixed bugs being in this UI is that unless if you set a hardcoded date range it can be kind of unexpected which bugs should be included. I.e. do we just take the earliest date in the fixed bug set and filter on creation_date for unfixed? That can lead to some outliers like https://github.com/mozilla/bugbug/issues/2065#issuecomment-754749577 when filtering on a release. Maybe we need to handle "release" filtering (and maybe other filter fields) differently for unfixed than fixed. Meaning only unfixed bugs that got filed during the release should be included.

**Comment by bgrins** [comment]
@marco-c Just curious - for unfixed bugs do we add any additional data in the artifact beyond what we would get from bugzilla rest API on the client?

**Comment by marco-c** [comment]
> @marco-c Just curious - for unfixed bugs do we add any additional data in the artifact beyond what we would get from bugzilla rest API on the client?

No, everything we have for unfixed bugs comes from the Bugzilla REST API (with some postprocessing of the fields).
