### ISSUE TITLE
Add a function to generate a heatmap with component connections

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#2090]
We should add a function in common.js to draw a heatmap. The function will later be used in multiple views (at least the team-level view).

The function should use the data coming from `getComponentRegressionMap` (introduced in https://github.com/mozilla/bugbug/pull/2089).
The function should draw the heatmap either at the team level (showing dependencies between teams), or at the component level (showing dependencies between components).
The function should accept a list of source and target teams/components to filter the teams/components to draw in the heatmap (so, for example, in the team level view we will only show dependencies where the target of the dependency is the selected team).

**Comment by bgrins** [comment]
A few notes from our conversation

* New parameter to getComponentRegressionMap to include "subdependency levels" 
* Take over graph.html for UI. Start with a single component

**Comment by jrbenny35** [comment]
Is there an idea of what this UI would look like?

**Comment by marco-c** [comment]
I'd start with a heatmap, like https://apexcharts.com/javascript-chart-demos/heatmap-charts/basic/. Or like the one that is currently present in graph.html.

**Comment by jrbenny35** [comment]
Is the idea of the graph supposed to be one huge graph will all the components?

**Comment by jrbenny35** [comment]
Trying to understand this a bit more. If we have Component 1 and Component 2. We enter those into the function and they both have similar components. What is the heatmap actually supposed to display? Is it the amount the components have caused regressions? So if Component 1 had a component that caused a regression by 10%, and component 2 had that same regression,  but it was 5%, would the heatmap display that?

**Comment by marco-c** [comment]
Yes, the heatmap would basically be something like:
![immagine](https://user-images.githubusercontent.com/1616846/105750998-bb054900-5f45-11eb-8ac9-05c7dd9075bf.png)
where both rows ("metric1", "metric2", etc.) and columns ("w1", "w2", etc.) would actually be components, and the color would be stronger or lighter according to the connection between the two components.

The "connection" between the components would be the number which is in the map returned by the function @bgrins introduced in #2089 (e.g. `connectionsMap["Component 1"]["Component 2"]`). It is currently the percentage you mentioned, but in the future it could be more complex and be generated by some kind of formula which takes into account multiple data points. It doesn't matter for this issue though, as you can "blindly" use `getComponentRegressionMap` and assume its map is the right one to draw.

**Comment by jrbenny35** [comment]
It seems like this will just create 1 row. 

Component 1 as the row, and the components that are children of it within the JSON object as columns. Is that correct?

**Comment by marco-c** [comment]
The map returned by `getComponentRegressionMap` should be something like:
```
{
    "component1": {
        "component2": 0.2,
        "component3": 0.1,
        ...
    },
    "component2": {
        "component4": 0.5,
        ...
    },
    ...
}
```

From this map, you should be able to build a heatmap composed of multiple rows and columns. The keys of the map ("component1" and "component2" above) will be the rows, the keys of the submaps ("component2", "component3", "component4" above) will be the columns. The color will be defined by the values in the submap (for the row-column "component1"-"component2" the color will be defined by map["component1"]["component2"], it would be 0.2 above).

**Comment by jrbenny35** [comment]
Thanks for that explanation marco. It seems the heatmap will be pretty big then, and that is why I kept asking for clarification.

**Comment by jrbenny35** [comment]
Should I add the capability to select a few components to compare? I know that is something we want to add but I feel it is needed or the chart just never loads and is unusable really

**Comment by marco-c** [comment]
@jrbenny35 you could add a generic function to draw the heatmap in common.js, with the characteristic I mentioned earlier:
>  The function should accept a list of source and target teams/components to filter the teams/components to draw in the heatmap (so, for example, in the team level view we will only show dependencies where the target of the dependency is the selected team).

In the graph.html page (you could start from there as a first usage of the function), you could draw the heatmap for a specific component/team (you can hardcode it at first).

**Comment by marco-c** [comment]
A first version has been built in #2120, I've opened separate follow-up issues to track further work.
