### ISSUE TITLE
videos are semi transparent if I'm not in fullscreen mode

### ISSUE THREAD

**Issue by Toadfield** [mozilla/bugbug#2097]
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0

Steps to reproduce:

Go to a youtube video and play it in windowed mode.
That bug doesn't happen in Fullscreen.

Actual results:

It is semi transparent vin windowed,like this:
https://i.imgur.com/iErS8K9.png

Expected results:

That it isn't transparent.

"layers.acceleration.force-enabled" to "true" doesn't help.
Here my "about:support":
https://pastebin.com/zuyUVMEi

**Comment by marco-c** [comment]
@Toadfield thanks for the report, but this is not the issue tracker for Firefox :)
You should file a bug on https://bugzilla.mozilla.org/

**Comment by marco-c** [comment]
@Toadfield this GitHub project is what powers the bot :)
It automatically detected a good component (Audio/Video) for your bug and set it on Bugzilla. If you think "Audio/Video" is a good component for your bug (it looks like it is), then there is no action needed from you. If you think the component is bad, you can change it on Bugzilla, or add a comment on Bugzilla.

**Comment by Toadfield** [comment]
oh,thanks for the explanation.
