### ISSUE TITLE
Create a classifier to detect bugs that need QA

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#21]
Needed for https://github.com/mozilla/relman-auto-nag/issues/227.

To do this, we'll need to collect some labels.
We can automatically create some positive labels by getting bugs that have the `qawanted` keyword or that have `qe-verify` flag.
We can't automatically create negative labels because we can't be sure that QA was not needed when the keyword/flag was not set.

**Comment by ayush1999** [comment]
@marco-c The function for generating labels will return `True` if `qawanted` is a label and `False` otherwise, right?

**Comment by marco-c** [comment]
#22 was the first step here, adding a function to create the labels. Now we need to add some code to run.py to use it.

**Comment by ayush1999** [comment]
@marco-c  The `args.goal` in run.py would need to have a new QA option right? Also, are there some models present at the moment to test these changes?

**Comment by marco-c** [comment]
@ayush1999 yes, there should be a new `qaneeded` option. There isn't a model present yet, since you're just adding the code to train now :smile:

**Comment by marco-c** [comment]
#27 added the code to train.

The result seems too good to be true though, so we need to figure out if there is some feature that should be not considered in the 'qaneeded' case.

**Comment by ayush1999** [comment]
@marco-c Currently we are considering labels that have `qawanted` or `qe-verify` keyword. What should we be experimenting with to check the validity of the model? Should we be checking for a specific keyword that might cause the condition to be false? (So we'd have to remove that condition too)

**Comment by marco-c** [comment]
It's possible that we are using those keywords as features, which clearly would make the problem too easy :smile: 
We have to remove these keywords from the training for this 'qaneeded' case. Currently it's not easy to do it, so this will have to wait for the refactoring from https://github.com/marco-c/bugbug/issues/6.

**Comment by marco-c** [comment]
#6 is done, and c95a6f809d45991489591066ebf5ff0b86ff4d2f made it possible to make the feature extractors configurable.
For the QA wanted case, we should clearly remove `qawanted` from the keywords extractor.

**Comment by marco-c** [comment]
Here's an example for the regression model: https://github.com/marco-c/bugbug/commit/e9d291aaae297c885688db7583a4bfc6200ede8f#diff-5f2351779b955b08e775eb4234c3f2ebR28.

We should do something similar for the qaneeded model, with the only difference being that in that case we want to ignore the `qawanted` keyword.

**Comment by marco-c** [comment]
Actually, we still need to make use of #5 when that's ready.

**Comment by marco-c** [comment]
We now have #5, so we can finish this up by making use of it.
I'll use #5 in the components model, so you can see an example of how to use it.

**Comment by marco-c** [comment]
I started with the `tracking` model, here's an example: 97d3bc2c41172b3cac54b0593787e329e2a1574e.

**Comment by marco-c** [comment]
@ayush1999 do you want to finish this up?

**Comment by ayush1999** [comment]
Sure. If I'm not wrong, a rollback option needs to be added to the qaneeded model, which returns True if `'field_name`` starts with `qa` right?

**Comment by marco-c** [comment]
The rollback option needs to be coherent with the labeling, that is we have to rollback either to when qawanted was added or to when qe-verify was added.

**Comment by ayush1999** [comment]
Right, abd we also need to add this option to `bug_snapshot.py`, right? Right now nothing happens when `field_name` in `['qawanted', 'qe-verify']`.

**Comment by marco-c** [comment]
No, bug_snapshot is generic, for each history change it calls the function to check when it should stop.
