### ISSUE TITLE
Mercurial command to retrieve changesets to analyze is using 'central' branch, even if it doesn't exist on a non-unified repository

### ISSUE THREAD

**Issue by sbeesm** [mozilla/bugbug#212]
It shows:
```
Mining 0 commits using 4 processes...
0it [00:00, ?it/s]
Analyzing 0 patches...
Mining commits using 4 processes...
0it [00:00, ?it/s]
```

I've also tried using `hg pull central` in the Mercurial repo, but it does not fix the problem.

**Comment by marco-c** [comment]
Try debugging it.
The first message is already wrong, 'Mining 0 commits ...', so it means the len at https://github.com/mozilla/bugbug/blob/a9eb10c87095bbc88aae9c6cbc69ce037396f0fc/bugbug/repository.py#L134 is 0.
If the len is 0, then it means https://github.com/mozilla/bugbug/blob/a9eb10c87095bbc88aae9c6cbc69ce037396f0fc/bugbug/repository.py#L122 returned an empty list.

So, try running that command manually with hg and see what the output is:
`hg log --template '{node}\n' --no-merges -r 'pushdate("2018-01-01"):tip' --branch central`

If the output is empty, try small variations of the command to see if there is something wrong with it (e.g. try removing the `--branch central` part).

**Comment by sbeesm** [comment]
The problem is with `--branch central` part, removing it gives an output. But the command with `--branch central` shows this error:

`abort: unknown revision 'central'!`

**Comment by marco-c** [comment]
OK, so the fix here would be to wrap https://github.com/mozilla/bugbug/blob/87ac0f3426a9fe89a2729c2bd9abb6caa1d0432c/bugbug/repository.py#L124 in try-except, and retry without the branch parameter in case of the exception.

**Comment by sbeesm** [comment]
Looks like `hglib.util.cmdbuilder` does not raise an exception for this. 

It shows similar behaviour even after wrapping it in try-except.

**Comment by sbeesm** [comment]
I tried running the script by explicitly removing the branch parameter but it still shows 0 commits.

But that's strange because it works fine within `mozilla-build` shell.

So could this be an issue with the hglib library?

**Comment by marco-c** [comment]
> Looks like hglib.util.cmdbuilder does not raise an exception for this.

Then the easiest solution would be to run the command, check if there are zero results, and rerun the command without the branch parameter next.

> I tried running the script by explicitly removing the branch parameter but it still shows 0 commits.
> But that's strange because it works fine within mozilla-build shell.
> So could this be an issue with the hglib library?

It's very unlikely. Did you try running exactly the same command? The one I gave you is an example, but it doesn't have the same date value as the one that would be run by repository.py.

**Comment by sbeesm** [comment]
> Did you try running exactly the same command? The one I gave you is an example, but it doesn't have the same date value as the one that would be run by repository.py.

Yes I tried running the same command:
```
args = hglib.util.cmdbuilder(b'log', template='{node}\n', no_merges=True, rev='pushdate("2018-01-01"):tip')
```
This returns empty data.

And I am facing this problem with python 3.7.1. But when I tried running it in a standalone script in python  2.7.14, it works fine:
```
args = hglib.util.cmdbuilder(b'log', template='{node}\n', no_merges=True, rev='pushdate("2018-01-01"):tip')
x = hg.rawcommand(args)
len(x)
2559138
```

Any idea why this might be the case?

**Comment by poojan124** [comment]
I am using python `3.7.1` and hg `4.9`. And its working for me. 
I used` hg pull central` followed by `hg up central` and repository.py working fine for me.

**Comment by marco-c** [comment]
The same standalone script works in Python 2.7 but not in Python 3.7? If this is the case, then it could be a bug in Mercurial. Could you file a bug (following https://www.mercurial-scm.org/wiki/BugTracker) and copy the link to the bug you file here?

**Comment by sbeesm** [comment]
> The same standalone script works in Python 2.7 but not in Python 3.7?

Actually the issue is with the path to the extensions in the hgrc file and not the python version.

While using WSL, I added the extensions with path as `/mnt/c/Users/HP/.mozbuild/version-control-tools/...`. But this returns 0 commits.

Then I tried running script with python 2.7 on windows shell with path as `C:/Users/HP/.mozbuild/version-control-tools/...`. And this works fine and returns non zero commits.

Any suggestions how can I fix this?

**Comment by marco-c** [comment]
A couple options:
1) Try running the `mach vcs-setup` command suggested in the README.md file under WSL, it should add at least one of those extensions, and then you can try using the same path format.
2) Use a Linux VM.

**Comment by sbeesm** [comment]
I tried running `mach bootstrap` and `mach vcs-setup` under WSL, and added the extensions in the hgrc file in the home directory. Everything else is working fine and now I am also able to run `hg up central` but I'm not able to fix this error with extensions: 
```
*** failed to import extension pushlog from ~/.mozbuild/version-control-tools/hgext/pushlog: No module named utils
*** failed to import extension hgmo from ~/.mozbuild/version-control-tools/hgext/hgmo: No module named utils
```

It the module `utils` somehow related to the extension or something else is wrong?

**Comment by marco-c** [comment]
From the error message, I'd say it is related.

If everything is working fine though, I guess you can ignore the error.

**Comment by villmow** [comment]
Hi, I just stumbled on your nice project and am currently trying to find myself around. I'm getting a similar error when running repository.py:

```
> bugbug$ python repository.py ../mozilla-central/ 0
Getting revs from 0 to tip...                                                                                                                     
Args: [b'log', b'--template={node}\n', b'--no-merges', b'--branch=central', b'--rev=0:tip']                                                             
Traceback (most recent call last):                                                                                                                
  File "repository.py", line 816, in <module>                                                                                                     
    download_commits(args.repository_dir, args.rev_start)                                                                                         
  File "repository.py", line 709, in download_commits                                                                                             
    revs = get_revs(hg, rev_start)                                                                                                                
  File "repository.py", line 356, in get_revs                                                                                                     
    x = hg.rawcommand(args)                                                                                                                       
  File "/home/johannes/projects/buglytics/env-bug/lib/python3.6/site-packages/hglib/client.py", line 263, in rawcommand                           
    raise error.CommandError(args, ret, out, err)                                                                                                 
hglib.error.CommandError: (255, b'', b"abort: unknown revision 'central'!")
```

I'm using python3 on Ubuntu. I executed `hg pull central` in the mercurial-central repository, however I'm not able to execute `hg up central` (I executed the vcs-setup). The output is: 
```
> mozilla-central$ hg up central
(third party extension push-to-try requires version 4.6 or newer of Mercurial; disabling)
*** failed to import extension pushlog from ~/.mozbuild/version-control-tools/hgext/pushlog: No module named utils
*** failed to import extension hgmo from ~/.mozbuild/version-control-tools/hgext/hgmo: No module named utils
*** failed to import extension firefoxtree from ~/.mozbuild/version-control-tools/hgext/firefoxtree: 'module' object has no attribute 'getargspec'
abort: unknown revision 'central'!
``` 

How shall I proceed from here? I can catch every exception in the `repository.py` script and execute the command without `--branch central`, but this seems somehow wrong. What am I doing wrong here?

**Comment by marco-c** [comment]
It looks like the mercurial extensions are not working (see the `failed to import extension ...` messages).
Which version of Mercurial are you using?
