### ISSUE TITLE
FF85 Print Bug: FF adds a emty site to every print at printing integrated PDFs

### ISSUE THREAD

**Issue by Gnjp66** [mozilla/bugbug#2121]
Steps to reproduce:

Open a website with integrated pdf in FF84 oder in FF85.

https://www.jena.de/fm/41/test.pdf

Actual results:

Print it in FF84 and you get **one printed Page**. (_Thats correct!_)

Do the same in FF85 and you **get the 1 Page with content and 1 other emty page without content**. (_Thats incorrect!_)

Expected results:

In both Versions, FF84 and FF85 you **should get only the ONE PAGE with content as it is shown in the browser**!

**Comment by marco-c** [comment]
@Gnjp66 for Firefox problems, you should file a bug on https://bugzilla.mozilla.org/.
