### ISSUE TITLE
URL stop working

### ISSUE THREAD

**Issue by fracting** [mozilla/bugbug#2196]
https://hacks.mozilla.org/2020/07/testing-firefox-more-efficiently-with-machine-learning/
https://hacks.mozilla.org/2019/04/teaching-machines-to-triage-firefox-bugs/

These two links worked yesterday, but there were 404 today, not sure what's going on?

**Comment by marco-c** [comment]
The URLs have been changed (e.g. https://hacks.mozilla.org/testing-firefox-more-efficiently-with-machine-learning/). I asked for a redirect to be set up: https://bugzilla.mozilla.org/show_bug.cgi?id=1695431.

**Comment by marco-c** [comment]
It was fixed.
