### ISSUE TITLE
Update list of components

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#220]
https://bugzilla.mozilla.org/show_bug.cgi?id=1533440

Maybe we should just use the top X components rather than manually selecting them.

**Comment by saurabhdaalia** [comment]
@marco-c, I  have been trying to train the component model, but it is taking an awful lot of time to train, and eventually throws some sort of memory error. 
https://github.com/dmlc/xgboost/issues/2907
Is it specific to OS or Machine Configuration?

**Comment by marco-c** [comment]
Maybe you don't have enough memory. This is off-topic for this issue though!
