### ISSUE TITLE
need possible update in requirements.txt

### ISSUE THREAD

**Issue by SiluPanda** [mozilla/bugbug#221]
while running the run.py after installing all packages in requirements.txt,
i got following error:

1. cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (/home/silupanda/anaconda3/lib/python3.7/site-packages/numpy/lib/arraypad.py)

The is actually is a sklearn and numpy version issue which appears to be satisfied while running the requirements.txt.
reference of the issue: https://github.com/scikit-image/scikit-image/issues/3551

**Comment by SiluPanda** [comment]
added a PR of a small change in requirement.txt https://github.com/mozilla/bugbug/pull/222 . @marco-c  kindly review

**Comment by sbeesm** [comment]
Which version of `scikit-image` are you using? Try updating it to version `0.14.2` and the problem should be solved.

See #120 for reference.

**Comment by SiluPanda** [comment]
i was using everything as it is in requirement.txt.
version is 0.20.3. 
i agree that this can be avoided with multiple ways, i did a PR #222 with one of the solutions.

**Comment by marco-c** [comment]
When you install the requirements from our requirements file, you'll get scikit-image 0.14.2, so this issue doesn't really apply.
