### ISSUE TITLE
repository.py not working

### ISSUE THREAD

**Issue by sbeesm** [mozilla/bugbug#234]
It shows this error while analyzing the patches:

```
Mining 50 commits using 4 processes...
100%|█████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:11<00:00, 11.13s/it]
Analyzing 48 patches...
Traceback (most recent call last):
  File "bugbug/repository.py", line 279, in <module>
    download_commits(args.repository_dir, two_years_and_six_months_ago)
  File "bugbug/repository.py", line 201, in download_commits
    author_experience[commit] = total_commits_by_author[commit.author]
TypeError: unhashable type: 'list'
```

**Comment by marco-c** [comment]
Add some debugging statements around the failing line to gather more information, otherwise this issue is not actionable.

**Comment by sbeesm** [comment]
The problem is with the changes I made locally, related to PR #229.

For [this](https://github.com/mozilla/bugbug/pull/229#discussion_r268796842), I did parse the data in _hg_log like this:

```
...
files=rev[7].decode('utf-8').split('|'), 
file_copies={fl[fl.find('(') + 1:-1]: fl[:fl.find('(') - 1] for fl in rev[8].decode('utf-8').split('|')},
))
...
```
And this makes the files a `list` and file_copies a `dictionary`. 
But when this commit is passed as a key to author_experience, it shows:
 `TypeError: unhashable type: 'list'`

**Comment by marco-c** [comment]
You can use `commit.node` as a key in the dictionaries instead of the whole `commit`.

(Closing as this is not an issue with the current code, but with a PR).
