### ISSUE TITLE
Add 'has bug ever had enhancement severity' as a feature

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#244]
Especially useful for the bug and regression models.

**Comment by rhcu** [comment]
Seems that I oversimplified the issue. :p Shouldn't it just check whether 'severity' field is equal to 'enhancement' or not? Or is all the difficulty in word "ever" - do we need to check all history of a bug for the 'severity' component?

**Comment by marco-c** [comment]
The 'enhancement' severity has been removed lately, so yes, we need to check in the history :)

**Comment by marco-c** [comment]
(but it is still easy enough)

**Comment by marco-c** [comment]
Since going forward bugs won't have enhancement severity, we can only use this for archeology (we should probably have two different models, one to analyze old bugs, one to analyze new bugs).
