### ISSUE TITLE
db.last_modified should return None if the DB version changed

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#2459]
When we change the version of a DB, we want to re-download everything.

E.g. say we bump the GitHub issues DB to a newer version, the next run of the retriever will get the last modified of the DB in the old version but without downloading the old version DB, and then will only download issues starting from that last modified date. We'll end up with a small subset of issues.

**Comment by webbdays** [comment]
How do we know, if the db version is changed.
How do we know the present db versions ?
Is it saved in any file for each db ?
I was not able to find.
If no such file is there,  we can create a db_versions file to store the present versions of all db.

Then have a check if ever the version of any db is changed in the register or last_modified function and perform what we needed when db version is changed. 

In db_versions file...
COMMIT_DB => 22
BUGS_DB => 7

**Comment by webbdays** [comment]
According to this commit c7087d76462a2c6fa2b8fa1e39be7724f176d7d0

db version is changed manually.

so, I am gathering all the at present db version of each db into a db_versions.json file for doing version check.

**Comment by webbdays** [comment]
In the first commit of my pull request #2653 , I have not used any json file.
I have created another function named is_db_version_changed  after looking at is_old_schema function.

For is_db_version_changed function, I have used the same code of is_old_schema function but small change in return statement.

**Comment by webbdays** [comment]
> When we change the version of a DB, we want to re-download everything.
> 
> E.g. say we bump the GitHub issues DB to a newer version, the next run of the retriever will get the last modified of the DB in the old version but without downloading the old version DB, and then will only download issues starting from that last modified date. We'll end up with a small subset of issues.

But you mentioned here, we need to download

**Comment by marco-c** [comment]
By "re-download everything" here I meant regenerate the DB from scratch.
