### ISSUE TITLE
Create an option in bug model for analyzing old bugs

### ISSUE THREAD

**Issue by rhcu** [mozilla/bugbug#248]
Details are here: https://github.com/mozilla/bugbug/issues/244#issuecomment-480284787 and https://github.com/mozilla/bugbug/pull/247#issuecomment-480756156

**Comment by rhcu** [comment]
May I clarify, should this option be added similar to `lemmatization` option here (https://github.com/mozilla/bugbug/blob/2d5a646784eb18b645dbfaae6a5e7401bf1e355a/bugbug/models/bug.py#L19) as well as to args parameters in `run.py`?  And then if true, severity feature will be added to feature_extractors in `bug.py`.

**Comment by marco-c** [comment]
Yes, exactly!
