### ISSUE TITLE
Create a DUPLICATE detector

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#25]

**Comment by marco-c** [comment]
This is the current code on Bugzilla: https://github.com/mozilla-bteam/bmo/blob/88101dcba7f4e60c862c14b6ba9c0861c62d3395/Bugzilla/Bug.pm#L766-L847.

**Comment by sylvestre** [comment]
We have a keyword _dupeme_ which might be useful to help

**Comment by sylvestre** [comment]
I improve the data with this in autonag:
https://github.com/mozilla/relman-auto-nag/pull/548
