### ISSUE TITLE
Add a cache for pip packages in Taskcluster builds

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#258]

**Comment by La0** [comment]
Or use the docker image produced by the docker build task and run inside

**Comment by marco-c** [comment]
Filed #272 for that.

**Comment by La0** [comment]
I made some tests, it will be more complicated than i thought: setting up the Taskcluster cache is easy, but using it while building a Docker image is complex.

The protocol for mounting an host folder during an image build [is still an experimental feature](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/experimental.md) and has several limitations:

- we can only use `mode=bind` for our use case
- the source must be in the build context, so in the midlle of our repo...
- but even with `readwrite` enabled, the doc says : **Written data will be discarded.**
- which means we cannot really cache anything...

I tested that with img and this Dockerfile:

```
#syntax=docker/dockerfile:experimental
FROM alpine

RUN echo 'taskboot !' > /etc/taskboot
RUN --mount=type=bind,source=/.cache,target=/cache,rw \
  echo 'plop' > /cache/plop
```

The build goes OK, but i don't have the `plop` file on my host cache... 

The *old* way to do that is to `COPY` a cache in the image, then use a staging image... that's dirty too.

**Comment by marco-c** [comment]
OK, yeah, sounds like building all the images in the same task is the best option.

**Comment by marco-c** [comment]
What if we build the base image in a task, and have another task to build the derived images.
In both tasks, we'd pull the previous base image first, so that we can benefit from the docker caching.

**Comment by marco-c** [comment]
I'm not sure if it still makes sense to have a pip cache, now that we are benefiting from Docker layer caching.

**Comment by marco-c** [comment]
> I'm not sure if it still makes sense to have a pip cache, now that we are benefiting from Docker layer caching.

@La0 what do you think? I think we can close this.

**Comment by La0** [comment]
Yes, we can.
