### ISSUE TITLE
Add support for building models on GitHub issues data

### ISSUE THREAD

**Issue by daxmc99** [mozilla/bugbug#259]
Awesome project! 
I was curious if there were any plans for github integration in the future?
If not, what might be a way to begin adding that?

**Comment by marco-c** [comment]
Yes, we were thinking about that. Some models might make sense for GitHub too (e.g. the assignee model), some might make sense only for very complex projects (e.g. the component assignment will not be so useful for small projects, as they have no components).

The first step would be adding support to retrieve issues' data from GitHub. There are likely already libraries to do that.
