### ISSUE TITLE
bugbug team UI does not load any graphs on Nightly 96

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugbug#2639]
![bugbug1](https://user-images.githubusercontent.com/55210859/143010749-a0924383-387e-4797-a610-22e66abc57b1.PNG)

Note that this seems to happen only with Nightly 96 ? On FF release 94 it seems to work. I did empty all local storage of "moz.tools" to no avail.

**Comment by marco-c** [comment]
I can reproduce this in Nightly too, but not on ESR. I can also not reproduce it on an older Nightly, so this looks like a Firefox bug.
I'm narrowing down the regression range with mozregression.

**Comment by marco-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1742572

**Comment by marco-c** [comment]
It's actually a bug in the temporal polyfill: https://github.com/js-temporal/temporal-polyfill/issues/92.
