### ISSUE TITLE
Merge common parts of .taskcluster.yml

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#268]
This will make the file more readable.

**Comment by Abhi-khandelwal** [comment]
Can we merge 'tasks_for == "github-push" && head_branch[:10] == "refs/tags/"' at  L244 & L281

**Comment by marco-c** [comment]
Not sure, maybe.
I was mainly talking about the parts common to all tasks, such as metadata/owner and metadata/source. You have an example of merging in https://github.com/mozilla-mobile/android-components/blob/9ddbaaf4084dc2e18a547de9f525ebdc528e1361/.taskcluster.yml#L158.

**Comment by Abhi-khandelwal** [comment]
Hi @marco-c  with the reference of  above link, I was thinking, that first we should, define a parameter like owner_and_source_details and then by using $mergedeep command we can merge , and similarly for other parameters. is it okay to this by that way?

**Comment by marco-c** [comment]
You can have a `default_task_definition` like in the example and put there everything which is in common.

**Comment by Sujay-Tandel** [comment]
Hello Marco,
If this bug is still open, can I attempt this as my first bug?

**Comment by marco-c** [comment]
@Sujay-Tandel no need to ask, you can work on any issue which is open and has no open PR linked to it.

**Comment by timalsinab** [comment]
Hello, I am an outreachy applicant. Can I work on it?

**Comment by suhaibmujahid** [comment]
> Hello, I am an outreachy applicant. Can I work on it?

no need to ask, you can work on any issue which is open and has no open PR linked to it.
