### ISSUE TITLE
Quality report email: infer assignment status from the assignee field instead of the bug status

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugbug#2691]
In my last report I received as a carry over regression:

Bug 1740144 | 21 days ago | Unassigned |  

But this bug has been assigned 21 days ago, so the assignment status seems wrong here.

**Comment by marco-c** [comment]
Bug 1740144 is in the list because we are looking for the "Status" field, and the "Status" field in that bug is "UNCONFIRMED".
@jensstutte do you think I should not list these bugs anyway, and so only list bugs where "Status"!=ASSIGNED and "Assignee" is empty? Or maybe only list those where the "assignee" is empty?

**Comment by jensstutte** [comment]
It is totally ok to see the bug in the list, but I'd want to see it as "Assigned". Currently "Unassigned" highlights a problem that is not there.

**Comment by marco-c** [comment]
Sorry, it would be in the list anyway.
What I meant was: should we show it as Assigned even though the Status is UNCONFIRMED? Should we consider bugs as assigned:
- when status is ASSIGNED
- when assignee is not empty
- when status is ASSIGNED and assignee is not empty
- when status is ASSIGNED or assignee is not empty

Currently I'm using the first rule. I would go with the second (so the bug you mentioned would be shown as Assigned, and a bug with status ASSIGNED buy empty assignee would be shown as Unassigned). Do you agree?

**Comment by jensstutte** [comment]
Oh, sure, now I see. Yes, I think status ASSIGNED without an assignee is a problem we should highlight. And UNCONFIRMED with an assignee could be read as "X is investigating", too, so no problem.
