### ISSUE TITLE
Quality report email: TEST COVERAGE shows very old patch

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugbug#2692]
The list of lowest coverage patches contains only one entry and that is a patch that landed 1,5 yy ago:

D78222 - 0.0%

**Comment by marco-c** [comment]
This is a weird one...

**Comment by marco-c** [comment]
Oh, I think it showed up because there was another patch landing that was linked to the same bug.
I'm not looking at the date of the revision but the date of the bug. Should be easy to fix.
