### ISSUE TITLE
Make infra/version_check.py only run on branches and tags, not pull requests

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#271]
It is painful for contributors otherwise.

**Comment by sbeesm** [comment]
We need to change `.taskcluster.yml` for this, right?

Removing version-check command for pull-request task and adding that for github-push?

**Comment by marco-c** [comment]
Yep. We can either make the linting task only run flake8 and define a separate task that runs this script, or we can make the linting task always run flake8 and run this script only if github-push.
