### ISSUE TITLE
Quality report mail: maintenance effictivenes seems to use still an old (wrong) calculation

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugbug#2714]
We corrected the metric in #2636 but the mail seems to report still the old values.

**Comment by jensstutte** [comment]
I just verified, the current master produces the expected results.

**Comment by marco-c** [comment]
5c7fc9375a2bb1f023cd039d97b44817f3a3dc32 is the fix for the script.

We need to apply the same change in the quality notification code, or, probably better, replace the ME code in the quality notification code with this script.

**Comment by jensstutte** [comment]
Can we align this, please?
