### ISSUE TITLE
Add number of previous commits touching the same directories as a feature

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#278]
Similar to #112 and #113.

**Comment by sbeesm** [comment]
Do we need to find the source directories as listed here: https://wiki.mozilla.org/Modules/All?

**Comment by marco-c** [comment]
We can simply use the directories of the repository (first and second-level directories)

**Comment by sbeesm** [comment]
So can we just use the commit files from hg_log template to find the directories?

**Comment by marco-c** [comment]
Yes.
