### ISSUE TITLE
Train spambug model on components from all products

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#2786]
We apply the model to bugs from Thunderbird too for example, but we only train on Firefox, Toolkit, etc. bugs. This means Thunderbird bugs are more likely to be wrongly marked as spam.

To fix this, we have to change our bug mining script (https://github.com/mozilla/bugbug/blob/18d270df3cdaa639093a37bde96bed639fb7470b/bugbug/bugzilla.py#L53) to also get Thunderbird (and a few other products: "Calendar", "Chat Core", "MailNews Core") bugs, but then we have to exclude these products from all other models and only use them in the spambug model.

**Comment by Amotul-raheem** [comment]
@marco-c and @suhaibmujahid  I started looking into this, and I think spambug is trained across all products in bugs.json. While I was debugging I found 114 unique products, part of which include the following 
`'Product Innovation', 'Data Platform and Tools Graveyard', 'Firefox for iOS', 'Penelope Graveyard', 'addons.mozilla.org', 'Hello (Loop)', 'NSS', 'SeaMonkey', 'Pocket', 'B2GDroid Graveyard', 'Core', 'User Research', 'Developer Documentation Graveyard', 'UX Systems', 'Other Applications', 'Remote Protocol', 'Mozilla Labs', 'bugzilla.mozilla.org', 'Firefox', 'Firefox Health Report Graveyard', 'NSPR', 'Documentation Graveyard', 'Web Compatibility', 'Websites Graveyard', 'Chat Core', 'External Software Affecting Firefox', 'Developer Services', 'Developer Engagement', 'DevTools', 'developer.mozilla.org', 'Taskcluster', 'Localization Infrastructure and Tools', 'Tracking', 'Mozilla QA Graveyard', 'addons.mozilla.org Graveyard', 'Marketplace Graveyard', 'Input Graveyard', 'Firefox for Android Graveyard', 'Thunderbird', 'www.mozilla.org', 'Webtools', 'Conduit', 'Tree Management Graveyard', 'Data & BI Services Team', 'developer.mozilla.org Graveyard', 'DevTools Graveyard', 'Add-on SDK Graveyard', 'Webmaker Graveyard', 'Tech Evangelism Graveyard', 'Mozilla Metrics', 'Other Applications Graveyard', 'MailNews Core Graveyard', 'Webtools Graveyard', 'Developer Ecosystem', 'Toolkit Graveyard', 'Infrastructure & Operations Graveyard', 'Plugins Graveyard', 'bugzilla.mozilla.org Graveyard', 'Community Building', 'Firefox Affiliates Graveyard', 'mozilla.org', 'Core Graveyard', 'Minimo Graveyard', 'Location', 'Instantbird', 'MailNews Core', 'Mozilla Localizations', 'Websites', 'User Experience Design', 'Release Engineering Graveyard', 'Testing', 'Participation Infrastructure', 'Mozilla Foundation Communications', 'Mozilla Reps Graveyard', 'MozillaClassic Graveyard', 'Firefox Graveyard', 'Data Platform and Tools', 'Firefox Build System', 'Infrastructure & Operations', 'Invalid Bugs', 'Socorro', 'support.mozilla.org', 'Directory', 'Security Assurance', 'Developer Infrastructure', 'Testing Graveyard', 'Lockwise Graveyard', 'Cloud Services', 'Firefox for Metro Graveyard', 'Air Mozilla', 'Mozilla Labs Graveyard', 'L20n', 'External Software Affecting Firefox Graveyard', 'Camino Graveyard', 'Release Engineering', 'Snippets', 'WebExtensions', 'Content Services Graveyard', 'Calendar', 'Cloud Services Graveyard'...` 

Please correct me if I'm missing something here.

**Comment by marco-c** [comment]
@Amotul-raheem I think there are only few bugs from Thunderbird because we are not retrieving them as part of https://github.com/mozilla/bugbug/blob/7a3a81ec4ba6b279fd37ec1f94847f6f74957a0f/bugbug/bugzilla.py#L28.

Normally, the bugzilla retriever script retrieves bugs we have manual labels for (https://github.com/mozilla/bugbug/tree/master/bugbug/labels) + bugs from that list of products. Probably you see some Thunderbird bugs because we have some manual labels for them, but they are too few for the spambug model.

**Comment by suhaibmujahid** [comment]
@Amotul-raheem Thank you for doing this!


> Thunderbird bugs appeared 1249 times

Thunderbird product has more than [62K bugs](https://bugzilla.mozilla.org/rest/bug?product=Thunderbird&count_only=1), out of that [9.4K](https://bugzilla.mozilla.org/rest/bug?product=Thunderbird&f1=creation_ts&o1=greaterthan&v1=-30m&count_only=1) created in the last 30 months only.


> Can't seem to find where we check against the PRODUCTS in the file referenced above for spambug model, the lables seem to be used mostly in defect, defect_enhancement_task model etc

We check against the defined products here: 
https://github.com/mozilla/bugbug/blob/19f43fc1abb40faf2c273d4ad59d2e633523775d/bugbug/bugzilla.py#L161-L167

Then we combine these with the labelled bugs:
https://github.com/mozilla/bugbug/blob/19f43fc1abb40faf2c273d4ad59d2e633523775d/scripts/bug_retriever.py#L59-L70

The retriever process generates the `data/bugs.json` file, which is used in all models.

**Comment by Amotul-raheem** [comment]
@suhaibmujahid Got it, makes sense. Thank you! I'll spend some more time looking into it.

**Comment by Amotul-raheem** [comment]
> @Amotul-raheem Thank you for doing this!
> 
> > Thunderbird bugs appeared 1249 times
> 
> Thunderbird product has more than [62K bugs](https://bugzilla.mozilla.org/rest/bug?product=Thunderbird&count_only=1), out of that [9.4K](https://bugzilla.mozilla.org/rest/bug?product=Thunderbird&f1=creation_ts&o1=greaterthan&v1=-30m&count_only=1) created in the last 30 months only.
> 
> > Can't seem to find where we check against the PRODUCTS in the file referenced above for spambug model, the lables seem to be used mostly in defect, defect_enhancement_task model etc
> 
> We check against the defined products here:
> 
> https://github.com/mozilla/bugbug/blob/19f43fc1abb40faf2c273d4ad59d2e633523775d/bugbug/bugzilla.py#L161-L167
> 
> Then we combine these with the labeled bugs:
> 
> https://github.com/mozilla/bugbug/blob/19f43fc1abb40faf2c273d4ad59d2e633523775d/scripts/bug_retriever.py#L59-L70
> 
> The retriever process generates the `data/bugs.json` file, which is used in all models.

I spent some time looking into the code base and I was looking at the wrong place. Basically, I was running the trainer.py with spambug as an argument locally therefore I was just downloading the bug.json file. However, After checking the data pipeline and I looked through the model dependency I figured out how the data was retreived.

**Comment by suhaibmujahid** [comment]
Thank you for reporting this, @amccreight! Resolving https://github.com/mozilla/bugbug/issues/2786 should increase the bot's accuracy when dealing with Thunderbird bugs.

In the meantime, we could make the bot avoid touching bugs that were moved out of the `Invalid Bugs` product.

**Comment by marco-c** [comment]
@jpangas looking again at your PR, there's something missing. You added additional products here https://github.com/mozilla/bugbug/blob/e1b8ced9c19e51c88501c1ada8e4e4ec2c5cdae4/bugbug/models/spambug.py#L138
but not here https://github.com/mozilla/bugbug/blob/e1b8ced9c19e51c88501c1ada8e4e4ec2c5cdae4/bugbug/models/spambug.py#L96.

**Comment by jpangas** [comment]
Thanks @marco-c, made a PR ( #4432 ) including the change.
