### ISSUE TITLE
Create a model to identify accessibility bugs

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#2833]
To get labels, we can use the presence of "access" in the keywords, or the presence of "access-s" in the whiteboard.

**Comment by Chandu-4444** [comment]
I'd like to work on this.

**Comment by suhaibmujahid** [comment]
You are more than welcome. If you need any help or have any questions, please join the [bugbug](https://chat.mozilla.org/#/room/#bugbug:mozilla.org) Matrix room. I will be glad to help.

**Comment by suhaibmujahid** [comment]
> As far as I understood, the goal is to build a model that assigns accessibility label to the relevant issues?

Yes, accessibility bugs are tagged manually with [`access`](https://mzl.la/3Gi3zLL) keyword or `[access-s*]` in the whiteboard field (e.g., [`[access-s2]`](https://mzl.la/3lKnfOW)). The goal is to automatically label such bugs as soon as they got reported.

**Comment by suhaibmujahid** [comment]
You could start by setting up the environment and installing the dependencies as explained in the [readme file](https://github.com/mozilla/bugbug#setup-and-prerequisites).

Next, you could try training an existing model; [`spambug`](https://github.com/suhaibmujahid/bugbug/blob/master/bugbug/models/spambug.py) model could be a good candidate:
```
python3 -m scripts.trainer spambug
```

If you feel stuck, do not hesitate to ask in [bugbug](https://chat.mozilla.org/#/room/#bugbug:mozilla.org) Matrix room

**Comment by prernadabi23** [comment]
Hello, @suhaibmujahid I would like to work on this issue as this will provide me some insights into the main project. How do I start?

**Comment by suhaibmujahid** [comment]
> Hello, @suhaibmujahid I would like to work on this issue as this will provide me some insights into the main project. 

Feel free to do that.

> How do I start?

Please read the comments above.

**Comment by suhaibmujahid** [comment]
> I did run this command but I didn't understand anything.

Have a look here: https://github.com/mozilla/bugbug#structure-of-the-project to get an idea about the project structure. Seeing how other models are implemented could be helpful.

**Comment by jpangas** [comment]
While trying to work this issue, I thought, can't we extend the `bugtype` model to also identify and label `accessibility` bugs?
