### ISSUE TITLE
Run the linting task only on modified files

### ISSUE THREAD

**Issue by Lothiraldan** [mozilla/bugbug#298]
We could reduce the duration of linting tasks by running pre-commit only on modified / new files. But we need to be careful about edge-cases like people pushing several commits at the same time.

**Comment by marco-c** [comment]
This is a good-first-bug for somebody who's really familiar with git.

**Comment by thedeveloperr** [comment]
Hey I would like to work on it. I am new to bugbug, would like to take a try. Can you please assign it to me ? Also if possible some guidance or tips for an absolute new contributor to bugbug like me. 😅

**Comment by marco-c** [comment]
Hello @thedeveloperr, you can work on any issue that you see open, but issues are not assigned until there is a PR open to fix them (see CONTRIBUTING.md).

To fix this, https://github.com/mozilla/bugbug/blob/331aa50f1fa5e142bd0870ede25721c8bda6a54a/.taskcluster.yml#L46 needs to be done.

**Comment by dishvyas** [comment]
So i need to find a way to run pre-commit on modified files only which will require me to write a function to get the modified files only and then run the command. Am i understanding it wrong or missing something here??

**Comment by marco-c** [comment]
@dishvyas there is already a PR open to fix this, #791.
