### ISSUE TITLE
Make NLP dependencies optional

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#307]
Some dependencies are only needed in some images, we should make some dependencies optional so that they are only installed when necessary.

For example, Spacy is the biggest dependency, but it is currently not really used by any image.

**Comment by marco-c** [comment]
Let's start with Spacy, Tensorflow and Gensim, which are currently not used in any image.

There is bugbug code that is trying to import them, so we should change it so that we don't fail if the modules are not available.

Not sure what's the best implementation for this.

**Comment by La0** [comment]
We could set them up as extra dependencies on the bugbug package.

For dev environment: ```pip install bugbug[ml-lib-whatever]```
For docker build : ```cd /tmp/bugbug && pip install .[ml-lib-whatever]```

**Comment by Lothiraldan** [comment]
Sounds good.

Just to be sure, they are not used because the Docker images do not user part of bugbug who need these dependencies, right?

**Comment by marco-c** [comment]
> Just to be sure, they are not used because the Docker images do not use part of bugbug who need these dependencies, right?

Yep. Those dependencies in particular are not used by any image at the moment (e.g. tensorflow would be used by the component_nn model, but we are not using it yet).

Instead, other dependencies are only used by some images. E.g. only the bug retriever images use 'requests', the training images don't use it.

**Comment by Lothiraldan** [comment]
I've started a PR for this https://github.com/mozilla/bugbug/pull/310

As you can see, it's a bit of work for each optional dependency and I'm not sure the cost would be worth it for popular libraries like requests.
