### ISSUE TITLE
Make ML dependencies (XGBoost, scikit-learn, etc.) optional

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#318]
See also #307 and #317.

**Comment by marco-c** [comment]
Only the training images and the http service image are using this dep.

**Comment by marco-c** [comment]
Not sure it's worth it, it would add complexity in several places.

**Comment by Lothiraldan** [comment]
Yeah at least 7 differents files needs to be updated, I'm not sure about the cost
