### ISSUE TITLE
Store pipeline tasks in the index, and update Taskcluster URLs in scripts

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#325]
The scripts are still using the old URLs from releng-services.

**Comment by Lothiraldan** [comment]
Are we speaking about these URLs? https://github.com/mozilla/bugbug/blob/master/scripts/trainer.py#L18

I see these URLs used to retrieve models, but I'm not sure where configure where we push the artifacts, is it the `artifacts` part of the data-pipeline.yml?

**Comment by marco-c** [comment]
The artifacts part only specifies the artifacts the task uploads.

The index can either be populated programmatically, or using a route (e.g. see the static analysis hook, https://tools.taskcluster.net/hooks/project-releng/services-production-staticanalysis%2Fbot, which has index.project.releng.services.project.production.static_analysis_bot.latest in the routes, which results in https://tools.taskcluster.net/index/project.releng.services.project.production.static_analysis_bot/latest).
