### ISSUE TITLE
Integration testing of the data pipeline

### ISSUE THREAD

**Issue by Lothiraldan** [mozilla/bugbug#329]
We will actually run the data pipeline code, downloading, training, building the http service and running the http service for real only after doing a release.

We should have a lightweight integration testing before the release to have a minimum of confidence that the release will works.

We could train on a subset of data (few commits and few bugs) then ask the http service to classify the trained bugs to ensure we have a stable answer and that the whole pipeline runs quite quickly.

**Comment by marco-c** [comment]
#823
