### ISSUE TITLE
Refactor print statments to use logger

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3322]
Example of a print statement that we want to replace (not limited to the `duplicate.py` file):

https://github.com/mozilla/bugbug/blob/69972a1684f788319bf5c2944bbe8eeb79428c7d/bugbug/models/duplicate.py#L123

Example of a logger that we already use (to replace with):

https://github.com/mozilla/bugbug/blob/69972a1684f788319bf5c2944bbe8eeb79428c7d/scripts/regressor_finder.py#L521

Note: please use lazy % formatting in logging functions (more details can be found in the [pylint docs](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-fstring-interpolation.html))

**Comment by WhiteWolf47** [comment]
This issue is similar to issue #3323 , i think i can help out with this too :blush:

**Comment by suhaibmujahid** [comment]
The target is to refactor all cases. Most of the cases still need to be refactored.

**Comment by ishaan-sangwan** [comment]
i think i can help out with this

**Comment by skynette** [comment]
Hi @suhaibmujahid can I take on this issue?

**Comment by suhaibmujahid** [comment]
> Hi @suhaibmujahid can I take on this issue?

Yes, you do not need to ask. Please start by reading https://github.com/mozilla/bugbug/issues/1092

**Comment by BhaswatiRoy** [comment]
Hello @suhaibmujahid 
Can I work on refactoring the print statements in version_check.py?

**Comment by suhaibmujahid** [comment]
> Hello @suhaibmujahid Can I work on refactoring the print statements in version_check.py? https://github.com/mozilla/bugbug/blob/0de8c327ad1ed275015231fd1657294eb32cf9b1/infra/version_check.py

@BhaswatiRoy This issue already has an open pull request (see the guidance for first contributors in https://github.com/mozilla/bugbug/issues/1092)



> > Hi @suhaibmujahid can I take on this issue?
> 
> Yes, you do not need to ask. Please start by reading #1092

@skynette Sorry, I just noticed that this issue has a linked pull request that is still open. Please consider working on another issue.

**Comment by BhaswatiRoy** [comment]
> > Hello @suhaibmujahid Can I work on refactoring the print statements in version_check.py? https://github.com/mozilla/bugbug/blob/0de8c327ad1ed275015231fd1657294eb32cf9b1/infra/version_check.py
> 
> @BhaswatiRoy This issue already has an open pull request (see the guidance for first contributors in #1092)
> 
> > > Hi @suhaibmujahid can I take on this issue?
> > 
> > 
> > Yes, you do not need to ask. Please start by reading #1092
> 
> @skynette Sorry, I just noticed that this issue has a linked pull request that is still open. Please consider working on another issue.

thanks for informing, I will head over to the remaining issues.
