### ISSUE TITLE
Refactor logging statements to use lazy % formatting

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3323]
Example of logging statements that we want to refactor:

https://github.com/mozilla/bugbug/blob/d53595391dbd75379bb49bff12dee4821e4b956c/bugbug/github.py#L61

https://github.com/mozilla/bugbug/blob/69972a1684f788319bf5c2944bbe8eeb79428c7d/scripts/regressor_finder.py#L396

More details can be found in the [pylint docs](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-fstring-interpolation.html).

**Comment by WhiteWolf47** [comment]
@suhaibmujahid I would like to help out and work on this issue, would you please assign this to me :blush:

**Comment by suhaibmujahid** [comment]
> @suhaibmujahid I would like to help out and work on this issue, would you please assign this to me 😊

You can work on any issue which is open and has no PR linked to it.

Did you read https://github.com/mozilla/bugbug/issues/1092 or [CONTRIBUTING.md](https://github.com/mozilla/bugbug/blob/master/CONTRIBUTING.md)?

**Comment by WhiteWolf47** [comment]
> > @suhaibmujahid I would like to help out and work on this issue, would you please assign this to me blush
> 
> You can work on any issue which is open and has no PR linked to it.
> 
> Did you read #1092 or [CONTRIBUTING.md](https://github.com/mozilla/bugbug/blob/master/CONTRIBUTING.md)?

yes I did

**Comment by suhaibmujahid** [comment]
The target is to refactor all cases. Most of the cases still need to be refactored.

**Comment by KhadijaKamran** [comment]
Hi @suhaibmujahid, are there any cases still left or is this issue fixed?

**Comment by suhaibmujahid** [comment]
> Hi @suhaibmujahid, are there any cases still left or is this issue fixed?

I still see one case:

https://github.com/mozilla/bugbug/blob/f9906057a5281b8913fb5a92edbe73440953581b/scripts/retrieve_training_metrics.py#L98
