### ISSUE TITLE
Add more guidelines in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by jpangas** [mozilla/bugbug#3332]
The current guidelines work for experienced contributors, but new contributors with little knowledge of Git may find it challenging. To make it easier for new contributors to get started, It would be great to include some guidelines that guide a new contributor from when they fork the repository upto submitting their first PR. 

I would be more than willing to take this up.

This issue is also related to #1092

**Comment by suhaibmujahid** [comment]
Thank you, @jpangas! Feel free to review the linked PR.
