### ISSUE TITLE
Replace general exceptions with a specific ones

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3337]
More details here: https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/broad-exception-raised.html

Example of a general exception that should be replaced:
https://github.com/mozilla/bugbug/blob/69972a1684f788319bf5c2944bbe8eeb79428c7d/bugbug/model.py#L192

The goal is to replace all general exceptions, not only in the `model.py` file.

**Comment by prernadabi23** [comment]
@suhaibmujahid Please assign this issue to me, I would like to work on it.

**Comment by Emeka-Onwuepe** [comment]
@suhaibmujahid I am a bit curious, the get_feature_names method in the Model Class will always return an empty list. Is this the ideal implementation?

**Comment by suhaibmujahid** [comment]
> @suhaibmujahid Please assign this issue to me, I would like to work on it.

You do not need to ask. Please start by reading https://github.com/mozilla/bugbug/issues/1092



> @suhaibmujahid I am a bit curious, the get_feature_names method in the Model Class will always return an empty list. Is this the ideal implementation?

The `get_feature_names()` will not be called directly; it is a placeholder that will be overridden. Alternatively, returning an empty list could be replaced by raising`NotImplementedError`.

However, this question is off-topic. For simmiler questions, you could open a new issue, use [Discussions](https://github.com/mozilla/bugbug/discussions) or chat with us in the [bugbug](https://chat.mozilla.org/#/room/#bugbug:mozilla.org) Matrix room.

**Comment by Emeka-Onwuepe** [comment]
Thanks for the reply and the corrections are duly noted.

**Comment by Munaelekwa** [comment]
https://github.com/mozilla/bugbug/pull/3343
