### ISSUE TITLE
Unify the logging's improt statments in the `bugbug/models` directory

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3364]
Use `import logging` instead of `from logging import INFO, basicConfig, getLogger`.

**Comment by fadebowaley** [comment]
I will like to work on this

**Comment by fadebowaley** [comment]
@suhaibmujahid  I just submiited a PR for this, thank you for the feedback and review

**Comment by fadebowaley** [comment]
Similar issue occurs in the test file, can  I raise an issue for it and fix ?

**Comment by suhaibmujahid** [comment]
> @suhaibmujahid I just submiited a PR for this, thank you for the feedback and review

Please link it to the issue. 




> @suhaibmujahid Similar issue occurs in the test file, can I raise an issue for it and fix ?

I will open other issues later. But you should not be working on that. Since you worked on this issue, you should try working on other types of issues (also not `good-first-bug`).

**Comment by fadebowaley** [comment]
I have link to the issue, Kindly help confirm If its ok
