### ISSUE TITLE
Get rid of run.py and move its functionality to scripts/

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#339]
The train functionality is already partly implemented in script/trainer.py.

**Comment by ayush-1506** [comment]
@marco-c How is the script/trainer.py supposed to run? (I see that we can't run it from the command line directly.)

**Comment by marco-c** [comment]
You can run it like this: `python3 -c 'from scripts import trainer; trainer.main()'`.

This issue is a bit problematic, as we need to make a few decisions before moving stuff, so let's not do it yet.

**Comment by marco-c** [comment]
We can now do this, so I've added back the 'good-first-bug' label.

**Comment by Lothiraldan** [comment]
You can also launch it with `bugbug-train`

**Comment by asmaknikar** [comment]
can I claim this issue?

**Comment by asmaknikar** [comment]
can I claim this issue?

**Comment by marco-c** [comment]
@asmaknikar you can work on any issue which is unassigned and has no open PR linked to it (read CONTRIBUTING.md).

**Comment by Abhi-khandelwal** [comment]
Hi @marco-c , So I was kind of interesting to take this issue, Actually I have one doubt, that do we have to run this functionality by some Bash script or by direct script/trainer.py ?

**Comment by marco-c** [comment]
We need to split the run.py functionality into multiple scripts under script/.
(Part of) The train functionality is already in trainer.py.

**Comment by cklyyung** [comment]
Seems like args.classify and args.generate_sheet could be split into scripts called bug_classifier.py and generate_sheet.py (or some other names along those lines). However, both of these require a trained model. Do you want these scripts to call the trainer.py script to train the models if the file can't be loaded? Or should the user be informed that the model should be trained beforehand by running trainer.py?

**Comment by marco-c** [comment]
> Or should the user be informed that the model should be trained beforehand by running trainer.py?

This one!

**Comment by cklyyung** [comment]
I think this will be easier to review if it's broken into multiple PRs. I plan to divide this into:

- [ ] generate_sheet.py

- [ ] bug_classifier.py

- [ ] add extra functionality to trainer.py

- [ ] remove run.py and update readme

I can do it in one PR if you'd prefer though.

**Comment by marco-c** [comment]
Yeah, breaking into multiple PRs is the best option!
