### ISSUE TITLE
Store training metrics in the Taskcluster index after training

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#342]

**Comment by Lothiraldan** [comment]
I remember a conversion where we said we should abort if the metrics are not good enough just after training, this way we don't generate bad models. If so, do we still need to store training metrics after training?

**Comment by marco-c** [comment]
We'll need some reference values for the metrics. We could hardcode them, or use the ones from a previous run (getting them from the index).

The check during training will be relaxed (e.g. if it decreases by 1%, we can't fail the training), so with the history of previous trainings we can see if things are slowly worsening over time.

So this could still be useful, even if less useful than the check itself.
