### ISSUE TITLE
On a new release, the hook is triggered in its old version rather than the new

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#345]
It looks like the hook is triggered before being updated. Maybe we have to stop using the route and use the insertTask API here. We need to check with Taskcluster.

**Comment by marco-c** [comment]
Even better solution: create a new dummy task that depends on the update hook task, move the index route from the update hook task to this new dummy task.

**Comment by Lothiraldan** [comment]
The route was added on docker push task rather than on the hook update task, that might explains why the old hook was triggered.

**Comment by marco-c** [comment]
Yeah, very likely
