### ISSUE TITLE
Remove unneeded train images

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#350]
They are mostly the same as the bugbug base image, plus a CMD.
We could use the bugbug base image and add the CMD in the task payload.

This will make things more flexible, as we won't need to create new repositories on docker hub for each train image. Also, caching at runtime will work better (all tasks will use the same image), and builds and pushes should get faster.

**Comment by Lothiraldan** [comment]
This would be easier on the maintenance side but every user of those images will need to pass the right CMD and we will need to synchronize the data-pipeline as it would contains commands with the right version of the Docker images so it might be a bit harder to rollback.

For caching, are we squashing the images right now with the way we are building the images? If so, yeah it would be better for caching.

**Comment by marco-c** [comment]
Right, the need to synchronize the pipeline would destroy the rollback when we change the command (even though changing the command should be pretty rare).

**Comment by marco-c** [comment]
I'm thinking that we can actually do this. The pipeline definition is in the spawn image anyway, so to rollback everything, we just need to rollback the hook to use an older image, containing an older pipeline definition.

**Comment by Lothiraldan** [comment]
@marco-c What is the procedure to ask for the creation of a `bugbug-train` Docker image on dockerhub?

**Comment by marco-c** [comment]
Here's an example: https://bugzilla.mozilla.org/show_bug.cgi?id=1557809.

For the spawn one, I already asked for it (and it was created) in https://bugzilla.mozilla.org/show_bug.cgi?id=1550436.

**Comment by Lothiraldan** [comment]
I opened an issue to get the new image created

**Comment by marco-c** [comment]
> I opened an issue to get the new image created

Link?

**Comment by Lothiraldan** [comment]
> > I opened an issue to get the new image created
> 
> Link?

Oops, the paste have failed https://bugzilla.mozilla.org/show_bug.cgi?id=1559444
