### ISSUE TITLE
Use `Booster.save_model` when saving XGBoost models instead of `pickle`

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3505]
```
WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-11.0-arm64-cpython-38/xgboost/src/learner.cc:553: 
  If you are loading a serialized model (like pickle in Python, RDS in R) generated by
  older XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for more details about differences between saving model and serializing.
```

**Comment by Inyrkz** [comment]
Hi @suhaibmujahid, I'm an Outreachy Intern eager to contribute to this project by addressing some of the identified issues. To get started, I'm in the process of familiarizing myself with the project's structure. Would you kindly assist me by indicating which script contains the code for the XGBoost model? Your guidance would be greatly appreciated.

**Comment by suhaibmujahid** [comment]
@Inyrkz thank you for your interest in the project! Please have a look at the readme file to get an idea about the project structure: https://github.com/mozilla/bugbug/tree/master#structure-of-the-project

**Comment by Inyrkz** [comment]
Thank you for steering me in the right direction.

**Comment by Isaakkamau** [comment]
Hello @suhaibmujahid I'm trying to work on this issue since no pr is linked to it! What prompted the above error?

**Comment by suhaibmujahid** [comment]
The warning above appears when loading a model that was trained in an older version of XGBoost. For example, training a model using XGBoost v1.7.5, saving the model using `pickle`, then loading the model again after updating XGBoost to v1.7.6.
