### ISSUE TITLE
Add "seniority" feature to commit data

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#355]
Right now we are calculating the experience in terms of number of commits. We should also add a "seniority" feature, which would be the time since the first commit in the repo.

**Comment by abinmn** [comment]
I am new to open source and I would like to contribute. can I take up this issue?

**Comment by marco-c** [comment]
Sure! Any issue which is not assigned is free to work on (see the CONTRIBUTING file with the rules).

The implementation will have to be in bugbug/repository.py (please follow the README to make sure you can run it).
The script is pretty slow, so I suggest limiting the number of commits to analyze. You can simply do that by changing https://github.com/mozilla/bugbug/blob/3c91af9c60f6b94349975a56017a2bc109b28b6a/bugbug/repository.py#L547 to a smaller time span (e.g. months=1).
