### ISSUE TITLE
Refactor `count_bugs` to use `libmozdata`

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3676]
We should use the `Bugzilla` class from `libmozdata.bugzilla` instead of doing a direct request:

https://github.com/mozilla/bugbug/blob/082613fc3a1121a9ec6f235990e61b829f407267/bugbug/bugzilla.py#L282-L291

Example:

https://github.com/mozilla/bugbug/blob/082613fc3a1121a9ec6f235990e61b829f407267/bugbug/bugzilla.py#L110

**Comment by akshayamadhuri** [comment]
@suhaibmujahid   i would like to work on this issue can you help me with this

**Comment by suhaibmujahid** [comment]
@akshayamadhuri you are welcom to work on the issue! You can start by following the instructions in [Guidance for first contributors](https://github.com/mozilla/bugbug/issues/1092).
