### ISSUE TITLE
Train models on TaskCluster whenever their corresponding files are modified

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3688]
Whenever a file in the `bugbug/models` directory is modified, we could have a task to train the corresponding model.

For example, if a new Pull Request is modifying the `bugbug/models/defect.py` file, the task should train the `defect` model:
```
python -m scripts.trainer defect
```

**Comment by marco-c** [comment]
As a first step, we could build a script to do this "manually" and not on PRs (doing it on PRs might be a bit complicated, as we need to run the whole pipeline to be able to train a model)

**Comment by suhaibmujahid** [comment]
It would be nice if we could trigger TaskCluster training using the same script with an optional argument. 

Example:
```
python -m scripts.trainer defect --taskcluster
```

**Comment by suhaibmujahid** [comment]
As suggested by Marco, we could use [TaskCluster API](https://docs.taskcluster.net/docs/manual/using/api) to replicate creating a task like https://community-tc.services.mozilla.com/tasks/RpQqfhKgT6GTlvOmK9i_vw/runs/0
