### ISSUE TITLE
Use all threads when decompressing with zstd

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#3692]
We should use the `-T0` option (or use the `zstdmt` binary instead of `zstd`).

**Comment by lutfiaomarr** [comment]
hi @marco-c im an outreachy applicant and i would like to contribute to this issue,please assign me this issue

**Comment by suhaibmujahid** [comment]
@lutfiaomarr you do not need to be assigned to work on the issue. Please read https://github.com/mozilla/bugbug/issues/1092.
