### ISSUE TITLE
Drop the `bug` model

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3695]
The model has been renamed to `defect` in https://github.com/mozilla/bugbug/pull/335/files#diff-74f32ab12cc9be314b1fead3a281590c768699c2e9883b8346066f6c4d6daa90 

However, the definition of `bug` model was not dropped.

We need to drop the following line: https://github.com/mozilla/bugbug/blob/c228c2a686b271f7ca24a0716cda4f9059229d9f/bugbug/models/__init__.py#L16

**Comment by goldpanth3r** [comment]
Hey! I tried to solve the issue. Please review the commit and give feedback if any changes are required.
