### ISSUE TITLE
Use 'product' and 'component' features in the models

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#37]
b7369ea8bf282941ce4b378ad5ad3c832db20668 introduced the features, but we are still not using them.

**Comment by pradeepgangwar** [comment]
@marco-c I will try this up. :)

**Comment by marco-c** [comment]
@pradeepgangwar cool, thanks! I would do one PR at a time, one per model. When you make the PR, please write down both the results before adding the features and the results after adding the features.

**Comment by chidauri** [comment]
@marco-c can i take this issue? I am contributing for the first time.

**Comment by marco-c** [comment]
Sure. As described at https://github.com/mozilla/bugbug#contributing, any issue that is open and has no PR linked to it can be considered unassigned.

**Comment by chidauri** [comment]
Hi @marco-c ,i,ve made some changes to use these features, how do i know if these features are being used now and i,ve done things correctly?

**Comment by marco-c** [comment]
Train the model to which you have added the feature before and after adding the feature, and see if there's any change in the metrics.

**Comment by chidauri** [comment]
Hey @marco-c ,  i checked the change in metrics for different models,and found significant change in only bug model.can i make PR?

**Comment by marco-c** [comment]
Sure, but please attach here one text file per model showing your results before/after.

**Comment by chidauri** [comment]
[bug_model.txt](https://github.com/mozilla/bugbug/files/2908732/bug_model.txt)
This is for bugmodel,like this for all?

**Comment by marco-c** [comment]
Yes, thanks!

**Comment by chidauri** [comment]
[qaneeded_model.txt](https://github.com/mozilla/bugbug/files/2910937/qaneeded_model.txt)
Here is the 'qaneeded' model, no changes at all. I think the rest of the models don't need to use these features and some are already using. So should i only implement this for 'bug' model? 
And Thank you @marco-c  :)

**Comment by marco-c** [comment]
OK, sounds good!
