### ISSUE TITLE
MEI: Adjust the weight for untriaged bugs to 3

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugbug#3712]
Based on [this doc](https://docs.google.com/document/d/1nWP3DtSWneYT8ietXuBa6uPszMKMgICXf3b2dwMVXYk/edit#heading=h.9joq5dbpnw41).

Currently untriaged defects have a weight of 5. While it is true that triaging should have a high priority, it is unlikely that many of those defects will end up being S1 or S2.

Furthermore we already used 3 for old severity values, which are most likely to be considered equally untriaged (and have become rare anyways, it seems).

Recap of the resulting weights:

S1: 8
S2: 5
untriaged/old severity: 3
S3: 2
S4: 1

**Comment by marco-c** [comment]
> and have become rare anyways, it seems

There should be basically 0, as we migrated the old values to the new ones recently (there might be 1 or 2 because of intermittent bugs that were closed at the time we did the migration and reopened after we did the migration).
