### ISSUE TITLE
MEI: Have a measure of incoming/closed defects vs. existing open

### ISSUE THREAD

**Issue by jensstutte** [mozilla/bugbug#3715]
Based on [this doc](https://docs.google.com/document/d/1nWP3DtSWneYT8ietXuBa6uPszMKMgICXf3b2dwMVXYk/edit#heading=h.9joq5dbpnw41).

```
Incoming(TimeInterval) := NumOpenedDefects(TimeInterval) / NumOpenDefects(Start(TimeInterval))
Closed(TimeInterval)  := NumClosedDefects(TimeInterval) / NumOpenDefects(Start(TimeInterval))
```

Given that `NumOpenDefects(Start(TimeInterval))` is hard to query live, we estimate it by:

```
NumOpenDefects(Start(TimeInterval)) := NumOpenDefects(End(TimeInterval)) + NumClosedDefects(TimeInterval) - NumOpenedDefects(TimeInterval)
```

such that if the calculation is run with an end date of the time interval that is close to today we can use the up-to-date values for components and severity without bothering too much for deviations.

**Comment by marco-c** [comment]
@jensstutte two questions:
- should this be made a percentage as well?
- do we want both weighed and non-weighed or only non-weighed? In the doc you mentioned the weighed, while here you mentioned the non-weighed

**Comment by jensstutte** [comment]
I think absolute numbers are easiest to relate to for who knows their backlogs. For the same reason I switched to non-weighed here, the doc needs updating.

**Comment by jensstutte** [comment]
(it might be nice to have links in the mail that open a query showing those bugs?)
