### ISSUE TITLE
Also calculate experience of backed out patches

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#373]
We are ignoring them to calculate experiences for authors and reviewers and previous commits for same files, directories and components.
Maybe we should have a new feature that says the number of previous backouts for the same author (probably doesn't make sense to have it for reviewers, files, directories and components too?).

**Comment by calixteman** [comment]
I think it could be useful in case where a dev has a good experience on a component and even after years he continues to have backed out patches: it probably means that every change here is not trivial at all and if a "newbie" writes a patch here then the probability to have a regression is pretty high.

**Comment by marco-c** [comment]
It could also help in calculating how likely a patch is to be backed out.
