### ISSUE TITLE
Fallback to use the Python API to compress/decompress when the CLI dependency is not installed

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3755]
We use the `zstd` binary in some places instead of `zstandard` for some performance gains. However, this becomes an issue when the `zstd` package is not installed, or the binary location is not listed in `PATH`.

Example of using the `zstd` binary through CLI:
https://github.com/mozilla/bugbug/blob/b6291dc725db9bbf866b0bd304a0b12516ed2b40/bugbug/utils.py#L244-L248

In this case, we should fallback to using `zstandard` API if we fail to compress using `zstdmt` because `zstd` is not installed.

This will solve the following:
- #3708
- #3742

**Comment by marco-c** [comment]
The old code, which was not using zstd, to decompress can be seen in this commit: https://github.com/mozilla/bugbug/commit/c079f0f4a77e24cc2102bdced333bcd5a45096bd.
