### ISSUE TITLE
Use Ruff for linting and formatting

### ISSUE THREAD

**Issue by unna97** [mozilla/bugbug#3767]
Proposal to use[ Ruff ](https://docs.astral.sh/ruff/) for linting and code quality. Due to following reasons:

-  It's faster 
-  Can fix code automatically

**Comment by marco-c** [comment]
I like the idea of using Ruff (though our current linters can already fix code automatically, so that's not going to change).

There is https://github.com/astral-sh/ruff-pre-commit, so the integration should be pretty easy.

**Comment by YBCS** [comment]
hello can I work on this ? @marco-c

**Comment by BaasanbayarOverflow** [comment]
Hello :DD @marco-c , @unna97 
Can I get this one? please

**Comment by suhaibmujahid** [comment]
@BaasanbayarOverflow feel free to work on any issue that is not linked to an open PR.
