### ISSUE TITLE
Change the names for feature extraction classes from Snake Case to Pascal Case

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3779]
The following files contained such classes:
- `bugbug/bug_features.py`
- `bugbug/commit_features.py`
- `bugbug/issue_features.py`
- `bugbug/test_scheduling_features.py`

In the following example, `source_code_file_size` should be renamed to `SourceCodeFileSize`:
https://github.com/mozilla/bugbug/blob/9021149937c62869e7afe76ef8cea05e1a46fa07/bugbug/commit_features.py#L39-L46

**Comment by OscarTienda** [comment]
Hi Suhai, how can I detect which classes are feature extraction classes?
