### ISSUE TITLE
Add tests for repository.get_commit_map

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#378]

**Comment by ayush-1506** [comment]
@marco-c  Is this test is perhaps going to be pretty straight forward? (test the length of the lists for a few random keys in the commit_map?)
(get_commit_map doesn't take any arguments, so there's nothing we can add in there.)

**Comment by marco-c** [comment]
Yes, the test is not going to be hard. The mock DB is already added in https://github.com/mozilla/bugbug/blob/f4b2b938be638533bcdab54ea0d35043d9ee3ff1/tests/conftest.py#L17, so the test function just needs to use the mock_data fixture.

**Comment by marco-c** [comment]
This is no longer needed, as the function was removed in 37f93de33b0bb6523c51b6a65b770998921fef9d.
