### ISSUE TITLE
Add some timing-related information about patches to the bug features

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#38]
These might be useful for the uplift model:
- [x] #3118
- [x] Time delta between uplift request and merge day (we can approximate it with the release date of the next version at the time the uplift was requested) #97

**Comment by marco-c** [comment]
The uplift request time can be retrieved from `when` inside `history`.

The landing of the patch in Nightly can be obtained by retrieving the date from Mercurial commits, or the date of the landing comments (https://github.com/mozilla/libmozdata/blob/0574613cc701eb10adff9ac3fcd422bc6efdd914/libmozdata/bugzilla.py#L313). This one is not so easy.

Merge day can be obtained by looking at the release dates, using https://github.com/mozilla/libmozdata/blob/0574613cc701eb10adff9ac3fcd422bc6efdd914/libmozdata/versions.py#L155.

**Comment by marco-c** [comment]
> For the first, (correct me if I'm wrong), we'll have to retrieve comments from the get_landing_comments method, and use this in versions.getCloserRelease to get the date, right?

One option is to use the `get_landing_comments` method, the other is to use the date of the commit. I guess they are equivalent.

**Comment by RicardormDev** [comment]
I made a PR for the first point on this issue (#1917 )

**Comment by 3qiu** [comment]
Hi @marco-c, I made a PR for the first task at #3118, let me know if this looks good.

**Comment by mathewhodson** [comment]
@marco-c It looks like this can be closed since code for both tasks were merged.

**Comment by suhaibmujahid** [comment]
Thank you, @mathewhodson!
