### ISSUE TITLE
Try out categorical mode with xgboost

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#3817]
See https://xgboost.readthedocs.io/en/stable/tutorials/categorical.html.

**Comment by gothwalritu** [comment]
Hello marco-c! I am interested in this issue. Could you please share more details on this?

**Comment by marco-c** [comment]
@gothwalritu it might be nice to continue with #3717 since it looks like you're close to completion.

If you want to explore this too, you could pick one of the models already implemented in bugbug/models, and try to use the https://xgboost.readthedocs.io/en/stable/tutorials/categorical.html.
You'd need to convert the categorical features to actually be categorical by doing `.astype("category")`, and then enable the functionality by passing `enable_categorical=True` to the XGBoost classifier constructor.

You can convert features to categorical in https://github.com/mozilla/bugbug/blob/c598ee7ef2e09556f9b308bf6a99a876505c870b/bugbug/bug_features.py#L601. We need to find a nice way to do it, but for testing you could just do it column by column on the dataframe here https://github.com/mozilla/bugbug/blob/c598ee7ef2e09556f9b308bf6a99a876505c870b/bugbug/bug_features.py#L689.

**Comment by gothwalritu** [comment]
Yes, I will close #3717 first. I just wanted to get myself acquainted with this one in the meantime. Thanks for your reply. BTW Happy New Year!!

**Comment by marco-c** [comment]
@gothwalritu happy new year to you too!

**Comment by suhaibmujahid** [comment]
Duplicate of #2819

@PromiseFru thank you for reporting this!

@gothwalritu you can work on #2819 instead since it is the original issue.
