### ISSUE TITLE
Comply with logging-fstring-interpolation / W1203

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3820]
Some logging statements aren't complying with [logging-fstring-interpolation / W1203](https://pylint.readthedocs.io/en/latest/user_guide/messages/warning/logging-fstring-interpolation.html). 

Examples:
 
https://github.com/mozilla/bugbug/blob/d454491af97ae42256f9e7960c560b1f7e4eca97/bugbug/models/browsername.py#L72-L76

https://github.com/mozilla/bugbug/blob/d454491af97ae42256f9e7960c560b1f7e4eca97/scripts/regressor_finder.py#L342-L344

**Comment by sreeroop10** [comment]
Hello, can I please work on this issue ?

**Comment by suhaibmujahid** [comment]
@sreeroop10 thank you for your interest! Unfortunately, the Issue already has an open pull request to address it. The issue will be available again only if the pull request gets closed without being merged.

Feel free to choose any other issue. The ones with the [good-first-bug](https://github.com/mozilla/bugbug/labels/good-first-bug) label are a good start.
