### ISSUE TITLE
Add tests for repository.get_commits

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#383]

**Comment by madhurish** [comment]
Hi, wanted to work on this. Have a few queries /clarifications, would be great if I can get some guidance.
1. This issue requires tests to be written for get_commits() method in bugbug/repository.py, correct?
2. The tests for bugbug/repository.py have to be written in test/test_repository.py, correct?
3.  So since the get_commits() method is returning the content of the database(?), what are some test cases that are expected to test this method (looking for some example scenarios).

**Comment by marco-c** [comment]
> This issue requires tests to be written for get_commits() method in bugbug/repository.py, correct?

Yes.

> The tests for bugbug/repository.py have to be written in test/test_repository.py, correct?

Yes.

> So since the get_commits() method is returning the content of the database(?), what are some test cases that are expected to test this method (looking for some example scenarios).

You can just add a simple test case that calls the method and asserts that the right commit is returned (you can check that its node property corresponds to the right one).
Tests are using the mock files from tests/fixtures, so in this case tests/fixtures/commits.json.

**Comment by madhurish** [comment]
Thanks for the clarifications, seems pretty straight forward, will be raising a PR soon. Is there any branching strategy that is being followed that I need to know about before making a PR?

**Comment by marco-c** [comment]
> Is there any branching strategy that is being followed that I need to know about before making a PR?

Just the usual workflow on GitHub. You create a fork, a branch in your fork, then create a PR in this repo from your branch in your fork.

**Comment by madhurish** [comment]
Hi, I'm trying to run the test but not able to see any test results, I think I'm missing something, here are the steps I followed:
1. I created a virtualenv and installed requirements.txt and test-requirements.txt
2. Copied the bugbug directory inside the test directory
3. Ran the python script (without making any changes): python test_repoitory.py

The script executed successfully without any errors, it didn't tell me how many test cases passed/failed
I changed the values in a couple of assert statements but still ran without any error.
Am I missing something? What's correct way to write my tests and verify them?

**Comment by madhurish** [comment]
Here's what I did:
1. Created a virtual environment, installed the requirements and test-requirements 
2. Copied the bugbug directory into the tests directory
3. Ran pytest

I got an error in the test_repository.py, is that expected output? Should I go ahead and add the tests? Or am I doing something wrong?

**Comment by marco-c** [comment]
You don't need to copy the bugbug directory into the tests directory.
Simply running `python3 -m pytest tests/test_repository.py` should work.

> is that expected output?

If you don't paste the output here, it's going to be hard for me to tell you whether that output is expected :P

**Comment by madhurish** [comment]
![Screenshot from 2019-05-15 22-58-26](https://user-images.githubusercontent.com/33370824/57796051-12a95400-7765-11e9-9ebc-88223f6d2218.png)
![Screenshot from 2019-05-15 22-58-39](https://user-images.githubusercontent.com/33370824/57796053-12a95400-7765-11e9-967f-29bbca9f6ee2.png)
Added screenshots : ```FileNotFoundError: [Errno 2] No such file or directory: 'hg': 'hg'

/usr/lib/python3.6/subprocess.py:1344: FileNotFoundError
========================================================= 2 passed, 1 error in 0.14 seconds ==========================================================
```

**Comment by hotdogman** [comment]
This error comes from trying to call the /usr/bin/hg command, but you do not appear to have mercurial installed.

**Comment by marco-c** [comment]
@hotdogman is right, installing Mercurial is a requirement for the project.

**Comment by madhurish** [comment]
Haha, yeah finally got it working. I guess a few things can be updated in the documentation like running tests and the Mercurial dependency. I might have missed it, if it is already mentioned somewhere let me know if it is. also opened an PR with a basic test, will add more let me know: #447

**Comment by peterchou3788** [comment]
Hello Marco,
If this bug is still open and unassigned, mind if I attempt it?

**Comment by marco-c** [comment]
Yes, of course, no need to ask!

**Comment by marco-c** [comment]
@peterchou3788 can you post a log of the command you are running and the result of the command?

**Comment by marco-c** [comment]
Open an issue in the rs-parsepatch repo (https://github.com/mozilla/pyo3-parsepatch) though, as this is not the right place to discuss that.

**Comment by Sujay-Tandel** [comment]
Can I work on this fix?

**Comment by Sujay-Tandel** [comment]
Hello Marco,
If this bug is not assigned, can I attempt it as my first bug?

**Comment by trulyness** [comment]
Is this issue still open? If yes, then can I work on this?

**Comment by marco-c** [comment]
No need to ask, you can work on any issue that has no open PR linked to it.
