### ISSUE TITLE
Optimize the `bug_to_types()` functions to avoid redundant the execution of string lowering

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3845]
The `bug["whiteboard"].lower()` statement is performed multiple times in the function. Instead, we could store the lowercase value in a variable (e.g., `bug_whiteboard`) and reuse it where needed.

Examples:

https://github.com/mozilla/bugbug/blob/0586c6a49732f03781daf43d8726b53e2049e3db/bugbug/models/bugtype.py#L46

https://github.com/mozilla/bugbug/blob/0586c6a49732f03781daf43d8726b53e2049e3db/bugbug/models/bugtype.py#L50

**Comment by sreeroop10** [comment]
Hello @suhaibmujahid , Could I please work on this issue ?

**Comment by suhaibmujahid** [comment]
> Could I please work on this issue ?

@sreeroop10 Yes, you could work on any issue that does not have an open PR linked to it.

**Comment by suhaibmujahid** [comment]
We still have one case, which was added in #3823 (after closing this issue):
https://github.com/mozilla/bugbug/blob/56822b33d6d8560976648c6d971de131f935d8ca/bugbug/models/bugtype.py#L65
