### ISSUE TITLE
Use `... | None` instead of `Optional[...]`

### ISSUE THREAD

**Issue by suhaibmujahid** [mozilla/bugbug#3856]
> We should make it more consistent. We could use `... | None` instead of `Optional[...]`.

_Originally posted by @suhaibmujahid in https://github.com/mozilla/bugbug/pull/3855#discussion_r1405206846_

**Comment by theoniko** [comment]
Hello @suhaibmujahid,
Could i work on this issue? 
Could you please exlain me why revs: list[bytes] | None = None is better than revs: Optional[list[bytes]] = None? 
They seem to have similar effect to me i.e list of bytes or None. Is just for consistancy in code?

**Comment by suhaibmujahid** [comment]
> Could i work on this issue? 

Yes!

> Could you please exlain me why revs: list[bytes] | None = None is better than revs: Optional[list[bytes]] = None?
> They seem to have similar effect to me i.e list of bytes or None. Is just for consistancy in code?

Yes, they are equivalents. The main reason is consistency. Also, `Optional[]` is a bit annoying because it requires to be imported.
