### ISSUE TITLE
worksforme model training task is failing (probably OOM)

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#4095]
https://community-tc.services.mozilla.com/tasks/TOyLl-ubQwehM8liNwtRdA/runs/0

**Comment by PromiseFru** [comment]
> https://community-tc.services.mozilla.com/tasks/TOyLl-ubQwehM8liNwtRdA/runs/0

Oh, the training was successful on [TC](https://github.com/mozilla/bugbug/runs/22254262828). Perhaps I should try the `compute-large` worker?

**Comment by marco-c** [comment]
Yeah, let's try that!
