### ISSUE TITLE
No results when adding feature meta bugs ID to bugbugUI

### ISSUE THREAD

**Issue by mboldan1** [mozilla/bugbug#4227]
Steps:
1. Go go bugbugUI. 
2. Make sure that 'Choose the feature meta bug' option is selected.
3. Add a bugzilla ID from e metabug (eg.1888645)

Expected:
All the needed information related to the meta bug ID is displayed. 

Actual:
Nothing is displayed.

**Comment by marco-c** [comment]
@mboldan1 bug 1888645 is not a meta bug, that's why it can't find any blocking bugs for it (https://bugzilla.mozilla.org/show_bug.cgi?id=1888645).

**Comment by mboldan1** [comment]
Hi @marco-c ! That was just an example. Here are a few more examples of meta bugs with no results in bugbugUi:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1894024
- https://bugzilla.mozilla.org/show_bug.cgi?id=1889038
- https://bugzilla.mozilla.org/show_bug.cgi?id=1882607

**Comment by marco-c** [comment]
@mboldan1 we only consider open bugs that are feature-meta-bugs.

https://bugzilla.mozilla.org/show_bug.cgi?id=1894024 and https://bugzilla.mozilla.org/show_bug.cgi?id=1889038 are closed.

https://bugzilla.mozilla.org/show_bug.cgi?id=1882607 is open, but it doesn't have the feature-meta-bug keyword.

We can relax the conditions if needed to include more feature-meta-bugs. E.g. we could include closed ones if they were closed recently.

**Comment by mboldan1** [comment]
Hi @marco-c ,
Since it's possible, we would like to have the conditions more relaxed in order to receive results for the closed bugs too, bugs that have included the feature-meta-bug keyword.

**Comment by marco-c** [comment]
@mboldan1 after #4271 lands and is deployed, you'll start to see closed feature meta bugs too (if they have received any update within the last 90 days). Let me know if you want to extend the time from 90 days to even more.
