### ISSUE TITLE
Add stepstoreproduce training task

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#427]

**Comment by ayush-1506** [comment]
@marco-c What is a training task in this context? Is there an example of this for some other model?

**Comment by marco-c** [comment]
[Taskcluster](https://docs.taskcluster.net/docs) runs our pipeline, which is defined in infra/data-pipeline.yml. Each item of that YAML file defines a task that is run on Taskcluster. A training task is a task that performs the training of a model.

Here is an example for the component model: https://github.com/mozilla/bugbug/blob/73a5192073ed6e805afc7cadc8143d68db5c38ef/infra/data-pipeline.yml#L88, with the Docker image defined at https://github.com/mozilla/bugbug/blob/73a5192073ed6e805afc7cadc8143d68db5c38ef/infra/dockerfile.train_component#L1.
