### ISSUE TITLE
Add some basic tests for the steps to reproduce model

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#428]

**Comment by sladyn98** [comment]
@marco-c I would like to work on this could you guide me a bit. Thanks

**Comment by marco-c** [comment]
Hello @sladyn98, this will be something similar to https://github.com/mozilla/bugbug/blob/1bae5834abd49f70c69da84d36b66f5f5cf503b0/tests/test_tracking.py, for the StepsToReproduce model (https://github.com/mozilla/bugbug/blob/master/bugbug/models/stepstoreproduce.py).

**Comment by sladyn98** [comment]
@marco-c Kindly review :)

**Comment by marco-c** [comment]
Fixed by #503.
