### ISSUE TITLE
Add basic tests for backout model

### ISSUE THREAD

**Issue by ayush-1506** [mozilla/bugbug#432]

**Comment by subhamkrai** [comment]
Hi, I would like to work on this issue. I'm newbie please help I can I get started with this issue.

**Comment by marco-c** [comment]
Hello @subhamkrai, this will be somewhat similar to https://github.com/mozilla/bugbug/blob/1bae5834abd49f70c69da84d36b66f5f5cf503b0/tests/test_tracking.py, for the Backout model (https://github.com/mozilla/bugbug/blob/master/bugbug/models/backout.py). The main difference is that the Backout model operates on commits rather than bugs.

**Comment by subhamkrai** [comment]
@marco-c  can you describe this. I'm new to this open source contribution.

**Comment by ayush-1506** [comment]
@subhamkrai What needs to be done is described in the comment above. To know more about open source in general, please go through https://medium.com/@jenweber/your-first-open-source-contribution-a-step-by-step-technical-guide-d3aca55cc5a6

**Comment by probaku1234** [comment]
I'm trying to implement test function for backout model but, get_labels() function gives me error
```
def get_labels(self):
        classes = {}
    
        for commit_data in repository.get_commits():
>           classes[commit_data["node"]] = 1 if commit_data["ever_backedout"] else 0
E           KeyError: 'node'
```
I'm guessing this is because there is no key 'node' in commits.json file.
Any suggest?

**Comment by marco-c** [comment]
The mock file in tests/fixtures/commits.json was not updated to add "node" when we added it as a key. You can do it by doing, for each commit in tests/fixtures/commits.json:
1. Take the bug ID from the "desc" field
2. Open https://bugzilla.mozilla.org/show_bug.cgi?id=BUG_ID
3. Find the commits from the bug comments (open all links starting with `https://hg.mozilla.org`)
4. Check which commit corresponds to the one you selected
5. Add the revision of the commit to the relevant line in tests/fixtures/commits.json

**Comment by probaku1234** [comment]
What is the 'revision' exactly?

**Comment by marco-c** [comment]
I guess you figured it out ;)
