### ISSUE TITLE
Add basic tests for component model

### ISSUE THREAD

**Issue by ayush-1506** [mozilla/bugbug#433]

**Comment by sumit4613** [comment]
@ayush-1506 I am new to open source contribution . This issue is not closed yet . Can I take up this issue .

**Comment by ayush-1506** [comment]
Sure. You can take up any issue that doesn't have a PR open against it.

**Comment by Purnika41** [comment]
This issue is still open. May I take up this issue?

**Comment by ayush-1506** [comment]
Yep, sure. Feel free to work on this. (As I mentioned above, you can work on any issue that doesn't have a PR open against it.)

**Comment by Purnika41** [comment]
@ayush-1506 While setting up the repo, I am facing a File-not-found error. 
FileNotFoundError: [Errno 2] No such file or directory: 'defectmodel'
I am unable to figure out where this error is occurring.

**Comment by ayush-1506** [comment]
`python run.py --train --goal=defect` will download the entire DB and save the model.

**Comment by Purnika41** [comment]
Thanks !!

**Comment by harsh020** [comment]
@ayush-1506 I'm a complete beginner in open source, will it be alright if I try to fix this bug.
And I would be very grateful if you helped me a bit as I'm trying to contribute to open source for over an year but every time I open a bug, I'm lost. I would be great pain but please bear with me and help me solve my first bug.

**Comment by ayush-1506** [comment]
Sure, go ahead. For this particular bug you can take inspiration from #607. You may also join the #bugbug channel on mozilla-irc to know more.

**Comment by ayush-1506** [comment]
There's actually a PR open for this. But feel free to take up any other issue. You may also join the #bugbug channel on mozilla-irc.

**Comment by Purnika41** [comment]
@ayush-1506 I am facing this error while running the train.py script:
-c: error: the following arguments are required: model

**Comment by ayush-1506** [comment]
@Purnika41 You need to specify the model too. For example `python -c 'from scripts import trainer; trainer.main()' duplicate` to train the duplicate model.

**Comment by Purnika41** [comment]
@ayush-1506 thanks!

**Comment by dotslash21** [comment]
Hi! @ayush-1506, I'm new to the open-source contribution, can I give this a try?

**Comment by ayush-1506** [comment]
Sure, there isn't a PR open against this issue, so feel free to take this up. 👍

**Comment by alfarhanzahedi** [comment]
Hi @ayush-1506 
I would like to work on this issue. I have cloned the repository and have already got a little bit of hang of the `ComponentModel`. 
To start, I have successfully written a trivial test for `is_meaningful()` method. I will next  (from taking up hints from other tests) try to write tests for the remaining methods. Should I continue?

**Comment by marco-c** [comment]
> Should I continue?

Sure, why not? :P

**Comment by alfarhanzahedi** [comment]
Okay! :) 
As mentioned in this comment - https://github.com/mozilla/bugbug/pull/682#issuecomment-511146279, I am also getting the same error - `AssertionError: There should be at least one bug matching Core::IPC at L-166 in models/component.py` on running the following set of simple statements -
```python
def test_get_component_labels():
    model = ComponentModel()
    classes, _ = model.get_labels()
``` 
Should I modify `tests/fixtures/bugs.json` to include a bug matching `Core::IPC`? If yes, then is there any rules/template that should be followed while creating the mock data, or is it all just random? 
If no, then what should be my next step here?

**Comment by marco-c** [comment]
You might need somehow to reduce the current checks done by the component model, otherwise you have to increase the fixture DB by a lot.
