### ISSUE TITLE
Fenix component model should include GeckoView too

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#4355]
As GeckoView could be considered part of Fenix.

**Comment by benjaminmah** [comment]
In this already merged [PR](https://github.com/mozilla/bugbot/pull/2399/files), I implemented a strategy to reclassify bugs using the Fenix model after being passed through the general component model. I assume upon merging this PR, we would have to alter our strategy, as the Fenix model can also classify bugs to be GeckoView. Does that sound correct @marco-c?

**Comment by marco-c** [comment]
Yes, that's correct!
