### ISSUE TITLE
Add basic tests for uplift model

### ISSUE THREAD

**Issue by ayush-1506** [mozilla/bugbug#437]

**Comment by bezoka** [comment]
I will try implement test for that

**Comment by pavitrawalia** [comment]
I am new to open source contribution . This issue is not closed yet . Can you provide me some insights regarding the issue

**Comment by ayush-1506** [comment]
You can take inspiration from #606.

**Comment by kanurag94** [comment]
Hi @ayush-1506 , Can you help me with why #693 is failing?
