### ISSUE TITLE
Add basic tests for defect_enhancement_task model

### ISSUE THREAD

**Issue by ayush-1506** [mozilla/bugbug#438]

**Comment by hmrishavbandy** [comment]
Can you please assign this issue to me? Ma a noobie and would like some help alongside my contribution

**Comment by marco-c** [comment]
@hmrishavbandy issues are assigned only when there is a PR open to fix them. You can feel free to work on any issue which you see unassigned and for which there is no PR linked, there is no need to be assigned first.

**Comment by marco-c** [comment]
In order to fix this issue, you'll need to do something really similar to https://github.com/mozilla/bugbug/blob/master/tests/test_tracking.py, but for the defect/enhancement/task model.

**Comment by hmrishavbandy** [comment]
@marco-c thanks a lot.. I'll be working on this now

**Comment by hmrishavbandy** [comment]
Can anyone please elaborate on what is meant by "basic" tests in here?I am getting the concept of tests with respect to the model specified but  what tests are classfied as basic tests? Thanks for your help!

**Comment by marco-c** [comment]
@hmrishavbandy see my previous comment, it contains an example of a basic test.

**Comment by hmrishavbandy** [comment]
@marco-c I am probably slow, but tests as in using assert? If that is so , then in https://github.com/mozilla/bugbug/blob/master/tests/test_tracking.py , I didn't get the place where you use the numbers in the square brackets. Thanks for your patience !

**Comment by marco-c** [comment]
@hmrishavbandy you are going to have to investigate a bit yourself, that's the nice part :P

**Comment by hmrishavbandy** [comment]
oh! Okay... I'll surely give my best :smile:
