### ISSUE TITLE
Use zstandard instead of xz

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#461]
We should compare the compression ratios and, if the difference is small, switch to zstandard.

**Comment by marco-c** [comment]
This is pretty simple.
1. Download the bugs.json.xz file (from https://index.taskcluster.net/v1/task/project.relman.bugbug.data_bugs.latest/artifacts/public/bugs.json.xz), extract it, compress it with zstandard. Compare the sizes of the extracted file vs the xz file vs the zstandard file.
2. Perform the same steps with one of the model files (e.g. https://index.taskcluster.net/v1/task/project.relman.bugbug.train_defectenhancementtask.latest/artifacts/public/defectenhancementtaskmodel.xz).

**Comment by x249wang** [comment]
Here's what I got for the relative file sizes:

| (in KB) | Original  | .xz     | .zst    |
|---------|-----------|---------|---------|
| bugs    | 1,370,732 | 152,193 | 154,090 |
| model   | 67,906    | 39,432  | 41,567  |

I'm using the Windows release of Zstandard v1.4.0, using compression level of 19 (results in smallest file sizes). 

Is the difference considered small enough?

**Comment by marco-c** [comment]
Could you try with the default compression level too?

**Comment by x249wang** [comment]
With default compression level (i.e. 3):

| (in KB) | Original  | .xz     | .zst    |
|---------|-----------|---------|---------|
| bugs    | 1,370,732 | 152,193 | 152,196 |
| model   | 67,906    | 39,432  | 39,433  |

Much closer than previously.

**Comment by marco-c** [comment]
OK, thanks! So we can definitely switch to zstandard.

**Comment by x249wang** [comment]
Sounds good. I can get started with that.

**Comment by x249wang** [comment]
@marco-c I found two instances of the `compress_file()` function being called (`commit_retriever.py`, `bug_retriever.py`), which I can update, but it seems that all the .xz-format model files are downloaded from taskcluster?

**Comment by marco-c** [comment]
> @marco-c I found two instances of the compress_file() function being called (commit_retriever.py, bug_retriever.py), which I can update, but it seems that all the .xz-format model files are downloaded from taskcluster?

Yes, they are downloaded from Taskcluster, but the code to upload to Taskcluster is also in this repository.
You'll need to update both the upload and the download code.
To catch all uses, you can simply `grep "xz" -r scripts/ bugbug/ infra/`.

**Comment by x249wang** [comment]
Upon second try, it seems the .zst files under default compression level are much larger than what I reported before. Really sorry!! Not sure what happened there...

| (in KB) | Original  | .xz     | .zst    |
|---------|-----------|---------|---------|
| bugs    | 1,370,732 | 152,193 | 228,711 |
| model   | 67,906    | 39,432  | 44,856  |

**Comment by marco-c** [comment]
No worries, the size is still small enough (and we save time with zstd, so it's better).
