### ISSUE TITLE
Component model check fails because a component doesn't exist (but it does)

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#478]
https://tools.taskcluster.net/groups/YmP0E_pwSuSdoagf1-CqGw/tasks/ArfJiFK0Q--CVZSNei8ieA/runs/0/logs/public%2Flogs%2Flive.log failed with:
```
Component 'Application Panel' of product 'DevTools' doesn't exists, failure
```

But this component actually exists.

**Comment by Lothiraldan** [comment]
I think the issue is that their was no issue in the last 6 months for this component

**Comment by marco-c** [comment]
You're right, it was a good failure actually. With the new component model it is not failing anymore.
