### ISSUE TITLE
Remove one-patch author at some point to free memory

### ISSUE THREAD

**Issue by calixteman** [mozilla/bugbug#485]
Algo:
 - in a first step: get max pushdate for author
 - in the main analysis loop, remove this author from the dict when the current date exceeds the max one

**Comment by marco-c** [comment]
We could do the cleanup every X commits, so we don't spend too much time.

**Comment by marco-c** [comment]
Actually, for each commit, we could do the check for the author (reviewer, etc.) of that commit.
