### ISSUE TITLE
Rename spawn_data_pipeline.py to spawn_pipeline.py

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#490]
Since it supports spawning both data and check (or any other pipeline defined in a yaml file).

**Comment by stardust3dd** [comment]
can I claim this issue?

**Comment by marco-c** [comment]
Sure!

**Comment by stardust3dd** [comment]
is changing the name enough or do I have to make other relevant changes?

**Comment by marco-c** [comment]
Just need to rename the file and update all places which are referencing it.

**Comment by hmrishavbandy** [comment]
Hey, I completed this. Shall i create a branch and and then create a Pull Request?

**Comment by marco-c** [comment]
Yes.

**Comment by hmrishavbandy** [comment]
I'm getting this error:
"remote: Permission to mozilla/bugbug.git denied to hmrishavbandy." ,
when i am trying to push my changes. I am using the terminal and am on Ubuntu 19.04.

**Comment by marco-c** [comment]
You need to push them to your fork, not to the upstream repository.

**Comment by hmrishavbandy** [comment]
Thanks a lot @marco-c  for all this help. You helped make this fun :D

**Comment by hzk120** [comment]
@marco-c  Can I take up this issue,since there is no PR for it?

**Comment by pavitrawalia** [comment]
marco-c  I am new to open source contribution . This issue is not closed yet . Can I take up this issue .

**Comment by mdl2000** [comment]
@marco-c I am new to open source contribution, and as this issue is not closed yet. Can I take this?

**Comment by championshuttler** [comment]
Hi All its weekend so Marco most probably is on leave, @hzk120 please go ahead and make the PR if you need any help comment here :)

**Comment by Patil2099** [comment]
@marco-c  If this issue is still open. Can I work on it ?

**Comment by marco-c** [comment]
@Patil2099 read CONTRIBUTING.md. You can work on any open issue which has no PR linked to it.
This one doesn't have a open PR linked to it, so it's not assigned.
