### ISSUE TITLE
Change hg_log chunksize

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#492]
@calixteman noticed that, for a small number of revs, chunksize=1 is faster. We should check if that is the case for all revs too.
Maybe we can find an optimal value of chunksize which would be != 20 and != 1.

**Comment by marco-c** [comment]
The same might apply to _transform chunksize.

**Comment by marco-c** [comment]
On my machine it didn't make any difference :(

**Comment by calixteman** [comment]
At least for the first step, we should have chunksize=ceil((number of chunks)/(number of cpus)).
It'd helpful especially when debugging.
20 is probably not good because it doesn't rely on the machine where stuff is running.

**Comment by marco-c** [comment]
I tried again today and without chunksize it was twice as fast, pretty weird...

**Comment by marco-c** [comment]
Fixed by 0e43fb69a2fe09b45531c15fad932b4d1a4fa6e1 (#737).
