### ISSUE TITLE
Add DB versioning

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#51]
When a new DB is available, it should automatically be downloaded.

**Comment by sbeesm** [comment]
We also need to add last-modified field to the dropbox link headers, right?

Then maybe we can compare timestamps of the existing DB in the file directory and the one on the server?

**Comment by marco-c** [comment]
We can just add a file containing the version alongside the DB files, that's the easiest solution.

**Comment by sbeesm** [comment]
But this would always require to download the DB (along with the version file) first and then check with the existing version.

**Comment by marco-c** [comment]
> But this would always require to download the DB (along with the version file) first and then check with the existing version.

Not really, it would just require downloading the version file.

Anyway, I've noticed that Dropbox returns an ETag in the headers, so we could just check the ETag before downloading (if it's the same as the previous one, we don't download, if it is different, then we download).

Thinking about it though, I prefer to avoid any kind of connection on every run. So I'd just add a version file for each database in the repository itself. We will have to remember to update them whenever we update the DBs.

**Comment by sbeesm** [comment]
So in `db.download()`, we can add a version file along with the database in the repository and then in `run.py`, we can check the version and download the DB if necessary?

**Comment by marco-c** [comment]
Yes

**Comment by marco-c** [comment]
Basically:
- we'd have a VERSION file for each DB in the repo;
- when downloading a DB, we save the current version in another file locally;
- when we run, we check that the VERSION from the repository is the same as the local version file.
