### ISSUE TITLE
Add options to the Duplicate classifier to select number of bugs in the training set

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#521]

**Comment by chidauri** [comment]
https://github.com/mozilla/bugbug/blob/5b367e2107c0382b861133643d9aca6c6d1e0f24/bugbug/models/duplicate.py#L17-L19
@marco-c  we can do this by changing the values of these three parameters, is there something else to it?

**Comment by marco-c** [comment]
@chidauri right now it's configurable only by changing those numbers in the source code. We need to somehow make it configurable more easily so you can run the model with different options without having to modify the source.
