### ISSUE TITLE
Add tests for repository.download_component_mapping

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#535]
This test will have to use `responses`, similarly to the test for repository.download_commits.

**Comment by codingisbliss** [comment]
Hello macro-c I want to contribute to this bug. I am a newbie to this, how can I get some reading material/ what this code does inforamtion ?

**Comment by marco-c** [comment]
Hello @codingisbliss, this method is pretty much self-contained. It is here: https://github.com/mozilla/bugbug/blob/ff5eba38322593f3a9c186b6da64e704ea0ab2a4/bugbug/repository.py#L645.
Here's an example of another test for another method which had to mock the download of the component mapping: https://github.com/mozilla/bugbug/blob/master/tests/test_repository.py#L244.

You will have to do something similar, but mocking the download in different ways to test all possible cases.
