### ISSUE TITLE
Upgrade to Mercurial 5

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#549]
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1545236.

**Comment by calixteman** [comment]
Everything is fine with an up-to-date vct and mercurial 5.1.

**Comment by marco-c** [comment]
We need to actually do the change in https://github.com/mozilla/bugbug/blob/5c848def12d596bd2a8a44425ff781f1d616680c/.taskcluster.yml#L91 and https://github.com/mozilla/bugbug/blob/5c848def12d596bd2a8a44425ff781f1d616680c/infra/dockerfile.commit_retrieval#L9.
