### ISSUE TITLE
Don't put VERSION in the env of the tasks

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#570]
We can directly render the tag where needed with JSON-e.

**Comment by marco-c** [comment]
Related to #558.

**Comment by Lothiraldan** [comment]
I'm guessing you are speaking about https://github.com/mozilla/bugbug/blame/master/.taskcluster.yml#L128 and not https://github.com/mozilla/bugbug/blame/master/.taskcluster.yml#L299

**Comment by marco-c** [comment]
I was thinking about the second, we should be able to replace $VERSION with {$eval: 'head_branch[10:]'}, no?

**Comment by Lothiraldan** [comment]
Yes we can, I have put the version in the env to not pollute the command list with the templating
