### ISSUE TITLE
Get bug data all at once instead of attachments and comments separately

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#573]
Using the feature from https://github.com/mozilla-bteam/bmo/pull/1148.

**Comment by sladyn98** [comment]
@marco-c This looks like a good issue to work on :)
Could I try it ?

**Comment by marco-c** [comment]
Sure! The function to modify is https://github.com/mozilla/bugbug/blob/master/bugbug/bugzilla.py#L107.
You need to make sure it behaves the same before/after your change. Choose a bug number, e.g. 1405567, try to download it before and after your change and make sure the data is the same.

**Comment by sladyn98** [comment]
If I understand correctly I need to make a request to the api 
`requests.get("https://bugzilla.mozilla.org/rest/bug/[ID]?include_fields=attachments,comments", params=bug_query_params)`
and then return the list of bugs

**Comment by sladyn98** [comment]
cc @marco-c

**Comment by marco-c** [comment]
Yes, making sure the same data is returned as the current `bugzilla.get` function.

**Comment by sladyn98** [comment]
https://github.com/mozilla/bugbug/pull/596
Opened a draft pr

**Comment by marco-c** [comment]
Unfortunately it seems we can't do this. Bugzilla would return the attachment's data too, which is really big and would slow down our requests.
