### ISSUE TITLE
Use some bug features too in the backout model

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#577]
We need to check if it can improve accuracy.

Depends on #514.

**Comment by marco-c** [comment]
Example features that we could try out: product, component, priority, has_regression_range, has_crash_signature, keywords, severity, number of bug dependencies, number of blocked bugs, whiteboard, bug type.

**Comment by marco-c** [comment]
In order to do this, we will also have to download all bugs associated to the commits we are going to train on.

**Comment by chidauri** [comment]
https://github.com/mozilla/bugbug/blob/50575e270275637f8514b2d9a68bd859e27d0060/bugbug/model.py#L265-L269
We just need to check if every bug in ("all_bug_ids" from above) is present in bugzilla.get_bugs() or download them , right?

**Comment by marco-c** [comment]
Yes, we need to do something like that in the `get_all_bug_ids` function of the labels module.

**Comment by chidauri** [comment]
I didn't find any changes in accuracy or any metric. I downloaded 100,000 bugs approx .

**Comment by marco-c** [comment]
@chidauri which features did you try?

**Comment by chidauri** [comment]
@marco-c product, component, has_regression_range, has_crash_signature, keywords, severity, whiteboard.

**Comment by marco-c** [comment]
Can you try with all the features I listed above?

**Comment by marco-c** [comment]
Could you submit the PR anyway, so we have a track of what happened.
