### ISSUE TITLE
Deployment of each worker is not atomic on heroku

### ISSUE THREAD

**Issue by Lothiraldan** [mozilla/bugbug#591]
With current deployment, each heroku worker is deployed separately, which makes it harder to rollback and could create some bugs. We should deploy all the workers at the same time.

**Comment by Lothiraldan** [comment]
It seems that Heroku doesn't limit the name or number of worker type (besides requiring a web worker), so we cannot declare all of the worker names in task-boot cli.py. See https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-multiple-images for example.

We need to either allow complex value as CLI arguments `worker:/path/to/image.tar` or environment variables.

**Comment by Lothiraldan** [comment]
I have create a PR with a proposed CLI API: https://github.com/mozilla/task-boot/pull/46

With this PR, we could deploy all the workers atomically using the following command:

```
taskboot deploy-heroku --heroku-app bugbug "web:public/bugbug/bugbug-http-service.tar" "worker:public/bugbug/bugbug-http-service-bg-worker.tar"
```

Let me know what do you think about the new API @La0

**Comment by La0** [comment]
Looks good to me, i left some comments on the PR. I'll release 0.2.0 after it lands
