### ISSUE TITLE
Don't try to find inconsistencies in all bugs multiple times

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#593]
We are re-downloading inconsistent bugs at https://github.com/mozilla/bugbug/blob/cc9c5e8c5d69e2dcabf35741a3f1d9b9bb797b39/scripts/bug_retriever.py#L61.

To find them, we are iterating through all bugs.

It makes sense to iterate through all bugs the first time, but the second time we should only iterate through the bugs we found inconsistent the first time (indeed, we can be sure that all the other bugs were not inconsistent).

To fix this, we simply need to modify https://github.com/mozilla/bugbug/blob/cc9c5e8c5d69e2dcabf35741a3f1d9b9bb797b39/bugbug/bug_snapshot.py#L755 adding a "bugs" parameter, and call it in the right way in bug_retriever.py (the first time bugs=bugzilla.get_bugs(), the second and following times bugs=previously_inconsistent_bugs).

**Comment by Abhi-khandelwal** [comment]
@marco-c Can I work on this issue ?

**Comment by marco-c** [comment]
Sure! See the CONTRIBUTING.md file, any issue which is not linked to a PR and not assigned is free for everyone to work on.

**Comment by Abhi-khandelwal** [comment]
> adding a "bugs" parameter, and call it in the right way in bug_retriever.py (the first time bugs=bugzilla.get_bugs(), the second and following times bugs=previously_inconsistent_bugs).

Actually I can't be able to understand that at second time what parameter we have to pass, as you explained.

**Comment by marco-c** [comment]
The first time you call the function, you have a list of bug IDs that are inconsistent. Then they are re-donwloaded. Now, the second time you call the function, you don't need to pass all bug IDs again, but you can just pass the bug IDs that were inconsistent at the first call.
