### ISSUE TITLE
Use the bug snapshot transform in the "uplift" model

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#60]
Depends on #5.

**Comment by marco-c** [comment]
To fix this issue, we'll need to do something similar to 2a440299d66d5a039bd683a353b80326dd5751df, but for the `uplift` model. We'd need to rollback to the time the uplift request was accepted or rejected.

**Comment by chidauri** [comment]
@marco-c  How to test if i've made correct changes for this issue?

**Comment by marco-c** [comment]
@chidauri make sure you can run the model, and write some tests similar to those in #189.

**Comment by ayush1999** [comment]
@marco-c The rollback should be done to the time when anything beginning with `approval-mozilla` was added to the change, right?

**Comment by marco-c** [comment]
We have to rollback to the time when the uplift was accepted (approval-mozilla-XXX == +) or rejected (approval-mozilla-XXX == -), but we don't have to rollback to when the uplift was requested (approval-mozilla-XXX == ?).
