### ISSUE TITLE
http service is currently broken

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#609]
In the logs, I see:
```
2019-06-21T07:04:09.778988+00:00 app[worker.1]: AttributeError: 'ComponentModel' object has no attribute 'get_extra_data'
```
but we have not deployed the patch which introduced `get_extra_data`.

@Lothiraldan maybe you deployed manually?

**Comment by marco-c** [comment]
> @Lothiraldan maybe you deployed manually?

If you did, feel free to close this issue.

If you didn't, we need to figure out why the service was deployed with some code which is not supposed to be deployed yet.

**Comment by Lothiraldan** [comment]
Latest deployment was made last sunday by heroku-relman-deployer@mozilla.com so I think it was automatically deployed.

**Comment by Lothiraldan** [comment]
The docker build task in data-pipeline.yml is cloning master https://github.com/mozilla/bugbug/blob/master/infra/data-pipeline.yml#L373, checking how to fix it
