### ISSUE TITLE
Create a classifier to suggest an assignee for a bug

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#61]
A new classifier, similar to the ones already present under bugbug/models/, should be created to predict the assignee of a bug.
This will be similar to the component model, except the label will be the assignee instead of the product/component.

**Comment by ayush9398** [comment]
I would like to work on this issue. 
@marco-c can you tell me where to start from? I have already forked the repo, cloned it on my system and have downloaded the requirements and test-requirements.

**Comment by LakshyAAAgrawal** [comment]
@ayush9398 I have already been working on this issue. Could you please take up another issue.

**Comment by ayush9398** [comment]
Sure, @LakshyAAAgrawal . All the best!
