### ISSUE TITLE
Make similarity script more generic so different similarity algorithms can be evaluated

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#611]
Right now, LSI is backed in the similarity script. We need to modify the similarity script to make it more generic so we can compare different algorithms.

**Comment by ayush-1506** [comment]
I'll add a cosine similarity model using tf-idf vectors and refactor the file a bit. @marco-c Shouldn't similarity.py be in scripts/ ?

**Comment by marco-c** [comment]
> I'll add a cosine similarity model using tf-idf vectors and refactor the file a bit

What are you going to use for the search?

> Shouldn't similarity.py be in scripts/ ?

similarity.py is a bit like model.py. The evaluation part should stay there, the "__main__" part should go in a script. But this is less important than making it generic.

**Comment by ayush-1506** [comment]
For the most similar bugs, I was thinking of a threshold value, (say 0.8), above which all pairs are classified as duplicate.

**Comment by marco-c** [comment]
@ayush-1506 we also have `k`, which is the maximum number of bugs returned. I'm not asking about that though, I'm wondering: once you have a vector representing a bug, how will you search for similar vectors? You can't iterate through all bugs, it will be *extremely* slow.

**Comment by marco-c** [comment]
You will need to use some library like nmslib, or https://scikit-learn.org/stable/modules/neighbors.html#finding-the-nearest-neighbors.

**Comment by marco-c** [comment]
Or even BM25 (https://github.com/mozilla/bugbug/issues/612).

**Comment by ayush-1506** [comment]
Once we have the word vectors, it can be treated as a clustering preblem. If this isn't a good idea, I don't see a way other than iterating the entire buds db.

**Comment by marco-c** [comment]
@ayush-1506 see my comments above. I think you don't really need clustering here, you just need a fast way to find similar vectors.

**Comment by ayush-1506** [comment]
Yep, I'll add this. Thanks!
