### ISSUE TITLE
Try BM25 as a similarity algorithm

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#612]
We can take inspiration from https://github.com/marco-c/uplift-analysis/blob/master/bm25.py.

Depends on #611.

**Comment by ayush-1506** [comment]
@marco-c The link doesn't seem to work.

**Comment by marco-c** [comment]
@ayush-1506 it should be available now.

**Comment by ayush-1506** [comment]
I'll try to see how this compares to other algorithms using https://pypi.org/project/rank-bm25/.
