### ISSUE TITLE
Add unit-testing for `spawn_data_pipeline` script

### ISSUE THREAD

**Issue by Lothiraldan** [mozilla/bugbug#613]
See https://github.com/mozilla/bugbug/pull/604#pullrequestreview-252923682

**Comment by probaku1234** [comment]
Should it test get_taskcluster_options?

**Comment by marco-c** [comment]
@probaku1234 this is about testing the whole spawn_pipeline script. It's not an easy issue, as it requires mocking the Taskcluster service.

**Comment by marco-c** [comment]
Since b568a2d8d552f4bce0ce444a9768e3250e7e382e, we are doing a few more checks, so I think we can consider this done.
