### ISSUE TITLE
Remove fallback on downloading xz files

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#624]
It's added in #524 because the current task have xz as artifacts. Once we make a successful deployment, we can switch to zst fully and remove the xz fallback.

**Comment by marco-c** [comment]
@x249wang do you want to do this cleanup?

**Comment by x249wang** [comment]
@marco-c Sure! Does this involve removing the code for downloading xz files in case the zst files are unavailable? When should this change occur?

**Comment by marco-c** [comment]
> Does this involve removing the code for downloading xz files in case the zst files are unavailable?

Exactly, and the related code.

> When should this change occur?

It can happen already, as I've deployed the zst change and we have zst datasets and models now (e.g. https://tools.taskcluster.net/groups/M4YroRtZRbyprTYhnmn2Kw/tasks/KJlvJjJvS-G5Ha1xHe6KlQ/runs/0/artifacts)
