### ISSUE TITLE
Use python slim images where possible in .taskcluster.yml

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#629]

**Comment by marco-c** [comment]
It might actually hardly be possible, because they are likely all using git (which is not in the slim image).

**Comment by marco-c** [comment]
We can likely use python:3-alpine though.

**Comment by kmehant** [comment]
@marco-c As installing git is easy, shall we use a slim version and add git installation to the `command` in the task cluster. I have noticed some general issue with alpine version? any thoughts? if yes I will take up the issue 😃

**Comment by marco-c** [comment]
@kmehant not sure if it will be faster to use the full blown Python image or installing git in Python slim/alpine.

Feel free to experiment with it. Issues are automatically assigned when there is a PR to fix them (see the CONTRIBUTING.md file).

**Comment by snowmanstark** [comment]
hi @marco-c I would like to work on it, can i please take this up?

**Comment by marco-c** [comment]
@snowmanstark sure, read CONTRIBUTING.md.

**Comment by snowmanstark** [comment]
I encounter the following error while I run `python3 -c 'from scripts import trainer; trainer.main()'`

```
WARNING: Logging before flag parsing goes to stderr.
I0821 15:38:34.177912 140020542736192 textcleaner.py:37] 'pattern' package not found; tag filters are not available for English
usage: -c [-h] [--lemmatization] [--training-set-size [TRAINING_SET_SIZE]]
          [--disable-url-cleanup] [--classifier {default,nn}] [--historical]
          model
-c: error: the following arguments are required: model
```
Maybe the error is caused due to mercurial version mismatch since the Docker definition at infra/dockerfile.commit_retrieval says `mercurial==5.1` but I didn't find mercurial version 5.1 for ubuntu (WSL)

**Comment by marco-c** [comment]
@snowmanstark the error is simply a missing argument. You need to pass the name of the model to train. E.g. `python3 -c 'from scripts import trainer; trainer.main()' defect`.

**Comment by marco-c** [comment]
See discussion in #3113, we decided to keep using full Python images.
