### ISSUE TITLE
Don't use cache when installing pip packages

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#646]
Both in the Dockerfiles and in the CI definition files.

**Comment by sumit4613** [comment]
@marco-c I am new to open source contribution . Can I take up this issue .

**Comment by Lothiraldan** [comment]
Sure. You can take up any issue that doesn't have a PR open against it.

**Comment by marco-c** [comment]
This was fixed by 830d88b1ebe96688048af3d3c654df2c8a364f21.
