### ISSUE TITLE
Remove pip from the commit-retrieval image

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#647]
We are installing pip2 to install mercurial. We should be able to, in a single layer, install pip2, install mercurial, then remove pip2 and clean. This should sliglthy reduce the image size.

**Comment by Shubhamchinda** [comment]
Hey, @marco-c  I'd like to solve this, any help would be appreciated.
Thanks!

**Comment by marco-c** [comment]
Hello @Shubhamchinda, feel free to work on it, until an issue is linked to a PR it is free to work on by anyone.
What you need to do is described in the first comment. The image is defined in infra/dockerfile.commit_retrieval.

**Comment by marco-c** [comment]
@trampfox if you're still interested in finishing this up, we need to make sure the scripts/commit_classifier.py script works too.

In order to test it, you need to run it setting the following environment variables:
BUGBUG_PHABRICATOR_URL=https://phabricator.services.mozilla.com/api/
BUGBUG_PHABRICATOR_TOKEN=YOUR_API_TOKEN_CREATED_ON_https://phabricator.services.mozilla.com/

Then you can run it with the diff ID parameter set to 125397.

**Comment by trampfox** [comment]
Ok, I'll take care of it.

**Comment by marco-c** [comment]
@trampfox it was actually an unrelated error, so I've reverted the revert. We can call this fixed!
