### ISSUE TITLE
Use bug reporter as a feature

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#69]

**Comment by manddy** [comment]
@marco-c I want to work on this issue but i am confused about the details about this project.Can you please guide me by giving an overall idea on this project.

**Comment by marco-c** [comment]
The bugbug/bug_features.py file contains functions that extract features from bugs. A new function should be added to extract the bug reporter (which is a categorical feature).

I suggest you read the code of bugbug/bug.py, bugbug/model.py and bugbug/bug_features.py to understand the whole project better.

**Comment by saurabhdaalia** [comment]
@marco-c Can you help me understand why bug reporter should be treated as a categorical feature?

**Comment by marco-c** [comment]
@saurabhdaalia it has all the properties of a categorical feature. Do you think it could be another kind of feature?

**Comment by saurabhdaalia** [comment]
@marco-c  yes, my bad. bug reporter qualifies as a categorical feature only. 
To clarify, do I need to only create a  new function in bug_features.py to extract the name of bug reporter only? or do I have to incorporate that as a feature as well?

**Comment by marco-c** [comment]
We should try to add it to the models and see if any model improves by adding the feature.
When you submit the PR, please make note of the results before/after adding the feature, and then we can decide for which models we should add it.

**Comment by saurabhdaalia** [comment]
@marco-c is there any specific IRC or communication channel for this specific project, where we can have discussions?

**Comment by marco-c** [comment]
#bugbug on irc.mozilla.org
