### ISSUE TITLE
Fix confusion matrix for multi-label models like bugtype

### ISSUE THREAD

**Issue by chidauri** [mozilla/bugbug#697]
**This is the error.**
> traceback (most recent call last):
File "run.py", line 159, in 
main(parse_args(sys.argv[1:]))
File "run.py", line 90, in main
model.train()
File "/home/harshit/Documents/bugbug/bugbug/model.py", line 256, in train
confusion_matrix = metrics.confusion_matrix(y_test, y_pred, labels=class_names)
File "/home/harshit/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 255, in confusion_matrix
raise ValueError("%s is not supported" % y_type)
ValueError: multilabel-indicator is not supported

**Comment by chidauri** [comment]
@marco-c fixed confusion_matrix problem by using multilabel_confusion_matrix but then imblearn doesn't support multilabel :(

**Comment by Lothiraldan** [comment]
@marco-c Where did you replaced the call from `confusion_matrix` to `multilabel_confusion_matrix` and do we need to update the tracking metrics?

**Comment by chidauri** [comment]
@Lothiraldan i meant i fixed it on my own clone , no change to this repo , sorry :P

**Comment by marco-c** [comment]
@chidauri we can skip the imblearn call when the model is multilabel
