### ISSUE TITLE
Enable responses automatically for all tests

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#723]
We can use pytest-responses to do this.

**Comment by Adrian-Tamas** [comment]
I assume that this would require something similar to what I have done in https://github.com/mozilla/code-review/issues/49 so I would like to help here also

**Comment by marco-c** [comment]
Correct! @Adrian-Tamas feel free to work on this!

**Comment by Adrian-Tamas** [comment]
Hi @marco-c . I am trying to run the tests locally to ensure that everything is ok without pytest-responses and I get errors of missing modules on test collections (infra and apispec - for this there is a TODO move http_service under bugbug) so the only way I can run the tests is using: "pytest --disable-pytest-warnings --ignore http_service/tests/test_app.py --ignore tests/test_hooks.py"

Running the tests like that I get a few failing tests for test_repository.py where it seems it does not find the temp files that are supposed to be under: /tmp/pytest-of-osboxes/pytest-2/test_download_commits0/repos/remote/ and  /tmp/pytest-of-osboxes/pytest-2/test_hg_log0/repos/remote/ . The folder structure is created until there but the files(.hg/pushlog2.db) are not there. I have installed bugbug locally with both extra options also and all dependencies and I have also installed mercurial. Am I missing anything that I should have installed and is not the requirements file?

**Comment by marco-c** [comment]
> I am trying to run the tests locally to ensure that everything is ok without pytest-responses and I get errors of missing modules on test collections (infra and apispec - for this there is a TODO move http_service under bugbug)

I think you simply need to install the HTTP service requirements and they will work: `pip3 install -r http_service/requirements.txt`.

> Am I missing anything that I should have installed and is not the requirements file?

Did you setup Mercurial as specified in the README in the "Running the repository mining script" section?

**Comment by Adrian-Tamas** [comment]
[testoutput.txt](https://github.com/mozilla/bugbug/files/3595194/testoutput.txt)
Sorry for the late reply but I managed to break my vm twice and had to rebuild everything. Btw when trying to clone mozilla-central using mercurial 5.1 I kept getting "Connection reset by peer" but it worked with the old mercurial version from apt

I have set up mercurial as in the  "Running the repository mining script" using all the values from the infra module with both the old mercurial version from apt and with the 5.1 from pip (python 2.7), I am getting a bit further along but I still get errors in the tests when running locally. Please see the attached test results.

**Comment by marco-c** [comment]
I'm not sure why they are failing for you :(
Anyway, you can ignore those local failures and let CI run the mercurial tests for you.
