### ISSUE TITLE
Comparison between similarity models

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#738]
We should check where we stand and compare the similarity models (with all bugs).

**Comment by ayush-1506** [comment]
For comparing on all bugs, I'm trying to run the models on colab. I'll let you know when I have some results. (The colab session keeps terminating for some reason.)

**Comment by ayush-1506** [comment]
Ok, so I was able to get the result for the LSI model (before the notebook terminated, so I've restarted it for another model now):
```
Recall @ 1: 13.626943005181346%
Recall @ 5: 15.911917098445597%
Recall @ 10: 16.134715025906736%
Precision @ 1: 0.6685768863419294%
Precision @ 5: 2.96211397644051%
Precision @ 10: 1.9879019420566857%
Recall: 16.17616580310881%
Precision: 1.9879019420566697%
MAP@k : 6.065229804705025%
```

**Comment by ayush-1506** [comment]
Got the Neighbors model results!
```
Recall @ 1: 13.766314481044125%
Recall @ 5: 15.661901802361717%
Recall @ 10: 15.87424901595194%
Precision @ 1: 7.213803641920285%
Precision @ 5: 3.1402011969946555%
Precision @ 10: 1.954667006239662%
Recall: 15.900145017609283%
Precision: 2.1623525268533195%
MAP@k : 9.593198207932758%
```

**Comment by suhaibmujahid** [comment]
The similarity model has been dropped in https://github.com/mozilla/bugbug/pull/3870
