### ISSUE TITLE
Move zstandard compression and decompression into utils module

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#747]
We want to move code such as https://github.com/mozilla/bugbug/blob/660935c0dbb4703ff71c1669767e5afd8a57f40e/scripts/trainer.py#L19-L23, which is duplicated in several places, in utils.py and use it in place of the duplicated code.

**Comment by kanurag94** [comment]
Only zst or the compression and decompression function? (including gzip)

**Comment by dishvyas** [comment]
Can this bug be assigned to me??

**Comment by chidauri** [comment]
@dishvyas Issues are considered not assigned, until there is a PR linked to them. Feel free to work on any unassigned "good-first-bug" issue.

**Comment by dishvyas** [comment]
So do i need to just move the zstd calls from other files and create a function in utils module that can be used to carry out compression and decompression??

**Comment by marco-c** [comment]
We want to move code such as https://github.com/mozilla/bugbug/blob/660935c0dbb4703ff71c1669767e5afd8a57f40e/scripts/trainer.py#L19-L23, which is duplicated in several places, in utils.py and use it in place of the duplicated code.
