### ISSUE TITLE
Pyemd is missing in requirements

### ISSUE THREAD

**Issue by villmow** [mozilla/bugbug#811]
The library pyemd is missing in the requirements (used in evaluate_similarity.py).

**Comment by marco-c** [comment]
Thanks for noticing! We should add it to extra-nlp-requirements.txt.

**Comment by ayush-1506** [comment]
(Although this won't be a requirement once #813 is merged)

**Comment by villmow** [comment]
Maybe note that this project requires Python > 3.7. For example for the initializer kwarg on this line: https://github.com/mozilla/bugbug/blob/001fba1242f2467defcb32a2bb644c1cc385a140/bugbug/repository.py#L659

**Comment by marco-c** [comment]
It's specified in setup.py, but I guess specifying it in the README also won't hurt.

**Comment by Patil2099** [comment]
Can I work on this? Do I just have to add Pyemd to README File?

**Comment by marco-c** [comment]
You simply need to add it to the requirements file (the nlp one).
