### ISSUE TITLE
Create constant sets directly instead of converting lists into sets

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#82]
Instead of doing something like `set(['val1', 'val2'])`, we should do `{'val1', 'val2'}`.

**Comment by ayush1999** [comment]
@Jeetu95 are you working on this? This involves a few subtle changes, so if you're not, I'll open a quick PR.

**Comment by Jeetu95** [comment]
Yes @ayush1999, I am working on this

**Comment by marco-c** [comment]
I'm adding some rules to the README.md to avoid conflicts. PRs with `reserved-for-beginners` label will be reserved to people who have never committed in the project before. Every issue is to be considered as being unassigned until there is a PR linked to it.
