### ISSUE TITLE
Add configuration parameters to generate_sheet script

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#821]
We should make a couple of things configurable:
- the time span (currently it's one week);
- the confidence threshold (currently it's 0.7).

**Comment by WaxXwing** [comment]
Hey @marco-c!
This is my first time in open source and I would really like to contribute to this. 
I guess passing the time span and threshold as arguments will do?

**Comment by marco-c** [comment]
Yes!

**Comment by WaxXwing** [comment]
So what next?

**Comment by WaxXwing** [comment]
Hey @marco-c ,
I wanted to know what might be the range values for the time span?
Will it always be in days?

**Comment by marco-c** [comment]
Yeah, I think we can make it an int which specifies the number of days.

**Comment by WaxXwing** [comment]
Sorry if this is silly, but I can't seem to push my changes to the remote repo

**Comment by marco-c** [comment]
@WaxXwing you'll need to push your changes to your fork of the repo. I suggest reading a guide on how to use git.
