### ISSUE TITLE
Add a main function to all our console_scripts so they are more easily runnable

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#831]
https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

We simply need to add:
```Python
if __name__ == "__main__":
    main()
```
at the end of every script.

**Comment by RishiMagudia** [comment]
see https://github.com/mozilla/bugbug/pull/837

**Comment by marco-c** [comment]
We need to do 14908e5a066966af9e2a6d76a3e29c89fcd81f78 for all scripts.

**Comment by shishirjha** [comment]
Hi, if this is still open, can I work on this?

**Comment by marco-c** [comment]
#936 missed scripts/regressor_finder.py.
