### ISSUE TITLE
Add an option to the bug_classifier script to download the model when it doesn't exist

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#832]

**Comment by chidauri** [comment]
@marco-c `f"https://index.taskcluster.net/v1/task/project.relman.bugbug.train_{model_name}.latest/artifacts/public/{model_file_name}.zst"` is this the right url ?

**Comment by marco-c** [comment]
Yes, for example https://index.taskcluster.net/v1/task/project.relman.bugbug.train_component.latest/artifacts/public/componentmodel.zst.

**Comment by chidauri** [comment]
@marco-c for some models it is working fine(`stepstoreproduce`) but for some the zstdecompression isn't working :(

> upliftmodel does not exist. Downloading the model....
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/harshit/Documents/bugbug/scripts/bug_classifier.py", line 80, in main
    classify_bugs(args.model, args.classifier)
  File "/home/harshit/Documents/bugbug/scripts/bug_classifier.py", line 35, in classify_bugs
    dctx.copy_stream(input_f, output_f)
zstd.ZstdError: zstd decompressor error: Unknown frame descriptor

**Comment by marco-c** [comment]
You need to check if the model is available at the URL, not all models are.
