### ISSUE TITLE
Remove `feature_names` parameter from model.print_feature_importances

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#834]
The `print_feature_importances` function can simply access the feature names of the model directly (self.get_human_readable_feature_names()), so the `feature_names` argument is not needed.

**Comment by Patil2099** [comment]
@marco-c  If this is still open can I work on it?

**Comment by marco-c** [comment]
@Patil2099 read CONTRIBUTING.md. You can work on any open issue which has no PR linked to it.

**Comment by pushpy** [comment]
@marco-c I am a complete beginner and I also want to fix this bug.

**Comment by marco-c** [comment]
Please read the CONTRIBUTING file like I said above. This issue has a PR open linked to it, so it's taken (you can come back to it if the PR gets closed without merging). You can take any other issue which has no PR linked to it, you don't need to ask to work on an issue (you can ask if you need more information, but please specify what information you need).
