### ISSUE TITLE
When cleaning up DLL names, differentiate between third-party DLLs and Firefox ones

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#88]
We're currently replacing all DLL names with a _DLL_NAME_ token, but we should differentiate between third-party DLLs and Firefox DLLs (XUL.dll, and so on).

**Comment by marco-c** [comment]
At https://github.com/mozilla/bugbug/blob/008c34b83a3d73dc8c9b007a98367dbacbf78233/bugbug/bug_features.py#L302, we should only cleaup third-party DLLs, and not Firefox ones.

So, for example xul.dll should still be xul.dll and not replaced with __DLL_NAME__. Same with mozglue.dll, libxul.so, and so on.

To get all Firefox DLLs, you can either download the archives containing the Firefox binaries from a URL such as https://ftp.mozilla.org/pub/firefox/nightly/2019/02/2019-02-27-10-44-26-mozilla-central/ (firefox-67.0a1.en-US.win64.zip, firefox-67.0a1.en-US.mac.dmg, firefox-67.0a1.en-US.linux-x86_64.tar.bz2), or install Firefox on the different OSes, go in the installation directory and check which DLLs are present.

**Comment by LakshyAAAgrawal** [comment]
I would like to take this up. Could I be assigned?

**Comment by marco-c** [comment]
@LakshyAAAgrawal feel free to work on any open issue. See https://github.com/mozilla/bugbug#contributing, all issues are unassigned until there is a PR open to fix them.

**Comment by LakshyAAAgrawal** [comment]
Could I create a file "firefox_DLLs.json" which contains a list of all firefox library files including *.so and *.dll files, and then load this file when the function "cleanup_dll" is called, and then do the needful for differentiating?

**Comment by marco-c** [comment]
You can just hardcode the DLL names in a constant that you define right before cleanup_dll, a separate file is overkill.

**Comment by LakshyAAAgrawal** [comment]
In the test file [test_cleanup_functions.py](https://github.com/mozilla/bugbug/blob/master/tests/test_cleanup_functions.py#L48-L53), the second test asserts that 'libxul.so' gets converted to '\_\_DLL_NAME\_\_', as shown:
```python
def test_cleanup_dll():
    tests = [
        ('Crashing thread: 0 scdetour.dll scdetour.dll@0x2dd77', 'Crashing thread: 0 __DLL_NAME__ __DLL_NAME__@0x2dd77'),
        ('Crash in libxul.so@0x287ad36 | libxul.so@0x270c062', 'Crash in __DLL_NAME__@0x287ad36 | __DLL_NAME__@0x270c062'),
        ('Crash in libsystem_pthread.dylib@0x14fc', 'Crash in __DLL_NAME__@0x14fc')
    ]
```

However, as pointed out [above](https://github.com/mozilla/bugbug/issues/88#issuecomment-467889054) by @marco-c :

> So, for example xul.dll should still be xul.dll and not replaced with '\_\_DLL_NAME\_\_'. Same with mozglue.dll, libxul.so, and so on.

Therefore, I think this test case should be updated. Am I missing something here?

**Comment by marco-c** [comment]
Yes, it should be updated.
