### ISSUE TITLE
Install Mercurial without pip

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#922]
Like we are doing in https://github.com/mozilla/code-coverage/blob/master/bot/Dockerfile, we should try changing infra/dockerfile.commit_retrieval to install Mercurial without pip.

**Comment by dotslash21** [comment]
I would like to work on this issue. I'm a beginner and this would be my first bug, so I'd very much appreciate any advice on how to get started.

**Comment by marco-c** [comment]
We want to modify our Dockerfile to stop using pip to install Mercurial, and download it directly like that script does (switching to a script separate of the Dockerfile is out of scope).

**Comment by pushpy** [comment]
@marco-c I am a total beginner and I also want to contribute to fix this bug. help me here!

**Comment by marco-c** [comment]
There is already a PR open to fix this, so the issue is taken. You can work on another good-first-issue (or come back to this if/when the PR gets closed without merging).

**Comment by marco-c** [comment]
From #928, it looks like using pip is more space efficient, so I'll close this.
