### ISSUE TITLE
For binary models, plot and check the classes separately

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#945]
For binary models, we are particularly interested in seeing the metrics per class and not only on average.

scripts/analyze_training_metrics.py is currently plotting and checking the "average", but for binary classes we want to plot and check the two classes separately.

To test the script, first run scripts/retrieve_training_metrics.py to retrieve the metrics files.

**Comment by kaushiksk** [comment]
Can you elaborate a bit on this, and direct me towards which files I need to be looking into?

**Comment by datavizard** [comment]
Is anybody working on this? If not, I'd be happy to help, given some more context of the problem.

**Comment by marco-c** [comment]
@datavizard read the contributing rules, if there is no PR attached to an issue, it is unassigned. So, feel free to work on this (@kaushiksk feel free to work on this too, I had missed your message).
I've added more details in the first comment.

**Comment by rishishounak** [comment]
I would like to work on this but I dont have any previous experience so please guide me

**Comment by marco-c** [comment]
Hello @rishishounak, you can follow the steps in the README to set the repository up, then you can run the scripts/retrieve_training_metrics.py script to make sure it works for you. Once everything is set up correctly, you can try to apply the required change (explained in the first comment of this issue) to the scripts/retrieve_training_metrics.py file.
