### ISSUE TITLE
Stop checking standard deviation

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#946]
It changes too much. We should either have a larger threshold than 5%, or stop checking it altogether.

**Comment by Lothiraldan** [comment]
If my understanding of statistics is correct, the smaller standard deviation we get, the better, right @calixteman?

**Comment by marco-c** [comment]
Yes, I think that is the case.
The problem is that currently it changes too much between one training and another, and it can get worse by more than 5% (which is our current threshold). We should increase the threshold, and e.g. only warn if it gets worse by 10%.

**Comment by Lothiraldan** [comment]
https://github.com/mozilla/bugbug/pull/930/commits/8e437719380708116596ce84f6bb1f87373c202c disabled checking the standard deviation

**Comment by marco-c** [comment]
Fixed by 099f9db.
