### ISSUE TITLE
Don't store /tmp/bugbug in Docker image

### ISSUE THREAD

**Issue by marco-c** [mozilla/bugbug#970]
We are copying bugbug (https://github.com/mozilla/bugbug/blob/f749fc8b95ff86238beaed502d305bb950fddaff/infra/dockerfile.base#L12) and then installing it with pip (https://github.com/mozilla/bugbug/blob/f749fc8b95ff86238beaed502d305bb950fddaff/infra/dockerfile.base#L13). In the end we end up with two copies of the bugbug source code, one in /tmp/bugbug and one in /usr/lib.

**Comment by imskr** [comment]
Assign this!  I want to work on this!

**Comment by marco-c** [comment]
Feel free to work on any open issue which is not assigned, issues are assigned only when there is a PR open to fix them (read CONTRIBUTING.md).
